### ISSUE TITLE
unique jobs

### ISSUE THREAD

**Issue by aartiles** [Automattic/kue#100]
I would like that the `jobs.create` fails if an identical job is already in the system. Is there any way to acomplish this?

**Comment by lykmapipo** [comment]
@aartiles @holic @gkoychev 

Though this is closed you may give a try to [kue-unique](https://github.com/lykmapipo/kue-unique)

**Comment by tonyxiao** [comment]
@bulkan @drudge what's your recommendation for how to handle best handle this in the application layer?

**Comment by bulkan** [comment]
hey @tonyxiao ! Sorry but it's been a few years since I've used `kue` and I've forgotten a lot of context on how it works.
