### ISSUE TITLE
Kue connecting to default database instead of provided via url

### ISSUE THREAD

**Issue by moustacheful** [Automattic/kue#1012]
Hello!. 
As title says, i'm having issues using redis urls with a provided database that would otherwise be supported by `node-redis`.

Using kue v0.11.5 on node v6.9.1

I'm doing the following:
```js
import kue from 'kue';
const queue = kue.createQueue({ redis: 'redis://localhost:6379?db=3' });
```

After creating a few jobs, I see everything kue-related is in db 0, instead of the provided database index. Checked the source, and on line 32 of *kue/lib/redis.js* there's the following: 

 ```js
    options.redis = {
      port: conn_info.port || 6379,
      host: conn_info.hostname,
      db: (conn_info.pathname ? conn_info.pathname.substr(1) : null) || 0, // Will always output 0 in the provided format
      // see https://github.com/mranney/node_redis#rediscreateclient
      options: conn_info.query
    };
```

A quick fix would be attempting to get the the db value from the db
```js
db: (conn_info.pathname ? conn_info.pathname.substr(1) : null) || conn_info.query.db || 0, // Will always output 0 in the provided format
```

I can provide a pull request if necessary.

**Comment by behrad** [comment]
You are free to open a PR, please :)
