### ISSUE TITLE
watchStuckJobs in multi server deployments of Kue

### ISSUE THREAD

**Issue by mmarshak** [Automattic/kue#1015]
Issue  #556 fix the issue of prompt in multi server environment behind a load balancer.
What about watchStuckJobs? If I have multiple nodes server that use Kue behind a load balancer, is it safe to call watchStuckJobs on each one upon restart? If not, how should you suggest to elect a master? Currently the severs are not communicating one with each other.

**Comment by behrad** [comment]
`watchStuckJobs`  is deprecated and should not be used any more
