### ISSUE TITLE
Redis memory increases linearly

### ISSUE THREAD

**Issue by tsheaff** [Automattic/kue#1019]
Been running on production now for a day, and our Redis memory usage has only gone up, never down.  Is there a way to evict completed jobs from redis once they're completed to avoid our storage simply growing forever @behrad ?

Thanks, would be super helpful.

**Comment by tjsail33** [comment]
https://github.com/Automattic/kue#job-cleanup

**Comment by tsheaff** [comment]
Thanks @tjsail33
