### ISSUE TITLE
Very slow processing speed when there are too much job done

### ISSUE THREAD

**Issue by GuroKung** [Automattic/kue#1020]
I have tried using kue in an application which create a job for sending bunch of messages to users
What happens is after several hundred thousand (or millions) of job is done, the processing speed becomes very very slow unless I have to delete old job done data continuously.

**Comment by behrad** [comment]
Kue is not maintaining any done job data in memory, and some are processing millions of jobs/day continuously, so there may be a problem with you Redis instance and so the system memory.

**Comment by DevBrent** [comment]
You may have luck not using job events by disabling JobEvents if you're not using them.
