### ISSUE TITLE
Allow exponential backoff to specify a maximum delay

### ISSUE THREAD

**Issue by Darkhogg** [Automattic/kue#1025]
As it is now, a task with `exponential` backoff will keep duplicating its delay after a failed attempt indefinitely.  This can make a task be delayed for days, weeks, months, years and so on. It should be possible to be able to specify a max delay so that the exponential backoff can reach a sensible maximum amount and not increase anymore.

Note that this is technically possible to achieve right now using a function, but that requires the use of `eval`, which is suboptimal.

**Comment by behrad** [comment]
`Job#attempts` should trigger the limit of re-tries

**Comment by Darkhogg** [comment]
Yes, but some jobs need a big number of attempts (or even infinite retries) without the time between those retries becoming huge.  Starting at 1 second, in just 15 attempts you already have 9 hours delay between them. 30 attempts would take many years.

**Comment by behrad** [comment]
You are welcome to create a PR then.
