### ISSUE TITLE
fn is not a function

### ISSUE THREAD

**Issue by lszjl** [Automattic/kue#1026]
stack: 
   [ 'TypeError: fn is not a function',
     '    at Job.<anonymous> (D:\\projects\\client-mgmt-api\\node_modules\\kue\\lib\\queue\\job.js:548:7)',
     '    at normal_reply (D:\\projects\\client-mgmt-api\\node_modules\\redis\\index.js:721:21)',
     '    at RedisClient.return_reply (D:\\projects\\client-mgmt-api\\node_modules\\redis\\index.js:819:9)',
     '    at JavascriptRedisParser.returnReply (D:\\projects\\client-mgmt-api\\node_modules\\redis\\index.js:192:18)',
     '    at JavascriptRedisParser.execute (D:\\projects\\client-mgmt-api\\node_modules\\redis-parser\\lib\\parser.js:560:12)',
     '    at Socket.<anonymous> (D:\\projects\\client-mgmt-api\\node_modules\\redis\\index.js:274:27)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at TCP.onread (net.js:548:20)' ] }

**Comment by behrad** [comment]
it seems a callback is not passed to one of method calls somewhere in your code.
However we should make it safer.

**Comment by lszjl** [comment]
but how to use function create and process,I added all job into queue,before use then function process。now,at the second processing the job,this error turned up.

**Comment by behrad** [comment]
Check documentation
