### ISSUE TITLE
What does concurrency mean in context of multiple servers? And what does watchStuckJobs do?

### ISSUE THREAD

**Issue by tylercollier** [Automattic/kue#1032]
If I run Kue on multiple servers all connected to the same Redis instance, what does the concurrency value mean? Let's say I have 2 servers, and I run `queue.process('email', 20, function(job, done){...})` on each server. Does that mean each server will handle 20 jobs, for a total of 40? I'm *thinking* with the use of BLPOP that this is correct.

Let's say, to make sure I'm clear, that one server's code has concurrency set to 20, and another at 30. Does that mean there's a total of 50 jobs running at a time? Because another theory my teammates and I had was that it would basically use the max between the concurrency numbers, so in this example, 30 total.

---

Would you be willing to explain what `queue.watchStuckJobs(interval)` does? I see it issue some huge command to Redis that I don't understand.

**Comment by behrad** [comment]
> Let's say, to make sure I'm clear, that one server's code has concurrency set to 20, and another at 30. Does that mean there's a total of 50 jobs running at a time?

Exactly.




> Would you be willing to explain what queue.watchStuckJobs(interval) does? I see it issue some huge command to Redis that I don't understand

It was trying to fix a race-condition bug inside kue, however this is deprecated now
