### ISSUE TITLE
jobs are completed at the same time from different routes

### ISSUE THREAD

**Issue by SkateFreak** [Automattic/kue#1036]
i run ```mocha``` tests with```supertest```, ```passport``` and ```passportStub```,
i mock 2 users login and try to queue a job for each request on ```post``` endpoint.

my console outputs:

    job 1 started
    job 2 started
    job 1 completed
    job 2 completed

any ides for what do i miss? thanks

**Comment by behrad** [comment]
Please provide some code and re-open
