### ISSUE TITLE
Simple queue question

### ISSUE THREAD

**Issue by patrikx3** [Automattic/kue#1040]
Do you think I should use
https://github.com/antirez/disque
vs Kue?

Do you know about anything? I need a queue and I am deciding Disque vs Kue.

I am thinking Kue is enough I use Redis, I guess I would need another server...

What do you know about?

Thanks so much!

**Comment by behrad** [comment]
Start with Kue, as it is more abstract and easier to start. Switch to Disque if you faced issues with Kue.
