### ISSUE TITLE
Remove redis open connections when Job is completed

### ISSUE THREAD

**Issue by pmaganti** [Automattic/kue#1051]
This is more of a question than issue.

Does anyone know how to release the open redis connection after Job completed? For example, if there 10 jobs are on queue, 20 connections are opening for redis and this can be seen using
```sudo lsof -i tcp:6379 | wc -l```

I need those connections to be closed to make sure the file open limit can be shared across other processes.

**Comment by pmaganti** [comment]
I would like to know the status here. If this is not a valid question, please close it.

**Comment by behrad** [comment]
Redis connections are based on your worker concurrency, and not per job!
So don't worry for reaching max open file handle :)
