### ISSUE TITLE
Difference between inactive and delay

### ISSUE THREAD

**Issue by hoangphuoc25** [Automattic/kue#1055]
Hello. I'm having some problems with my kue workers. After running for some time a job just got stuck in `inactive`. I'm trying to debug it and have a question: what's the difference between `inactive` and `delayed` state? Sometimes I see jobs got promoted from `delayed` to `inactive` first before changing to `active`, sometimes they got promoted straight to `active`.

**Comment by IvanMMM** [comment]
`Delayed` job promoted to `inactive`, that's true. After it Kue scans for inactive jobs and if there are processors for it, takes X jobs from queue, sets `active` status and processes them.
