### ISSUE TITLE
[Q] How to process only one job and then shutdown?

### ISSUE THREAD

**Issue by pulkitsinghal** [Automattic/kue#1070]
If I run `node worker.js` then the process stays alive and waits for any jobs to process.
And ofcourse it processes any jobs it can find ... BUT

> Is there a way to shutdown once a job is processed?

I know it sounds strange but for me this is important.

Can I hook into the `done` method somehow and pass it an anonymous function to execute a `queue.shutdown`?

Any ideas or solutions are welcome.

**Comment by behrad** [comment]
Strange usecase, however you may be able to use `pause` to pause the processing, call `done` and then shutdown all kue context. Don't know if this works. :)

**Comment by pulkitsinghal** [comment]
Thank you @behrad, I will let you know what happens. And another strange follow up:

> If I do not setup `job.on(...)` for `complete, failed, progress` and only use `job.save(...)` then does that mean Kue will not wait for the result and I can treat the job POST to be a `fire and forget` async behaviour?

**Comment by pulkitsinghal** [comment]
Well I ran an experiment, simple enough and it seems that the producer waits as long as needed. So now my question is how can I use Kue so that the producer saves (POSTs payloads) and then lets it go (assuming there aren't any connection errors and message post was successful) and returns immediately?

**Comment by pulkitsinghal** [comment]
Feedback on:

> Strange usecase, however you may be able to use pause to pause the processing, call done and then shutdown all kue context. Don't know if this works. :)

This did not work:
```
    done(); // <--------
    console.log((new Date()).toLocaleString(), 'WILL TRY TO PAUSE NOW...');
    ctx.pause( 5000, function(err){
      console.log((new Date()).toLocaleString(), 'Worker is paused...');
      setTimeout( function(){
        ctx.shutdown(); // <--------
      }, 10000 );
    });
```

This also did not work:
```
    done(); // <--------
    console.log((new Date()).toLocaleString(), 'WILL TRY TO PAUSE NOW...');
    ctx.pause( 1000, function(err){
      console.log((new Date()).toLocaleString(), 'Worker is paused...');
      setTimeout( function(){
        console.log( (new Date()).toLocaleString(), 'ctx based Kue shutdown will now commence');
        ctx.shutdown(10, function(err) {
          console.log( (new Date()).toLocaleString(), 'ctx based Kue shutdown', err||'' );
          process.exit( 0 ); // <--------
        });
      }, 10000 );
    });
}
```

This did work:
```
    done();
    console.log((new Date()).toLocaleString(), 'WILL TRY TO PAUSE NOW...');
    ctx.pause( 5000, function(err){
      console.log((new Date()).toLocaleString(), 'Worker is paused...');
      setTimeout( function(){
        exit(); // <--------
      }, 10000 );
    });
...
function exit(){
  var TIMEOUT = 1;
  queue.shutdown( TIMEOUT, function(err) {
    console.log( (new Date()).toLocaleString(), 'Kue shutdown', err||'' );
    process.exit( 0 );
  });
}
```

Not sure if you find that strange or expected. Being able to shutdown from queue but not the context *shrug* ... or its entirely possible that i may have made a mistake here *shrug* don't know.

**Comment by pulkitsinghal** [comment]
> Strange usecase, however you may be able to use pause to pause the processing, call done and then shutdown all kue context. Don't know if this works. :)

@behrad with hints given [here](https://github.com/Automattic/kue/blob/master/examples/shutdown.js)

This [approach](https://gist.github.com/pulkitsinghal/a38e2321643f1b103aa49c27755d0805) worked the best.

I tested it by pre-populating many jobs and while other approaches at times made the mistake of processing a lot of stuff (or maybe i read the logs wrong) ... this [approach](https://gist.github.com/pulkitsinghal/a38e2321643f1b103aa49c27755d0805) worked on only one payload everytime.

Thanks for answering my question.

**Comment by pulkitsinghal** [comment]
I think the docker logs were confusing me.
> the way container logs were being colored and spit out on my console, made it seem like one worker run was handling multiple jobs before shutting down sometimes. 

This [test](https://gist.github.com/pulkitsinghal/7b66d2dce2af8939bfc13365544ee365#file-showthatbadcodecanleakdataacrossjobs-js) shows a worker that handles multiple jobs where bad code leaks data across jobs.

This [test](https://gist.github.com/pulkitsinghal/7b66d2dce2af8939bfc13365544ee365#file-avoidleakswithonejobperworkerrun-js) proves that a worker which can properly shutdown after one job is finished, will not leak data across jobs.

**Comment by behrad** [comment]
Can you sent me a working code snippet that reproduces the problem?

**Comment by pulkitsinghal** [comment]
Hey @behrad there isn't a problem with `Kue`, my experiment was focused around segregating and containing badly written **job** code.

Do you still want a working project? The code itself is upstairs mention in links.

**Comment by behrad** [comment]
not needed if you think so :)
