### ISSUE TITLE
[Q] How to save a job but not wait for results?

### ISSUE THREAD

**Issue by pulkitsinghal** [Automattic/kue#1071]
Another strange follow up:

> If I do not setup `job.on(...)` for `complete, failed, progress` and only use `job.save(...)` then does that mean Kue will not wait for the result and I can treat the job POST to be a `fire and forget` async behaviour?

The thing is that I don't want a producer (my webserver or restApiServer) to wait for results. My workers can handle the reporting of results directly to the DB on their own.

cc @harshadyeola @aquid

**Comment by pulkitsinghal** [comment]
Well I ran an experiment, simple enough ... and it seems that the producer waits as long as needed. Omitting `complete, failed, progress` does not tell it to skip the wait for a job result.

So now my question is:

> How can I use Kue so that the producer saves (POSTs payloads) and then returns immediately?

... assuming there aren't any connection errors and message post was successful

**Comment by aquid** [comment]
@pulkitsinghal So according to your comments, what I understand is that the save method that you are talking about is nothing else than just a POST method which will send success/error after execution and processing of data. So does that mean we can't just acknowledge back with received status to our producers?

**Comment by pulkitsinghal** [comment]
@behrad - At a high level, do you think that a change such using `enqueueOnly` flag which skips the [following line](https://github.com/Automattic/kue/blob/master/lib/queue/job.js#L804) when its `enqueueOnly:true` work?

```
Job.prototype.save = function( enqueueOnly, fn ) {
    ...
    (enqueueOnly) ? doNnothing() : self.subscribe(function() {...
```

**Comment by behrad** [comment]
1. producer will not block/wait, it only checks a subscription on job event topics.

2. if you want to turn this subscription off, you can disable `jobEvents` mentioned [here](https://github.com/Automattic/kue#job-events)
