### ISSUE TITLE
I would like to ask if Kue supports deploying under multiple servers, because I didn't see the relevant instructions

### ISSUE THREAD

**Issue by zackCzy** [Automattic/kue#1072]
I would like to ask if Kue supports deploying under multiple servers, because I didn't see the relevant instructions
Opening Kue on a multi server can cause the task to be repeated

**Comment by orgoldfus** [comment]
If all instances work against a single redis server, it should work just fine (tasks won't be repeated).
That said, notice that **events** will be dispatched to all servers: https://github.com/Automattic/kue/issues/809

**Comment by behrad** [comment]
Use a single redis instance, configure your Kue processes to use it :)
