### ISSUE TITLE
Redis Cluster support

### ISSUE THREAD

**Issue by rrichardson** [Automattic/kue#1095]
I recently attempted to run kue against a Redis cluster in AWS and got a parser error. 

Looking into it.. I find this :  https://github.com/NodeRedis/node_redis/issues/574

What is the interest in switching the underlying redis client to one that supports Redis in cluster mode (and has been for the last 2 years) 

A cursory glance indicates that the options are : 

https://github.com/thunks/thunk-redis
https://github.com/luin/ioredis
https://github.com/gosquared/redis-clustr

If this is desired, then I can probably put together a PR.

**Comment by jdesboeufs** [comment]
You can already do that:
https://github.com/Automattic/kue#using-ioredis-client-with-cluster-support

**Comment by rrichardson** [comment]
Oh.  I swear I read that at least twice as well.   Nevermind then :)
