### ISSUE TITLE
Make docs more explicit and readableame 

### ISSUE THREAD

**Issue by stern0** [Automattic/kue#1120]
The documentation is good and extensive but at times a bit confusing. 
An example is the following in the docs:
```js
var kue = require('kue')
  , queue = kue.createQueue();
```
The above is less explicit and which could take one more time to get around than needed.
I personally think the following is more readable, explicit and could replace the above:
```js
const kue = require('kue');
const queue = kue.createQueue();
```
or
```js
let kue = require('kue');
let queue = kue.createQueue();
```
Same accounts for most of the documentation. For example the following:
```js
var job = queue.create('email', {
    title: 'welcome email for tj'
  , to: 'tj@learnboost.com'
  , template: 'welcome-email'
}).save( function(err){
   if( !err ) console.log( job.id );
});
```
The trailing commas at the start of every key makes it confusing to read, I think the following is much better and anyone reading the docs should not be spending too much figuring out what it is:
```js
const job = queue.create('email', {
    title: 'welcome email for tj',
    to: 'tj@learnboost.com', 
    template: 'welcome-email'
}).save( function(err){
   if( !err ) console.log( job.id );
});
```
Here the trailing commas are at the end like standard key value pairs making it easier to read.

**Comment by behrad** [comment]
Can you please create a PR?

**Comment by cryst10** [comment]
@behrad yes I will Thanks.

**Comment by cryst10** [comment]
@behrad  I cannot create PR since I do not permissions
