### ISSUE TITLE
Whenever I use queue.watchStuckJobs, It throws the error ReplyError: ERR unknown command 'script'

### ISSUE THREAD

**Issue by bron10** [Automattic/kue#1128]
My config : 
redis : 4.0.2
kue : "0.11.6"

I guess watchStuckJobs uses some kind of 'script' command and has some issue compatibility issue.

**Comment by bron10** [comment]
Also queue.process throws 'ERR wrong number of arguments for 'set' command'

**Comment by bron10** [comment]
Please close this issue, It was a mistake due to an environment variable in code. Sorry for the inconvenience.

**Comment by henkeklein** [comment]
> Please close this issue, It was a mistake due to an environment variable in code. Sorry for the inconvenience.

What was the wrong environment variable?
