### ISSUE TITLE
queue.process variables

### ISSUE THREAD

**Issue by lucasreppewelander** [Automattic/kue#1129]
Hello, on the `queue.process()` can I get the first parameter as a variable? I'm having like 6 different jobs, and would love to be able to write just one queue process just to keep my code down, as right now there are 6 exact equal functions just calling other functions with strings instead of variables.

I was thinking something like

```
queue.process(type, 1, (job, done) => {
    jobs[type](job.data).then(result) => {
        done();
    }
});
```

**Comment by behrad** [comment]
I think you can use `job.type` if not mistaken!
