### ISSUE TITLE
Redis randomly "refuses" connection?

### ISSUE THREAD

**Issue by felixchan** [Automattic/kue#120]
Hi,

I'm using kue  0.4.0 (10 workers, 1 redis server).  After letting everything run for a day or so, sometimes, redis will reject the connection.

```
Error Error: Redis connection to MY_IP:6379 failed - connect ECONNREFUSED
```

And from my redis-server logs, I see random stuff like this:

```
[1092] 30 Jul 10:18:48 - Accepted MY_IP
[1092] 30 Jul 10:18:48 - Accepted MY_IP
[1092] 30 Jul 10:18:48 - Accepted MY_IP
[1092] 30 Jul 10:18:48 - Accepted MY_IP
[1092] 30 Jul 10:18:48 - Client closed connection
[1092] 30 Jul 10:18:48 - Client closed connection
[1092] 30 Jul 10:18:48 - Client closed connection
[1092] 30 Jul 10:18:48 - Client closed connection
```

When I restart my redis-server (and then restart the kue script of course), everything works normally again.  If I do restart kue.js but do not restart redis-server, it will keep saying connection refused.

Any help would be appreciated!

thanks

**Comment by s1riedel** [comment]
I am also experiencing this identical issue currently. I am running Node 0.10.36, Redis 3.0.0, and the latest version of the Kue module. I am connecting to the Redis server remotely from another VM. Both VMs are Ubuntu 14.04 LTS.

Any updates on this issue? Thank you.

**Comment by behrad** [comment]
Can you test if you are facing the same issue on Redis 2.8 !?
I haven't tested with Redis 3 yet... You can also check [node_redis](https://github.com/mranney/node_redis) or ask them if they are stable with Redis 3.0

I think more details on this will help to see whats really happening...

**Comment by s1riedel** [comment]
Sure, I will install that this morning and let it run for about 24 - 36 hours and let you know if I have the same connection issues. Thank you.

**Comment by s1riedel** [comment]
I have been testing all day with Redis 2.8, and it is still having some connection issues, but it is different than what I saw in Redis 3. Instead of getting in a bad state where all connections start getting refused, I am getting intermittent but frequent connection timeouts. Sometimes it resolves itself quickly, other times it times out on connections for several minutes. I have verified this is not due to a memory issue on the VM.

Any thoughts or ideas on what this could be? Thank you.

**Comment by behrad** [comment]
If your redis is not local, try to find out if there's any network problems, otherwise verify redis is up and running without hiccups, 

Could you post your node.js redis error logs into node_redis ?

**Comment by s1riedel** [comment]
The connection issues were being caused by our hosting provider apparently, not a Redis issue directly. I was able to get the connections working reliably by using private networks with our hosting provider. Thank you for you feedback on this issue.

Sorry to re-start this thread again.
