### ISSUE TITLE
Please deprecate this package OR add a notice to the ReadMe OR add maintainers

### ISSUE THREAD

**Issue by chilts** [Automattic/kue#1230]
Dear @Automattic,

I ask courteously and with huge respect for both you and Kue, but please do one of the following for this project:

1. deprecate this package in npm (https://docs.npmjs.com/cli/deprecate)
2. add a note to the top of the ReadMe such as "Kue is not part of any of our current projects, and is not being actively maintained." (https://twitter.com/automattic/status/1019073146446602240)
3. add maintainers so that the people using it can fix problems, add updates, and perform releases (though I understand this might not actually be the best course of action)

Another nicety for (1) and (2) would be to point people to other Redis-based queue projects for Nodejs, such as Bull (https://www.npmjs.com/package/bull), which is actively maintained.

Kue is both a widely used package and one that commands a lot of respect having been around for a while. I remember it in it's infancy in 2011 having been around node back then.

Recently, having spent a fair bit of time evaluating both Kue and Bull it wasn't until I starting looking at the repo for more info that I realised that this project was inactive. I appreciate the trail Kue made in nodejs where others have followed, but it is no longer fair to just leave the project as-is.

Seeing issues such as "Is this repo maintained?" (https://github.com/Automattic/kue/issues/185) created in 2013 gives an indication that users have been wondering for a very long time now. Perhaps it's time to bring these questions to a conclusion.

Having written mongodb-queue (https://www.npmjs.com/package/mongodb-queue) and many other node packages, I understand what it is like to write it, use it, then no longer use it and I understand your pain in not wanting to do any of the above, which would effectively seal the fate of the project. I fear delaying the decision any more however is detrimental.

I have no preference and no personal buy-in to this project or others (yet) but I think it is fair of you to do any of the above options and there may be others. I'm just trying to save time for people who , like me, spent time trialling an inactive project.

I'd love to hear from you on behalf of your users and for potential users who are evaluating using Kue. Many thanks for all of your hard work over the years in both creating (indirectly) and maintaining Kue - it's a thankless task, hence my thanks above - but hopefully we can draw some of these questions to a conclusion.

Thanks again,
Your Users and Potential Users

**Comment by chilts** [comment]
Looks like @simison now has a PR which is essentially option 1 : https://github.com/Automattic/kue/pull/1231

**Comment by simison** [comment]
>add maintainers so that the people using it can fix problems, add updates, and perform releases (though I understand this might not actually be the best course of action)

This would be lovely — just requires people from the community to stand up and actively start working on Kue. Triaging open issues and PRs would be a great way to start. :-)

**Comment by behrad** [comment]
I will be backing everyone who is capable of being a new maintainer of Kue

**Comment by gkorland** [comment]
Is it still open for discussion? or is the deprecation final? Are there any active forks?

**Comment by simison** [comment]
@gkorland are you suggesting you'd like to volunteer as active maintainer?  :-)

**Comment by gkorland** [comment]
I can do my best, and I know others who would like to join too

**Comment by gkorland** [comment]
@simison will you accept contributions?
