### ISSUE TITLE
Stop Processing Jobs

### ISSUE THREAD

**Issue by danpalmer** [Automattic/kue#133]
There does not seem to be the ability to stop processing jobs, it would be nice to have this.

**Comment by knutole** [comment]
Still not possible to cancel jobs?

```javascript
kue.Job.get(job_id, function (err, job) {
    job.failed().error(new Error('whatever')); // doesn't work
    job.failed(callback); // doesn't work
});
```

How can I manually cancel a running job? I'm doing image processing, and sometimes I need to cancel heavy duty tasks. Thanks

**Comment by behrad** [comment]
Kue currently doesn't support canceling a running job, the only way to do this is using `done` to mark current job as failed/completed.

**Comment by ineedthekeyboard** [comment]
I've spent several days now trying without success to cancel heavy duty jobs. Is there any update to this thread, is Kue still unable to cancel a running job? 

I have tried several other methods recommended by @Behrad to no avail (such as spoken about in issue #942 #130 and others) 

Even if I do mark the job as done..or listen for a completed message on the job, Kue takes no action until the event look it freed up by the job.

Am looking to see if anyone has any ideas on how to cancel a event-loop blocking job midway through?

**Comment by cptrodgers** [comment]
> I've spent several days now trying without success to cancel heavy duty jobs. Is there any update to this thread, is Kue still unable to cancel a running job?
> 
> I have tried several other methods recommended by @behrad to no avail (such as spoken about in issue #942 #130 and others)
> 
> Even if I do mark the job as done..or listen for a completed message on the job, Kue takes no action until the event look it freed up by the job.
> 
> Am looking to see if anyone has any ideas on how to cancel a event-loop blocking job midway through?

We can use semaphore style for mark job dont use resource and call `next_job`. I don't read your source code. But with many concurrent processing. I think we need semaphore.

In short: User must use semaphore for mark resource done. Store in redis or update to `job` by `job_id`.
