### ISSUE TITLE
Job not starting

### ISSUE THREAD

**Issue by jbrooksuk** [Automattic/kue#186]
I have the following code:

```
var job = jobs.create('verify', {
    emails: ["jbrooksuk@me.com"],
    cacheTime: 604800
}).priority('high').attempts(5);
job.on('complete', function(){
    res.send("Job complete");
}).on('failed', function(){
    res.send("Job failed");
}).on('progress', function(progress){
    console.log('job #' + job.id + ' ' + progress + '% complete');
});
job.save();
```

When I check `/stats` I get:

```
{"inactiveCount":0,"completeCount":0,"activeCount":0,"failedCount":0,"delayedCount":0,"workTime":null}
```

And my job is never processed, even though I'm running a worker via Foreman.

Also, how do I get Kue to display the UI when I have an existing Express app setup? I want something like `localhost:3000/kue/` which is authorised.

**Comment by ctechnologyenterprise** [comment]
Hi @jbrooksuk , I used call back on save and it doesn't occur any issue, But the kue job not starting, the state is inactive when saving job to Redis. Can you help me?

**Comment by jbrooksuk** [comment]
Sorry, I've not used Kue for 8 years now. I would suggest creating a new ticket.

**Comment by jbrooksuk** [comment]
Actually, it appears Kue is no longer maintained. I'd look for another project.
