### ISSUE TITLE
Fail a job

### ISSUE THREAD

**Issue by jbrooksuk** [Automattic/kue#191]
I'm building an application which runs Kue after a file has changed, it triggers a set of jobs and all is good. However I want to be able to purposefully fail a job if something goes wrong.

For example, I request a web page, but if the `http.statusCode !== 200` the job should fail and no other job should be processed.

How do I go about that?

**Comment by knutole** [comment]
This doesn't work.

```javascript
kue.Job.get(job_id, function (err, job) {
	var err = new Error('purposely fail job');
	job.failed().error(err);
});
```

**Comment by behrad** [comment]
The normal way to fail a job is by calling `done` @knutole , So you should keep a reference to it
