### ISSUE TITLE
Support for scheduling for specific date/time, or recurring?

### ISSUE THREAD

**Issue by victorhooi** [Automattic/kue#200]
Hi,

I'm wondering if there's any plans to add support for scheduling jobs at specific dates/times? (e.g. run at 7:00AM on 5th February, 2015).

Or the ability to have recurring jobs (i.e. run every hour, Monday through to Friday).

Cheers,
Victor

**Comment by lykmapipo** [comment]
@ArtworkAD 
@victorhooi 

Though this issue has been closed.
You may check [kue-scheduler](https://github.com/lykmapipo/kue-scheduler)
