### ISSUE TITLE
JSON API Method to update the job's progress 

### ISSUE THREAD

**Issue by jibay** [Automattic/kue#219]
Hello all,

Thank for this awesome tool. I have patched the code in order to modify with JSON API the jobs's progress

Sorry i feel unconfortable with git so I copy/paste my code here.

In ./lib/http/routes/json.js

```
/**
 * Update job :id :frames :totalFrames.
 */

exports.updateProgress = function(req, res){
  var id = req.params.id
    , frames = req.params.frames , totalFrames = req.params.totalFrames;

  Job.get(id, function(err, job){
    if (err) return res.send({ error: err.message });
    job.progress(frames, totalFrames);
    job.save(function(err){
      if (err) return res.send({ error: err.message });
      res.send({ message: 'updated Progress' });
    });
  });


};
```

And in ./lib/http/index.js

```
app.put('/job/:id/progress/:frames..:totalFrames', provides('json'), json.updateProgress);
```

Here an example:

 curl -X PUT "http://domain:port/job/163/progress/1200..3000"

Sorry for my english.

**Comment by PaulMaly** [comment]
@behrad I don't agree with you. It's very useful feature. 

Right now JSON API is completely unuseful and it's sad. Kue as a stand-alone (micro-)service is much more preferable than just a nodejs module. And it's simple to move Kue this way - just make JSON API more powerful.
