### ISSUE TITLE
Put job back on the queue

### ISSUE THREAD

**Issue by richardbaronpenman** [Automattic/kue#221]
When processing the queue how can a job be put back on the queue?

One possibility would be increasing the attempts and return an error:

``` javascript
job._max_attempts = parseInt(job._max_attempts) + 1;
job.save(function() {
    done("handle later");
});

Or perhaps just remove the job and create again:
job.remove(function() {
    jobs.create(...).save(function() {
        done();
    });
})
```

Is there a proper way?

**Comment by schnie** [comment]
Hey @richardpenman, having a very similar issue.  I know its been a while, but can you let me know how you ended up handling this?  Thanks!

**Comment by richardpenman** [comment]
I needed to modify Kue so that a call to done("requeue") would add it back to the queue after a delay. Not ideal.

**Comment by bradvogel** [comment]
See https://github.com/Automattic/kue/pull/553 for another attempt at this. cc/ @andrewtamura
