### ISSUE TITLE
kue is crashing the server on Redis client error

### ISSUE THREAD

**Issue by bsphere** [Automattic/kue#240]
When the Redis server causes an error (for example, disconnection or server is down), Kue is crashing the server (even that I'm handling the on('error') event of the Redis client).

The normal Redis client behavior is to retry to reconnect and not crash anything if on('error') is handled.

this is my code:

``` javascript
kue.redis.createClient = function() {
    client = redis.createClient(cfg.redisPort, cfg.redisHost);
    if (cfg.redisAuth) {
        client.auth(cfg.redisAuth);
    }

    client.on('error', console.log);

    return client;
};
```

**Comment by Rukeith** [comment]
@kintel Which version had fixed this problem ?
I use 0.7.9, but I still have this problem

**Comment by kintel** [comment]
@Rukeith I cannot remember - prob. the latest version at the time of my comment. Stopped using Kue due to new requirements on our end..
