### ISSUE TITLE
My worker received a job. Turns out after some analysis I want to put it back in the queue. Best way to do so?

### ISSUE THREAD

**Issue by Analogreality** [Automattic/kue#249]
Suppose I get a job from jobs.process(). A new job comes in and my worker takes a look at it and decides that THAT SPECIFIC worker shouldn't work on it for whatever reason.

What is the best way to put it back in the queue. I don't want to create ANOTHER job, just 'un'mark that this worker received it. Basically undo whatever is set so that other workers don't get that job.

**Comment by andrewtamura** [comment]
When I call `job.inactive()` does this job go to the back of the queue or is it inserted into the top? After I call `job.inactive()` how do I get that job to pick up a new job from the queue?

**Comment by behrad** [comment]
> When I call job.inactive() does this job go to the back of the queue or is it inserted into the top?

Queues in Kue are prioritized (by redis sorted sets) so the job will be inserted in the correct order based on it's score and arrival (queues are FIFO by default)



> After I call job.inactive() how do I get that job to pick up a new job from the queue?

not sure to understand your question :)
