### ISSUE TITLE
Sorting for WebUI

### ISSUE THREAD

**Issue by aonic** [Automattic/kue#27]
It would be very helpful if the queued/complete pages had the ability to sort desc by ID to see the latest completed jobs instead of the oldest jobs first.

The current lack of sorting ability is a pain for large fast-moving queues.

**Comment by emin93** [comment]
It would be helpful if sort would sort all jobs and not just the visible. In my case i have over 1000 jobs and it's very annoying to scroll through them to get to the latest.
