### ISSUE TITLE
Feature request: periodic task support

### ISSUE THREAD

**Issue by thom-nic** [Automattic/kue#298]
So I have a use case which I don't believe 'fits' with kue currently, and I'm looking for guidance as to whether it would be worth contributing an enhancement to Kue or rolling my own.  Here's what I'm looking for:

A cron-like job scheduling system that is backed by redis and uses many worker nodes as an HA mechanism.  So the way it works is:

Cron jobs are defined by a job ID, interval, last run, run count, and sorted by "next deadline."  When a job is ready to be run, any or all workers can attempt to acquire the job by performing a "compare and set" increment of the run counter for that job.  The worker whose CAS succeeds is deemed the "winner" and acquires the job for this turn.  Losers simply update their counter for that job and wait for the next deadline and try again.  This would provide a level of HA to ensure that the job will always be acquired by one worker even in the face of failures from worker nodes.

In contrast, I've found [this](http://gelnior.wordpress.com/2012/10/26/nodejs-cron-job-with-kue/) however I don't like the idea that if for some reason repeatJob isn't called (say an uncaught exception or process crash) your job will be lost because it's never rescheduled.  

Does this resonate with Kue, seem like something that would fit well or completely out of scope/ doesn't fit well into the current design?  Thanks.

**Comment by lykmapipo** [comment]
@thom-nic 

Though this issue has been closed.
You may check [kue-scheduler](https://github.com/lykmapipo/kue-scheduler)
