### ISSUE TITLE
broken backoff feature

### ISSUE THREAD

**Issue by Jedius** [Automattic/kue#360]
After some commit, merge or something, this was gone from lib/queue/job.js:

```
if (this._backoff) {
    if (_.isPlainObject(this._backoff)) this.set('backoff', JSON.stringify(this._backoff));
    else this.set('backoff', this._backoff.toString());
}
```

```
if (hash.backoff) {
    var source = 'job._backoff = ' + hash.backoff + ";";
    eval(source);
}
```

so backoff not works.
looks like it happened here - https://github.com/LearnBoost/kue/commit/9ce22c2795b52dcaa903fc596bf52d1492960063
0.7.9 version looks fine.
or am I missing something?

**Comment by daminufe** [comment]
Question: Why are you using an `eval()` of the backoff callback function? I am trying to set dynamic delays, and I can't because you are evaling it.

Is there any reason?

**Comment by behrad** [comment]
backoff calculation function should be serialized on redis so that they can be unmarshalled and get evaluated on any worker node needed.
