### ISSUE TITLE
Let Job level events to be turned off for memory usage optimization

### ISSUE THREAD

**Issue by mlordon** [Automattic/kue#401]
I'm running a kue worker processing jobs of type A.
Each A job creates around 500 000 jobs of type B.

The memory this worker uses keep increasing as it creates B jobs.
It seems that all B jobs are mapped in events.js, thus using more and more memory as more B jobs are created.

Is there a way to avoid this?

I don't really understand why events.js maps jobs created in the process.
Is it used to handle job events?
Is there a way to avoid this memory consuming mapping? Maybe it could be an option, loosing the job event feature when activated.

**Comment by behrad** [comment]
`kue.createQueue( {jobEvents: false} )` should work in master branch

**Comment by mlordon** [comment]
Thanks very much!
