### ISSUE TITLE
Detect if job is removed

### ISSUE THREAD

**Issue by tim-smart** [Automattic/kue#486]
I was wondering if there is a job event to detect when a job has been removed. My use case:

Sometimes I want to manually stop a job from the web ui, so I click the 'x' which drills down to a `job.remove` call. The issue is I now need to stop the worker tasks that are still running even after removing the job.

**Comment by hems** [comment]
Maybe clicking the "x" could emit and event "deleted" ?

**Comment by behrad** [comment]
currently kue supports no job dependencies or ... so it is the application responsibility to build needed events and dependencies over Kue :)

**Comment by hems** [comment]
@behrad what i meant is, if i click the "x" on kue UI is there a way to be notified on my code that the job was canceled, so i can keep my app up to date in case an "admin" decides to kill a job from within kue UI ?
