### ISSUE TITLE
What does 'priority' do?

### ISSUE THREAD

**Issue by bradvogel** [Automattic/kue#501]
There's very little documentation on priority. What does it do? If I enqueue a task with 'high' priority into the queue of 'normal' priority tasks, does that job get picked up first?

**Comment by behrad** [comment]
priority is exactly mapped to the redis' ZADD score, so your job moves up to the head of the set and will be picked up more likely :)

**Comment by bradvogel** [comment]
Oh ok, can you define more "likely" though? If I have 99 'normal' jobs in the queue and I push one 'high' job, will the 'high' priority job be started immediately?

**Comment by behrad** [comment]
Yes, however there's always a chance that each of your worker BLPOPs pick a job for themselves before ZADD is finished, so a few jobs win the race, and then the high prio job comes in.
If you wanna make sure it is always first, you can call `.process` after creating your jobs... but this is not a good assumption.

**Comment by behrad** [comment]
and write a 5min snippet to really feel it ;)
