### ISSUE TITLE
Enable / disable job processors

### ISSUE THREAD

**Issue by luislobo** [Automattic/kue#504]
Hi,
I have created a jobs manager that can process different "queues". I don't know if I'm doing it right, but I have different kind of jobs, and I enable the processing of them via a flag, so I only define a process("queueName", 10, fnThatProcessesThatQueue())

If the job is disabled, then process is not called with the corresponding queueName.

I still get jobs from other queues, even if I don't define a process() for that queue. Am I doing anything wrong?

How would you enable/disable different jobs, all sharing the same codebase, but only with configs?

Related to this issue, is it possible to have several servers? Is it safe? Does Kue takes/locks a job, and no other process/server can take the same one?

**Comment by behrad** [comment]
> I still get jobs from other queues, even if I don't define a process() for that queue. Am I doing anything wrong?

you will only get jobs from the queue that you called `process( )` for that queue name.



> How would you enable/disable different jobs, all sharing the same codebase, but only with configs?

Please check *pause/resume* section in the README documentation


> Related to this issue, is it possible to have several servers? Is it safe? Does Kue takes/locks a job, and no other process/server can take the same one?

totally safe and more scalable. Kue is depending on Redis's BLPOP implementation for atomic job picking. so thanks Redis :)
