### ISSUE TITLE
RPOPLPUSH?

### ISSUE THREAD

**Issue by grimborg** [Automattic/kue#519]
Is there any reason why kue uses BLPOP instead of RPOPLPUSH?

**Comment by behrad** [comment]
Priority support!
Kue uses ZSETs to support job priorities, however RPOPLPUSH, atomically moves objects between lists. Please check the implementation to check how kue is using a utility list and BLPOP on that... however this could be refactored to RPOPLPUSH, please follow this old issue  https://github.com/LearnBoost/kue/issues/38 or contribute on that.
