### ISSUE TITLE
Multi-server Kue for High Availability

### ISSUE THREAD

**Issue by awinder** [Automattic/kue#522]
I saw the notes in the documentation about using the node cluster module to leverage more than one CPU, which is awesome.  I'm wondering about the ability to stick Kue behind a load balancer for high availability and horizontal scaling, though.  That way if one machine went down or our system exceeded the throughput that one kue server could handle, we could handle that through more server instances.  Any gotchas to be aware of or anyone with experience setting Kue up like that?

Thanks!

**Comment by sequoiar** [comment]
@awinder 

AFAIK, Kue job queue is based on Redis DB, which means Kue can scale horizontally by scale RedisDB.

**Comment by behrad** [comment]
@awinder you can easily start node.js processes in different machines (scale out) as well as using cluster (scale up). Depending on your pressure you can use a single redis instance or even more (via sential for example) as @sequoiar said.

**Comment by awinder** [comment]
Sorry for coming in late on the reply, thanks for that answer.  I'm reading about a lot of issues with calling promote on more than one machine, how would that stand up in a cluster?  Also wondering, if I'm calling promote from one machine, is only that machine going to be processing those promoted jobs, or will any machine in the cluster be able to run the promoted jobs?

**Comment by behrad** [comment]
you need to call `promote` from only one machine. Job Promotion process is simply a flagging process which moves jobs from `delayed` to `inactive` and that doesn't need to be clustered :)
However this will be changed to a server side redis script in upcoming Kue versions
