### ISSUE TITLE
kue (reds?) creates always a Redis connection to localhost when requiring

### ISSUE THREAD

**Issue by esamattis** [Automattic/kue#54]
Don't know if this is kue or reds issue, but it certainly affects kue. Tested on kue master.

Consider following:

```
var redis = require("redis");                                                                                                                
var client = redis.createClient(1234, "example.com");                           

setTimeout(function() {                                                         
    require("kue");                                                   
}, 1000);                                                                       

client.on("connect", function() {                                               
  console.log("Connected!");                                                    
});                                                                             
```

It dies immediately after kue is required in the timeout:

```
Connected!

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Redis connection to 127.0.0.1:6379 failed - ECONNREFUSED, Connection refused
    at Socket.<anonymous> (/home/epeli/tmp/kue/node_modules/reds/node_modules/redis/index.js:123:28)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:830:27)
    at EventEmitter._tickCallback (node.js:126:26)

shell returned 1
```

Creates a second connection to localhost?

I think the reason is here:

A search is created on require
https://github.com/LearnBoost/kue/blob/b2cd5d3393d12e4bdd1c2e654a3ef5eb45e5bf11/lib/queue/job.js#L27

which means new Search on Reds
https://github.com/visionmedia/reds/blob/156c046803df6b96fa40e90be26b933f7d324d01/lib/reds.js#L68

which then again means a new Redis client which connects to localhost
https://github.com/visionmedia/reds/blob/156c046803df6b96fa40e90be26b933f7d324d01/lib/reds.js#L236

This happens also if you override the createClient function in kue.

**Comment by petermekhaeil** [comment]
What was the solution? I am getting this problem after a successful connect to a non-localhost url.

**Comment by eaglevision20** [comment]
I've been beating my head against this wall for a full day now. I'm running kue version 0.11 and node 4.5 but still cannot connect to a remote host. here is what my connection looks like:

`
const config = require('./config');
var Kue = require('kue');
var queue = Kue.createQueue({
    redis: {
      port: 6379,  //process.env.REDIS_PORT,
      host: 'DOMAIN_HERE.com' //process.env.REDIS_HOST,
      //auth: process.env.REDIS_PASS
    },
    jobEvents: false,
    disableSearch: true,
  });
`
No matter what I try I get the same error back: 
`
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
`
I have tried every example I can find and still nothing.. :( 

Any help is greatly appreciated.

**Comment by 59023g** [comment]
@eaglevision20 closest thing I could find: https://github.com/Automattic/kue/issues/875 

If I have time I'll fork and look..

Maybe check the Pull Requests

**Comment by ganeshcse2991** [comment]
Still facing the same issue. Tried all the examples and pull requests too. Please help. Its still creating queue with local redis.

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:907:11)
at exports._exceptionWithHostPort (util.js:930:20)
at TCPConnectWrap.afterConnect as oncomplete

**Comment by fabulator** [comment]
@ganeshcse2991 as was said in comment earlier https://github.com/Automattic/kue/issues/54#issuecomment-57683955 Problem is requiring app from kue before creating a queue. Something like this: ```import kue, { app } from 'kue';``` At least it was my issue and it is working fine for me now.

**Comment by shierro** [comment]
@behrad thanks for the input about `creating the queue` before calling `kue.app` you are awesome!
```
queueService.initQueue(REDIS_HOST, REDIS_PORT);
app.use('/kue-api/', basicAuth, require('kue').app);
```

**Comment by sinisavukovic** [comment]
@behrad @shierro. Thanks!

For those who are still looking for a quick answer:
```
import kue from "kue";
import express from "express";

kue.createQueue({
  prefix: 'q',
  redis: {
    port: <REDIS_PORT>,
    host: "<REDIS_HOST>"
  }
});

const app = express();
app.use("/kue-api/", kue.app);
```
