### ISSUE TITLE
TTL / Job

### ISSUE THREAD

**Issue by behrad** [Automattic/kue#544]
There should be a server side (redis scripts?) TTL mechanism which prevents stuck/stale `active` jobs.

client node.js worker processors should be aware of job's TTL being exceeded if they are live

**Comment by behrad** [comment]
http://stackoverflow.com/questions/11810020/how-to-handle-session-expire-basing-redis/11815594#11815594

https://groups.google.com/forum/#!topic/redis-db/rXXMCLNkNSs

**Comment by mautematico** [comment]
So, is this getting removed? :(

**Comment by behrad** [comment]
Semantically yes, this is split into two features
1) stalled jobs: the timeout when a worker is crashed/restarted and it's job stays active
2) active job expiry: the timeout when a worker is alive, but the user's app is not calling `done` in time
