### ISSUE TITLE
automatic fail after x seconds?

### ISSUE THREAD

**Issue by gebrits** [Automattic/kue#555]
Is it possible to have a job fail automatically after x seconds passed since job was pulled from queue using `queue.process`? This would allow to mark a job as failed when a worker processing the job crashed without having had time to call `done(err)`. 

This could be useful as an extra safety net, when it's certain certain jobs are done within a given period of time

**Comment by behrad** [comment]
duplicate of https://github.com/Automattic/kue/issues/544
