### ISSUE TITLE
use a distributed redis lock to hide job promotion from user

### ISSUE THREAD

**Issue by behrad** [Automattic/kue#556]
call promotion logic inside kue, user can configure promotion parameters if desired.

**Comment by andrewtamura** [comment]
will this and #522 mean that `promote()` will work out of the box in multi server deployments of Kue? What about `watchStuckJobs()`?

**Comment by behrad** [comment]
Exactly @andrewtamura 
`.promote` method will be emptied and deprecated in future, job promotion should work out of the box in Kue without user involvement :)
