### ISSUE TITLE
Testing queueing and/or execution of jobs

### ISSUE THREAD

**Issue by patbenatar** [Automattic/kue#560]
I'm not able to find much documentation around the topic of how to test that jobs are added to queues with correct data. It looks like the HTTP API may be useful for getting at this data, but that seems like a roundabout way to get at some testing support. Sidekiq has some nice support for testing: https://github.com/mperham/sidekiq/wiki/Testing#setup ... are there plans on the kue roadmap for adding this sort of functionality? Would you be open to a PR on this topic? Thanks!

**Comment by behrad** [comment]
Thank you @patbenatar for the suggestion :+1: 

> are there plans on the kue roadmap for adding this sort of functionality?

not yet



> Would you be open to a PR on this topic?

sure yea!

**Comment by epicbagel** [comment]
Is there a way to process the jobs within test mode? From what I can see in the code, the jobs in the queue aren't processed at all.

**Comment by patbenatar** [comment]
@epicbagel It doesn't currently run the jobs.. We could build a feature similar to Sidekiq's `Worker.drain` (perhaps `kue.drain(jobName)` to manually process any jobs waiting in the queue?

**Comment by behrad** [comment]
a neat PR totally welcomed :+1:
