### ISSUE TITLE
Remove scrolling from job log.

### ISSUE THREAD

**Issue by okor** [Automattic/kue#562]
I have a job type which sometimes creates a lot of ```job.log```'s which are essentially updates. When I expand an individual job in the UI to view progress, if the job has a bunch of logs a new level of scrolling is revealed (some kind of js based scrolling). This is like trying to read a book through a pinhole and doesn't really allow me to get a good view of what is going on. It just feels like an unnecessary thing, since by clicking on the job I have stated my intention to view job's details.

I would like to suggest removing this job log scrolling feature. If there is interest, I can whip up a PR. If not, I don't really want to maintain a fork, so I'd probably just learn to live with it.

Thanks!

**Comment by behrad** [comment]
what if scroll is removed? How long logs would be visible and read?

**Comment by behrad** [comment]
> They would just automatically expand to their full height

I don't think this is a good default

**Comment by okor** [comment]
Do you have a reason for that opinion? 

I think simplicity default is pretty OK. If someone is logging a bunch of stuff to the job, I think it's entirely reasonable to show the full log when they expand the UI item for that job. I think my reasoning for finding the second layer of scrolling annoying, is pretty sound. It's just like any other UI which makes getting information more difficult through some new trend (like parallax scrolling for example) or fancy javascript thing.

To be clear, my intention is to only show the full log after you click to expand the jobs details. Nothing would change about the UI when the details are collapsed.

Could just be me, I just prefer less work rather than more work when possible : )

**Comment by behrad** [comment]
> To be clear, my intention is to only show the full log after you click to expand the jobs details. Nothing would change about the UI when the details are collapsed

I myself think full log are third level of details, one after the job details, not at the same level :)

**Comment by okor** [comment]
Welp, ok : )

I won't fight with you about it. If the sentiment changes then let me know.
