### ISSUE TITLE
Add option to hide progress indicator

### ISSUE THREAD

**Issue by okor** [Automattic/kue#563]
I have some jobs that run for infinity (they schedule other jobs), which are difficult to quantify progress since they are never done. And if one complete iteration would be considered 100% of the job, I would have something in the active queue which said it was 100% but it's just hanging around forever. Alternatively, not updating the progress at all (what I'm doing now) leaves me feeling like the "0%" is telling me the job is stuck or not doing anything. Both of which are false.

I propose adding the ability to pass an option to ```job.create``` or ```job.save```, so that I can tell the UI to not show the progress indicator. Like ```job.save({ showProgress: false })```, which could default to true. Something like that.

If kue had built in support for recurring/scheduled job types, then this might not be an issue since the inactive job could just be taken out of the queue or stuck into a new queue state (add "scheduled" or "recurring" tab to UI, similar to "active" "complete" etc.).

**Comment by behrad** [comment]
I am not into adding presentation specific options to Queue and job management code, that doesn't feel good to me. However we can add more controls to the UI for a better and more friendly UX :+1: 



> If kue had built in support for recurring/scheduled job types, then this might not be an issue since the inactive job could just be taken out of the queue or stuck into a new queue state (add "scheduled" or "recurring" tab to UI, similar to "active" "complete" etc.).

tab based or separated list view of different workers is one of my favs for UI enhancement... I am open to any PRs :)

**Comment by okor** [comment]
Ok. I don't feel like I confidently say that I would be able to create a PR for recurring job support at this point. But I could add a tab for another job state. I guess the second best option to full scheduling/recurring job support would be a new job state. I think it might be something like "sleeping"?

Just like you can change a jobs state to any of the available options, this doesn't actually do anything to the job which would prevent processing from occurring (right?). Then we could leave it up to the job/application code to set the state of the job to "sleeping"/"active".

....ok, the more I think about this maybe the most appropriate option would be to just push the job into the "inactive" queue. That's somewhat misleading as it's actually doing work, it's just waiting on a timer to fire. hmmm, thoughts?

**Comment by behrad** [comment]
`inactive` is not sleeping, job will be activated as soon as no jobs are in front of it; and adding another state is the last thing I will do ;) since this is not intended for logic, but also UX enhancement

**Comment by okor** [comment]
Oh, right. Ok, so that wouldn't be a good solve. I think the scope of what this discussion is becoming is really about supporting recurring jobs. Like I said, I don't think I can confidently introduce support for this. I'll go ahead and close for now.

Thanks!
