### ISSUE TITLE
Add red bg color to "X" button on jobs

### ISSUE THREAD

**Issue by okor** [Automattic/kue#564]
This button is "destructive" as it actually removes the job. I just think it should give the user a little more feedback as to it's nature. A confirm dialog would probably be extreme (I really dislike native dialog apis), but a little bit of red and perhaps a boring old ``title="Destroy Job"`` would provide a little more context.

If interested, I can create a PR.

Thanks!

**Comment by behrad** [comment]
A PR that does

1) a confirmation from the user (in any method) is great

2) more attention (warn style) to the delete button which is pretty

**Comment by behrad** [comment]
at development or debugging you will find it handy to delete multiple jobs in UI by that delete icon... confirmation would be annoying in that case or we should add a job selection box and push a delete all

**Comment by okor** [comment]
Yeah, I totally agree. I will just create a PR for the bg color on hover and a title tag so we can get simple browser tooltips which indicate the action is destructive. This would not interfere with folks who are in development/debugging envs, just adds a bit of visual feedback while still staying out of the way of productivity. I'll work on a PR.

**Comment by okor** [comment]
So, I've noticed that the master branch seems to be throwing an error on a jade requirement error. Would you like this PR be for the 0.8 branch or master?

**Comment by okor** [comment]
I went ahead an stuck this in the 0.8 branch since that appears to be the latest, stable branch and this is a very low risk PR.

https://github.com/Automattic/kue/pull/565

If you prefer 0.9, then there is a commit for that too (but that branch seems to have a module loading error at the moment): https://github.com/okor/kue/commit/a596af1989e2a6a6df77cc78916a4722e3a29a22

**Comment by behrad** [comment]
I prefer it for the 0.9 (master) @okor 
Thank you

**Comment by okor** [comment]
Sounds good, here is the 0.9 PR: https://github.com/Automattic/kue/pull/566
