### ISSUE TITLE
Worker errors are improperly wrapped

### ISSUE THREAD

**Issue by defunctzombie** [Automattic/kue#567]
https://github.com/Automattic/kue/blob/master/lib/queue/worker.js#L87-L93

I am not sure for the reasoning behind these lines but they break the typical pattern of `emit(error)` being an instance of `Error`. This makes `instanceof Error` checks fail as well as losing any additional properties the original error may have had.

Seems to be that all this line needs is to re-emit the error passed to it.

**Comment by behrad** [comment]
thank you @defunctzombie but what `emit` is doing, is publishing JSON.stringified of that objects on redis, and `Error` object is not JSON.stringifiable :( so I had to wrap the error in a new Object

Any better solution or recommendation is totally welcome

**Comment by behrad** [comment]
Oh Oh! seems I'm missing `event.emit` via `EventEmitter.emit`.. 
lemme check the roots... if that is related to the second you're totally right and we shouldn't wrap Error object, then I'll re-open and merge your PR ;)

**Comment by defunctzombie** [comment]
@behrad I made these changes in my fork and tested them. They produce the correct results I expect when handling `queue.on('error')` in my app. I don't know what redis has to do with the error object here.

**Comment by behrad** [comment]
right @defunctzombie I missed up with another root in the code base where we should wrap the error object to publish it to redis... however emitting on worker's EventEmitter is something different :+1:
