### ISSUE TITLE
Publish v0.9.0 to npm

### ISSUE THREAD

**Issue by jesucarr** [Automattic/kue#572]
Any reason why version 0.9.0 is not published in npm?

**Comment by behrad** [comment]
Not released yet... I'm in the middle of issues however `History.md` and package version are updated in master

**Comment by jesucarr** [comment]
may be a good idea to keep in master the official releases, "gitflow" style. I couldn't figure out why delayed jobs weren't working and of course I needed to call promote(), which is deprecated in the new documentation...

**Comment by behrad** [comment]
+1 for gitflow-ish style, I think should stick to it from now on since it feels standardish to all npm users.
job promotion is re-implemented in 0.9 and so in the current master you are looking at 0.9 docs, however `npm install` gives you [this](https://github.com/Automattic/kue/tree/0.8)

**Comment by bradvogel** [comment]
Hi @behrad , What's the status of 0.9? We're all really eager to start using it from NPM!

**Comment by behrad** [comment]
I'll try to push in a day :)

**Comment by behrad** [comment]
0.9.0 pushed to npm
