### ISSUE TITLE
please tell users that they need a log file/dir instead of silently exiting.

### ISSUE THREAD

**Issue by boxxxie** [Automattic/kue#573]
pleeeeeeeeeeeeeeeeeeeeeeease.

i had to do 
```javascript
process.once( 'uncaughtException', function(err){
  console.log("process error",err);
  queue.shutdown( 1000, "", function(err2){
    console.log("queue.shutdown", err2);
    process.exit( 0 );
  });
});
```
to figure out that i needed a `./var` dir after hours of not knowing why my process was exiting.

**Comment by behrad** [comment]
you should know that `uncaughtException` is not a safe gaurd in your code, since a potential for a swallowed error is always on with it.

I will try to explain this in the related section :) renaming the issue if you don't mind
