### ISSUE TITLE
Recover jobs from node restart

### ISSUE THREAD

**Issue by btmdave** [Automattic/kue#575]
It seems that when restarting a 'worker' that is using kue, any active jobs go away and are no longer in kue.   Is there anyway to save or re-pickup these jobs?

**Comment by behrad** [comment]
first read 
https://github.com/Automattic/kue#prevent-from-stuck-active-jobs

and then
https://github.com/Automattic/kue#programmatic-job-management

**Comment by btmdave** [comment]
Thanks behrad, those are helpful.

Any ideas why sometimes a job will be marked complete and show up as complete, but it's still showing in active?

**Comment by behrad** [comment]
are you sure your ui is updated and this is not related to the ui not being synced?
I haven't seen such a deep state anomaly.

**Comment by btmdave** [comment]
I'm refreshing it..  If a job is `done()` and data is updated to that job after `done()` is called, would that re-active it?  I'm not sure that's the case yet hough, doesn't seem to be.

**Comment by behrad** [comment]
No, it should not, however it can be a race between `done` and `update`, can you reproduce that with a code snippet?

**Comment by btmdave** [comment]
That was exactly it.   I had `job.update()` being called just before the `done()`.    When I removed that, or checked it's condition before updating, it works!

**Comment by behrad** [comment]
happy for you, you'd better call done inside your update callback function :)
