### ISSUE TITLE
Remove old jobs?

### ISSUE THREAD

**Issue by ybogdanov** [Automattic/kue#58]
How to do some "garbage collection" by removing old completed jobs, for example, those which are older than 1 hour?
Thanks!

**Comment by warrickhill** [comment]
Try this, worked for me
```javascript
jobs.on('job complete', function(id) {
	kue.Job.get(id, function(err, job) {
		setTimeout(function() {
			job.remove();
		}, 60000);
	});
});
```

**Comment by rkotcherr** [comment]
> For those interested, you could also use
> `job.create( ... ).removeOnComplete( true ).save()`
> that will remove each job on completion.

For smaller systems I'd say this is ideal, but if you have a system where you're creating jobs in many different places I'd say it's probably best to listen to the "on complete" event.

As for using setTimeout() to remove the jobs after a certain time interval, the downside is that if your restart the application you'll lose those callbacks and the jobs will never be removed.

Just some thoughts...

**Comment by lfernandes** [comment]
> sorry everyone I am a new guy of kue and have a question to ask about why don't just use a function to complete like
> 
> ```
> var CLEANUP_TIME = 0.5 * 60 * 1000;
> var CLEANUP_INTERVAL = 0.1 * 60 * 1000;
> function performCleanup() {
>   var now = new Date().getTime();
>   Job.rangeByType('someType', 'complete', 0, -1, 'asc', function (err, selectedJobs) {
>     selectedJobs.forEach(function (job) {
>       var created = job.created_at;
>       if (now - created > CLEANUP_TIME) {
>         job.remove();
>       }
>     });
>   });
> }
> setInterval(performCleanup, CLEANUP_INTERVAL);
> ```
> 
> Is this a bad way for this problem??

Other status can be:
- active
- inactive
- failed
- complete
