### ISSUE TITLE
Update job hash with the worker ID

### ISSUE THREAD

**Issue by btmdave** [Automattic/kue#580]
Is it possible via config or perhaps already available natively, to get a unique name for each worker being run.  Right now, I'm updating jobs w/ the hostname their run on, which is fine.. but seems like maybe this is functionality that might be built in?

**Comment by behrad** [comment]
1) depends on the definition/use of worker id: Kue instantiates a Worker instance for each worker per concurrency, so `process( 'myJob', 10, func )` creates 10 workers.

2) here is where worker ids are set: https://github.com/Automattic/kue/blob/master/lib/kue.js#L259 which can be enriched by local machine name before the process id 

3) how that id will be exposed to the client? should a `getId` be added to the `ctx` object exposing to process callback?

**Comment by btmdave** [comment]
Ah ok I mean let's say we have 10 servers that are processing kue jobs, it would be useful to know which server is handling the job

**Comment by behrad** [comment]
Kue can automatically update job hash with the worker.id which is handling it, also items 2 and 3 is nice to have :+1:

**Comment by btmdave** [comment]
Nice, so there would be a way to set this id to a name, such as `worker-server-001` or would it make sense to have a generic `server` object that `ctx` could set properties on?

**Comment by behrad** [comment]
No, you can't set it but read it from the job properties, if you need an extra information, your app should manually add that in `job.data`

**Comment by btmdave** [comment]
Ah ok, so that's what we do now.   It might be useful say for when you call `createQueue()`, if you could specify a server name or identifier that would then be available in the job objects which that queue processes?

**Comment by btmdave** [comment]
Just to elaborate, here's the scenario.

You have a video encoding server farm, say 50 servers.   At this scale, a lot of the management is done via a custom UI, integrated into existing systems.  In that UI, it's useful to group by server, so you can see "How many jobs are being processed on server 0015" etc.  and not like a random ID or even unique ID, but a name that you can view in your UI and understand what's what.

So the solution is in all of your `process()` methods to update with a custom `job.data`, that's fine.  But, if there was a way to specify a server or user-friendly name, associated to a `createQueue()`, would be nice :)

**Comment by behrad** [comment]
```js
job.on( 'complete', function(){
  Job.get( job.id, function(err,updatedJob){
    console.log( updatedJob.getJSON().workerId );
  });
});
```
