### ISSUE TITLE
Q: does kue support distributed mode?

### ISSUE THREAD

**Issue by paul42** [Automattic/kue#581]
I'd like to set up a kue server and was wondering, if I stand up an identical server, different vm/ip but same code base/redis connection, can they co-exist peacefully with the same redis queue and not step on each other's toes when popping jobs off? 

Still learning about the library but it seems super cool.

Thanks in advance,
Paul

**Comment by behrad** [comment]
Kue is actually a distributed job queue, where multiple workers can be easily started on different machines for scale out
