### ISSUE TITLE
Failed jobs are not being removed with removeOnComplete(true)

### ISSUE THREAD

**Issue by felipejfc** [Automattic/kue#582]
Hi, I'm creating a new job the following way:

function createDictionaryJob(inputTerm, country, device, language){
  queue.create('build-dictionary',{
    inputTerm: inputTerm,
    country: country,
    device: device,
    language: language
  }).priority('high').attempts(config.jobs_max_retry_count).removeOnComplete(true)
  .backoff(backoffFunction).save();
}

max retry is 20

When the job fails 20 times it is not removed, it is kept in memory, is this the expected behavior?
 Im using kue 0.8.12

**Comment by behrad** [comment]
`removeOnComplete` only removes completed not failed jobs :) this is the defined behavoir
