### ISSUE TITLE
Set `ttl` & `attempts` & `backof` than when retry occur error

### ISSUE THREAD

**Issue by sinoon** [Automattic/kue#585]
My config of queue when create:
```
attempts(5).backoff({ delay: 30*1000 , type:'fixed' }).removeOnComplete(true).ttl(20000).save();
```

But when some one task ttl expired and doing attempt occur
```
/root/kue-polling/node_modules/redis/index.js:602
                throw err;
                      ^
TypeError: Cannot read property 'length' of undefined
    at Worker.<anonymous> (/root/kue-polling/node_modules/kue/lib/queue/worker.js:189:12)
    at Job.<anonymous> (/root/kue-polling/node_modules/kue/lib/queue/job.js:622:12)
    at /root/kue-polling/node_modules/redis/index.js:1170:13
    at try_callback (/root/kue-polling/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/root/kue-polling/node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (/root/kue-polling/node_modules/redis/index.js:321:14)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_reply (/root/kue-polling/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/root/kue-polling/node_modules/redis/lib/parser/javascript.js:211:22)
    at RedisClient.on_data (/root/kue-polling/node_modules/redis/index.js:547:27)
```

Than , remove ttl config without change other config , it works.

Could someone tell me why ?

**Comment by behrad** [comment]
ttl feature is new, I should write more tests and check your issue, thank you for reporting :)

**Comment by sinoon** [comment]
Hey buddy , what time in you location , don't be too tired.

Actually , I'm very glad to be `rat`~

`ttl` is very useful new feature .

My environment:
```
node : 0.12.2
centOS: 6.5
redis: 0.12.1
kue: 0.9.0
```

Hope it can help you ~ 

Good night~!

**Comment by sinoon** [comment]
Oh! I see , is caused by me  , is my fault . 

Because the task is on process while the  `ttl` expired , so , `fn` is undefined , I set the `ttl` too short.

Sorry for that~

**Comment by sinoon** [comment]
I'm thinking is that will be nice for others if add some words to `README` about notice that the `ttl` can not be shorter than a job's real life ?

**Comment by behrad** [comment]
> Because a job is on process while the ttl expired , so , fn is undefined , I set the ttl too short.

I'm not sure if I am getting you right!



> I'm thinking is that will be nice for others if add some words to README about notice that the ttl can not be shorter than a job's real life ?

there's no  job's real life, and you can't be sure what is your job lifetime, ttl can be set to any value (smaller or bigger than the job existence) it is Kue's side not to face errors in different scenarios.

**Comment by sinoon** [comment]
I'm so sorry about my English ... :(

In some case , a job is send a request to some website and get information , and I set a `timeout` to restrict per request.Once timeout , job fail . 

So , a job lifetime control by timeout , if i set `timeout` logger than `ttl` , it will be fine.

But sometimes , that error still occur when attempt , I have no idea about this for now , I need more time to check out.

**Comment by behrad** [comment]
I checked the code, it appears the callback passed to `.process` is undefined. SO strange, it should be happening from a bad client code. Show me some of your code related to this.

**Comment by behrad** [comment]
solved, please pull master

**Comment by sinoon** [comment]
It's my fault that I checked code on client slide code.

Thank you very much!
