### ISSUE TITLE
Sort in Kue admin ui is not natural

### ISSUE THREAD

**Issue by endorama** [Automattic/kue#591]
Hello and thanks for this module! :)

I've just discovered a strange behaviour, maybe someone else has noted this too. Jobs in the Kue admin interfaces are sorted numerically and not "naturally".  
What I mean is that job 10 is after job 1 instead of being after job 9. This is probably caused by the sorting function which sorts numerically by job id instead of using natural sorting.  Not a big issue really, more a reminder :)

**Comment by behrad** [comment]
this is because how kue uses priority sets in redis and the way redis sorts elements by lex.
I am closing as a duplicate to https://github.com/Automattic/kue/issues/33 
You can contribute and follow the same issue there :)

**Comment by endorama** [comment]
Sorry for the duplicate, I didn't notice that issue.

Thanks for the superfast feedback! :)
