### ISSUE TITLE
Application redirects to /active when used as express middleware

### ISSUE THREAD

**Issue by endorama** [Automattic/kue#592]
As reported by @digitaljohn and me in #587.

Step to reproduce:
* use kue app in a express application:  
    ```
    var app = express();  

    app.use(kue.app);

    app.listen(3000);
    ```
* try to reach http://localhost:3000

**Expected behaviour:**  
Redirect to http://localhost:3000/active

**Actual behaviour:**  
Redirected to http:///active/

Kue version: 8.1.2
Express version: 3.1.2
Npm version: 2.7.4
Node version: 0.12.2

**Comment by behrad** [comment]
whats your kue version?

**Comment by endorama** [comment]
8.1.2

**Comment by behrad** [comment]
we have no 8.1.2 version, dya mean 0.8.12 ?

**Comment by behrad** [comment]
if so, 0.8.12 is based on express 3.x and I don't think it can sit as a middleware in an express 4 app

**Comment by behrad** [comment]
however I'm not an express man, so any patches are welcome if anybody can provide something to fix this

**Comment by endorama** [comment]
Ups sorry :) yes is 0.8.12. I had a look at the code but is really simple, so the problem could be a little weird.

Hope to have time to look into this a bit more in the next weeks

**Comment by behrad** [comment]
have you tested if the above code (express 4.x) works in kue 0.9.0 ?

**Comment by h2non** [comment]
I'm experimenting the same trouble. I'll take a look to the code

**Comment by h2non** [comment]
Seems like this is related to the Express version. In my case using 3.x, where the `req` object interface is not the same as expected with Express 4.x. The field `baseUrl` is missing in 3.x and old versions.

**Comment by h2non** [comment]
I've created a PR that should fix this issue. #594

**Comment by behrad** [comment]
tested in 0.9.0, thank you @h2non

**Comment by hellboy81** [comment]
I am trying as follows:

```js
  var basicAuth  = require('basic-auth-connect')
  ....
   // Securing dashboard app
    var subApp = express()
    // add authentication
    subApp.use(basicAuth('foo', 'bar'))
    // re-add kue.app (but dont put it in its own folder)
    subApp.use('', messagesMod.kueDashboardApp)
    server.use('/kue', subApp)
```

**Comment by hellboy81** [comment]
If I call `/kue` endpoint, I got  redirect to `/kueactive`

I am using `kue` with [fixed  bad redirect URL issue](https://github.com/Automattic/kue/pull/594/files)

**Comment by behrad** [comment]
why not to use `server.use('/kue/', subApp)` ?
