### ISSUE TITLE
how to add jobs to the queue in different languages

### ISSUE THREAD

**Issue by amit777** [Automattic/kue#593]
Is it possible to add jobs to the queue in different languages such as python, php etc.. I have a couple legacy apps that I would like to be able to fire and forget some jobs.  Is there a specific format of json to publish to a redis object or pub/sub channel?

**Comment by sinoon** [comment]
So do i , and you may want to read [api](https://github.com/Automattic/kue#json-api) .

With that , `nodejs` can as a independence server running where you want.

**Comment by sinoon** [comment]
So do i , and you may want to read [README](https://github.com/Automattic/kue#json-api) and [post job](https://github.com/Automattic/kue#post-job) for more info.

Than , you can add jobs to queue by send a HTTP `POST` request with a lot of language.

~~With that , `nodejs` can as a independence server running where you want.~~

Also you can choose language whatever you want as long as it can send HTTP request.

hope it can help you~

**Comment by amit777** [comment]
Ahh.. thank you. I don't know why I didn't see the JSON API before.

**Comment by sinoon** [comment]
It's my pleasure , you are welcome~
