### ISSUE TITLE
Empty records in redis

### ISSUE THREAD

**Issue by robpolak** [Automattic/kue#597]
All,

   Let me know if I should post this elsewhere (could not find a user group).  I have been having an issue with items showing up in the job folder with no data.  Kue is showing no active jobs, however, these "empty" jobs keep building up.. here is an example:

http://imgur.com/cvCTU0Z

Any thoughts what could be causing this?

**Comment by behrad** [comment]
from your picture it seems this should be related to #559 
Would you please tell me which version of kue are you on?

**Comment by robpolak** [comment]
Running..  "version": "0.8.12",

In my code I am running large numbers of jobs (~10-20k) and I am doing a very simple queue then process then done, nothing out of the ordinary.  After running about 20k Items I am left with about 20 of these hashkey records.

Is there a way to force remove these?

**Comment by behrad** [comment]
this should be solved when you move to 0.9.0 (you should check changes before you upgrade however)

**Comment by behrad** [comment]
I can provide a patch for 0.8 branch if you are sticky

**Comment by behrad** [comment]
closing this as a duplicate, please follow #559
