### ISSUE TITLE
Error: job "1" doesnt exist

### ISSUE THREAD

**Issue by ogim** [Automattic/kue#598]
when I register a job with
    channels.kue.create("redis.key", "value").attempts(1).removeOnComplete(true).save(function(err){
        if( err ) {console.error( err );}
    });

and process it like this
    channels.kue.process(redis.key, function(job, done){
        throw new Error("something bad happened");
        done();
    });

in that case the next time if we process again we get an error each time

Error: job "1" doesnt exist
    at /Users/xx/Projects/aa/api.tws/node_modules/kue/lib/queue/job.js:169:17
    at try_callback (/Users/xx/Projects/aa/api.tws/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/Users/xx/Projects/aa/api.tws/node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (/Users/xx/Projects/aa/api.tws/node_modules/redis/index.js:321:14)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_reply (/Users/xx/Projects/aa/api.tws/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/Users/amigo/Projects/XTrade/api.tws/node_modules/redis/lib/parser/javascript.js:211:22)
    at RedisClient.on_data (/Users/xx/Projects/aa/api.tws/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/Users/xx/Projects/aa/api.tws/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:107:17)

kue is inited with
    channels.kue = kue.createQueue(
        {
            prefix: "kue",
            disableSearch: true,
            redis: {
                port:config.redis.port,
                host:config.redis.host,
                auth:config.redis.auth,
                db:config.redis.db.kueDB,
                options:config.redis.options
            }
        }
    );
    channels.kue.watchStuckJobs();

**Comment by behrad** [comment]
there was a critical bug in kue 0.9.0 which has been fixed just now and published to npm as 0.9.1, can you test it against 0.9.1?

**Comment by ogim** [comment]
cool youre fast i check

**Comment by ogim** [comment]
yep, good work, its solved

**Comment by behrad** [comment]
good for you :)

**Comment by ogim** [comment]
Can you please reopen it ?

I got the issue again

**Comment by behrad** [comment]
since you are calling `removeOnComplete` it will be deleted when `done` is called.

**Comment by ogim** [comment]
Hi Behrad

I got the issue again, here is the 

databse
localhost:6379[3]> keys *
 1) "tws.kue:job:11"
 2) "tws.kue:job:types"
 3) "tws.kue:job:10"
 4) "tws.kue:jobs:tws.U183300.api.cmd.kue:active"
 5) "tws.kue:ids"
 6) "tws.kue:jobs:inactive"
 7) "tws.kue:jobs:active"
 8) "tws.kue:jobs"
 9) "tws.kue:job:4"
10) "tws.kue:stats:work-time"

**Comment by ogim** [comment]
Warning: Redis server does not require a password, but a password was supplied.
Uncaught Exception...
Error: job "1" doesnt exist
    at /Users/amigo/Projects/XTrade/api.tws/node_modules/kue/lib/queue/job.js:169:17
    at try_callback (/Users/amigo/Projects/XTrade/api.tws/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/Users/amigo/Projects/XTrade/api.tws/node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (/Users/amigo/Projects/XTrade/api.tws/node_modules/redis/index.js:321:14)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_reply (/Users/amigo/Projects/XTrade/api.tws/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/Users/amigo/Projects/XTrade/api.tws/node_modules/redis/lib/parser/javascript.js:211:22)
    at RedisClient.on_data (/Users/amigo/Projects/XTrade/api.tws/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/Users/amigo/Projects/XTrade/api.tws/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:107:17)

**Comment by ogim** [comment]
re: since you are calling removeOnComplete it will be deleted when done is called.

aha, in that case do you think kue should crash on that ?

**Comment by ogim** [comment]
when removeOnComplete is enabled i dont expect the dequer to see it again, or maybe the error is coming from done(), illcheck that when i get into error the next time

**Comment by ogim** [comment]
so it is definitively not coming from done() in dequer/process, i can expect that done would raise an error when removeOnComplete is enabled, because it would remove the item from que while it is allready removed. 

what i dont expect is that the dequer raises an error immediately

**Comment by ogim** [comment]
also with removeOnComplete set to false it will raise the same error, ill flush the db, maybe it is in deplorable state

**Comment by behrad** [comment]
if you can reproduce this, please post me the code with github markup

**Comment by ogim** [comment]
ill prep this evening

**Comment by ogim** [comment]
Here it is:

run the script below ones and after that once more with a disabled throw line

it will fail with "Error: job "1" doesnt exist"

rgds,

Pieter

```javascript
'use strict';

var
	redis = require('redis'),
	kue = require('kue');


var queue = kue.createQueue({
	prefix: "kue",
	disableSearch: true,
	redis: {
		port:6379,
		host:"127.0.0.1",
		db:3,
		options:{
			"detect_buffers":true
		}
	}
});
queue.watchStuckJobs();

function create(){
	queue.create("test", {cmd:"setServerLogLevel",args:5}).attempts(1).removeOnComplete(true).save(function(err){
		if( err ) {console.error("queue", err);}
	});
}

function process(key,callback){
	queue.process(key, function(job, done){
		var data;
		try{
			data=JSON.parse(job.data);
		}
		catch(e){}
		if(job && data){job.data = data;}

		callback(job);

		done();
	});
}

create();
create();
create();

process('test', function ( job ) {
        //disable the error the second time you run this script
	throw new Error("something went wrong");
	console.log(job.data);
});

```

**Comment by ogim** [comment]
I suspect detect_buffers true,
when detect_buffers is false I cant reproduce it. I am using detect_buffers in my generic redis settings  because I pass binairy data in redis, though not in kue, so strictly i dont need that setting, at this moment.

**Comment by behrad** [comment]
read these: https://github.com/mranney/node_redis/issues/263, https://github.com/mranney/node_redis/pull/733, https://github.com/mranney/node_redis/pull/471

Can you merge https://github.com/mranney/node_redis/pull/733 in your node_redis dependency inside kue and test?

**Comment by ogim** [comment]
Thanks !

just merged and cant reproduce the problem anymore. seems solved.

**Comment by behrad** [comment]
so this is actually a `node_redis` issue, hope they resolve that there soon :)

**Comment by ckee83** [comment]
> Can you merge NodeRedis/node_redis#733 in your node_redis dependency inside kue and test?
Can you elaborate on how to do this? I am experiencing the same problem. In Kue's package.json I do not see node_redis as a dependency, only 'node-redis-warlock'.
