### ISSUE TITLE
TTL exceeded

### ISSUE THREAD

**Issue by kirrg001** [Automattic/kue#599]
hey,

i currently have an issue with TTL exceeded error message.
my jobs getting directly exceeded and i don't know why.

Create Job Somewhere
````
var job = jobs.create('eventname....', data);

job.on('failed', function(errorMessage) {
  // here the error message comes
})

job.save();
````

Listen Somehwere
```
jobs.process('eventname....', 100, function(job, done) {
    // here i call something async with http and wait for the answer
    request.get(....)
        // wait async for the answer
        // i delay a new job and finish the old one with an error message ('delay')
       // or i complete the current job
})
```

i have the feeling the http async operation maybe takes too long and then TTL exceeded is fired.

line 222 in kue.js (version 0.9.0)
````
client.zrangebyscore(client.getKey('jobs:active'), 0, Date.now(), "LIMIT", 0, limit, function( err, ids ) {
````

this filters my job. so the job is active and gets exceeded.

when i set ttl to ````job.ttl(10000000);````` it works, but actually i dont want a ttl, because ttl is default undefined, which is fine (this._ttl).

Any suggestions?

Thanks
Kate

**Comment by behrad** [comment]
if you are on `0.9.0` please update to '0.9.1'

**Comment by behrad** [comment]
https://github.com/Automattic/kue/commit/5d1b05677e6b8cdfdd9e9d91da4c4bd2333e611b

**Comment by kirrg001** [comment]
:+1: super thanks
