### ISSUE TITLE
Prevent kue from accept jobs

### ISSUE THREAD

**Issue by btmdave** [Automattic/kue#600]
We have several 'worker' scripts that run kue jobs, each script is run on a different server.  When we need to do maintenance on a particular server, we'd like to be able to tell that server to stop processing any new jobs.  Is there anyway to do this?

**Comment by btmdave** [comment]
Just to clarify, we don't want to shut down with a timeout, because some jobs may need to continue running for 30min or whatever the case may be, they vary.  We'd want to finish all active jobs, but stop accepting new ones.

**Comment by behrad** [comment]
> we don't want to shut down with a timeout, because some jobs may need to continue running for 30min or whatever the case may be, they vary. We'd want to finish all active jobs, but stop accepting new ones


why aren't you using `shutdown( 30min )` ?

**Comment by behrad** [comment]
have you also looked at the worker `pause` API?

**Comment by btmdave** [comment]
Yeah, will use `shutdown( 5hrs )`, kind of an oversight, was thinking it would wait for timeout, even if there's no active.  Thank you
