### ISSUE TITLE
{jobEvents: false} at the job level

### ISSUE THREAD

**Issue by pcothenet** [Automattic/kue#610]
I recently fixed a memory issue I had when creating many jobs with tje jobEvents parameter introduced by https://github.com/Automattic/kue/issues/401.

However, since there is only one instance of kue per module, disabling it disable job events for my entire module. Is there (or could there be) a way to disable job events on a job per job basis?

Thanks!

**Comment by behrad** [comment]
yes we can also add per job granularity something like:
```js
queue.create( 'my-job', {} ).events( false ).save();
```
or even:

```js
createQueue( { disableJobEvents: [ 'my-job' ] } );
```

which sets per job type but needs API change.

I prefer the first, however applications should take care to consistently use `events(false)`

**Comment by pcothenet** [comment]
The first one would work great in my case.

**Comment by pcothenet** [comment]
@behrad I'd like to give this a shot but wanted to make sure this hasn't been started yet.

**Comment by behrad** [comment]
> wanted to make sure this hasn't been started yet

I didn't get you @pcothenet 
This is already done, totally forgotten to close this:

`kue.createQueue({jobEvents: false})`

**Comment by pcothenet** [comment]
Not sure I get your answer. 

```kue.createQueue({jobEvents: false})``` disable events at the queue level.

I have a bunch of jobs for which I would like to disable events (because there are many of them), but keep events for other.

**Comment by behrad** [comment]
You can simply patch https://github.com/Automattic/kue/blob/2e9d5f201b43f5f1f3689fb475b9172b7f1396cb/lib/queue/job.js#L848 refactoring `jobEvents` to a property of Job class
