### ISSUE TITLE
Why connect ETIMEDOUT?

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [Automattic/kue#619]
```
{ stack: 'Error: Redis connection to 192.168.1.88:6379 failed - connect ETIMEDOUT\n  at RedisClient.flush_and_error (/srv/node_modules/redis/index.js:149:13)\n  at RedisClient.on_error (/srv/node_modules/redis/index.js:191:10)\n  at Socket.<anonymous> (/srv/node_modules/redis/index.js:106:14)\n  at Socket.emit (events.js:95:17)\n  at net.js:440:14\n  at process._tickDomainCallback (node.js:463:13)\n',
  message: 'Redis connection to 192.168.1.88:6379 failed - connect ETIMEDOUT' }
```
Some job success , other job failed?

code as follow(`coffeescript`)
```
kue     = require 'kue'
config  = require '../config'
jobs    = kue.createQueue config.kue

jobs.on 'error', (e) ->
  console.log 'kue jobs error'
  console.log e
```

**Comment by behrad** [comment]
the error shows your connection to redis server is timed out. check your server not crashed, and connection to `192.168.1.188` is healthy

**Comment by feifeiiiiiiiiiii** [comment]
redis server not crashed, some job connect redis `success`, other job connect redis `failed`, I guess `network` cause!!!

**Comment by behrad** [comment]
you should check your connectivity stability then....

**Comment by jorgelozano95** [comment]
@behrad  Could you recommend a reconnection handling when this kind of error happens?

**Comment by behrad** [comment]
I believe this should be handled by node_redis / ioredis modules inside kue.
