### ISSUE TITLE
Cannot find module 'jade' when accessing web ui on 0.9.3

### ISSUE THREAD

**Issue by endorama** [Automattic/kue#620]
I'm experiencing this problem with latest version and the web ui. I've seen #583 but I'm not using tarball or master branch, just a plain npm installation.

Trying to access web ui results in the error:
```
Error: Cannot find module 'jade'
     at Function.Module._resolveFilename (module.js:336:15)
     at Function.Module._load (module.js:278:25)
     at Module.require (module.js:365:17)
     at require (module.js:384:17)
     at new View (/vagrant/node_modules/express/lib/view.js:50:49)
     at EventEmitter.app.render (/vagrant/node_modules/express/lib/application.js:545:12)
     at ServerResponse.res.render (/vagrant/node_modules/express/lib/response.js:938:7)
     at /vagrant/node_modules/kue/lib/http/routes/index.js:22:11
     at try_callback (/vagrant/node_modules/kue/node_modules/redis/index.js:592:9)
     at RedisClient.return_reply (/vagrant/node_modules/kue/node_modules/redis/index.js:685:13)
```

Tried to remove kue and reinstalling:
```
$ npm install kue
kue@0.9.3 node_modules/kue
├── lodash-deep@1.6.0
├── redis@0.12.1
├── nib@0.5.0
├── lodash@2.4.2
├── node-redis-warlock@0.1.2 (uuid@2.0.1, node-redis-scripty@0.0.5)
├── body-parser@1.12.4 (content-type@1.0.1, bytes@1.0.0, depd@1.0.1, raw-body@2.0.1, qs@2.4.2, on-finished@2.2.1, iconv-lite@0.4.8, debug@2.2.0, type-is@1.6.2)
├── stylus@0.42.2 (css-parse@1.7.0, mkdirp@0.3.5, debug@2.2.0, sax@0.5.8, glob@3.2.11)
├── reds@0.2.5 (natural@0.2.1)
└── jade@1.1.5 (character-parser@1.2.0, commander@2.1.0, mkdirp@0.3.5, monocle@1.1.51, with@2.0.0, transformers@2.1.0, constantinople@1.0.2)
```

But the problem persists.

Installing `jade` ( `npm install jade` ) solves the problem.

**Comment by behrad** [comment]
jade is in kue's dependencies and should be installed via NPM https://github.com/Automattic/kue/blob/master/package.json#L30
It may be caused by a temporary connection/SSL problem on npm repos

**Comment by endorama** [comment]
```
$ ls node_modules/kue/node_modules
body-parser  jade  lodash  lodash-deep  nib  node-redis-warlock  redis  reds  stylus
```

Jade seems to be correctly installed as kue dependecy. But still a "application-wide" installation is needed.

Just my 2 cents: I noticed that express is not installed as kue dependency, but is installed at the same level   
```
$ ls node_modules/
async          ...                   grunt-contrib-cssmin  kue            sails-disk
basic-auth     ...                   grunt-contrib-jst     lib            sails-mongo
...            ...                   grunt-contrib-less    lodash         sails-mysql
...            express               grunt-contrib-uglify  ...            shelljs
...            grunt                 grunt-contrib-watch   moment         unirest
...            grunt-contrib-clean   grunt-sails-linker    q              winston
deasync        grunt-contrib-coffee  grunt-sync            rc
...            grunt-contrib-concat  include-all           readline-sync
ejs            grunt-contrib-copy    jade                  sails
```
This happens probably because express is already a dependency in my application and npm is 'reusing' that module. Could this be the problem? ( Is quite reasonable that installing jade at the same level of express makes everything works ).

**Comment by behrad** [comment]
it seems you are using kue.app inside your express app, this is an error inside your express app or so, nothing related to cue

**Comment by endorama** [comment]
I'll try to figure that out. Closing, thank you for your feedback.

**Comment by jdrydn** [comment]
So, if my project has a dependency on both `express` and `kue`, and since `express` will install before `kue` when running `npm install` (I'm assuming this is due to alphabetical organising of `package.json`?) then `npm` tries to be extremely "helpful" and de-dupes the dependencies. This results in the `kue.app.listen` call failing, since the Kue app requires `jade` and my project doesn't use `jade` at all (and I'm assuming the OP's app doesn't require `jade` either, hence the same issue, as spotted from `at ServerResponse.res.render (/vagrant/node_modules/express/lib/response.js:938:7)`).

Therefore this points to an error (or a conflict of features) in `express` or `npm`. Personally I think it's an issue in `express`, since `express` should handle view engines better when building applications, however there's a fair argument it's `npm`'s fault for unwanted de-duplication.

**Quick fix:**

```sh
$ rm -rf node_modules/express node_modules/kue
$ npm install kue
$ npm install express
```

Or have a separate repository / collection of files for the Kue Web UI, taking care to ensure the connection parameters point to the same redis instance as your main project.

**Comment by behrad** [comment]
can anybody with this issue test and verify #649 fixes this?

**Comment by alpenliebe** [comment]
Thanks , as @jdrydn said , it's simple just NPM's fault. the most easy solution is to require the kue's express module in your project.
$ var express = require('kue/node_modules/express')

**Comment by jdrydn** [comment]
@alpenliebe I'm ever so sorry but in my head that is not an acceptable fix - forcing your project to rely on Kue's version of `express` (which may not be the latest version and/or the version that you want) should not be the correct way forward.

The solution really is to either convince NPM not to flatten packages (which isn't always great...) or to "trick" packages higher up the path that packages they need are lower down the path. Or my solution, which forces Kue to use Jade with whichever version of Express it can find.

**Comment by behrad** [comment]
@jdrydn is right.
