### ISSUE TITLE
job.create().save(function(err){}) callback not working for my case

### ISSUE THREAD

**Issue by gauravnayak210** [Automattic/kue#623]
hi,
I need an urgent solution to my below issue..

We have a scenario in which redis-sentinel is used but not configured when running the application. Here, we are creating Kue jobs which throws error as sentinel is not running[You can see this in CreateQueue.js file]. But the application in not crashing. We are then exporting the Kue Jobs object to worker.js file.

Now the issue is, in above scenario, when we are attempting to create a job, the job is created but its not definitely saved, as you can see in the code block ( Worker.js ) that there are three lines for logging, but none of them are actually being logged. At this time, the job is created but not in any if these state: failed, queued, active, complete and delayed.

Everything is working properly if Redis-sentinel is configured correctly. Actually we want to perform some task if any error occurs in saving the job.

CreateQueue.js
--------------
var kue = require('kue');
var Sentinel = require('redis-sentinel');
// 
// Some other code
//
jobs = kue.createQueue({
       redis: {
           createClientFactory: function () {
               console.log('Connected');
               return sentinel.createClient(masterName, opts);
           }
       }
   });
   
var data = [
   jobs = jobs
];

module.exports = data;

jobs.on('error', function (err) {
   console.log('Error occured on queue :  ', err); // This line is printing below error on console
});

output:
Error occured on queue :   [Error: Failed to find a sentinel from the endpoints]

worker.js
---------
var queueDetails = require("./createQueue");
var jobs = queueDetails[0];

var job = jobs.create('TestJob', {
	   title: 'TestJob',
	   queueId: id
	})
	.ttl(5 * 60 * 1000)
	.attempts(3)
	.backoff({ delay: (30 * 1000), type: 'fixed' })
	.removeOnComplete(true)
	.save(function (err) {
	   console.log('Not logging when there is error');
	   if (err)
		   console.log('ERROR : ', err);
	   else
		   console.log('The job running is ', job.id);
	});

**Comment by behrad** [comment]
1. please post your codes in proper markup to be readable.

2. post your error in case you are telling `.save` callback is not being called

**Comment by gauravnayak210** [comment]
Thanks for your quick reply..

I am not getting any error in .save() callback neither it is being called when redis-sentinel is not configured or misconfigured. ( But if redis-sentinel is configured properly, everything is working parfectly)

my .save() callback portion looks like,

.save(function (err) {
	console.log('Not logging when there is error');
	if (err)
		console.log('ERROR : ', err);
	else
		console.log('The job running is ', job.id);
}

and I am not getting any log.
so it indicates that callback is not executed.

**Comment by behrad** [comment]
since this is a reds client conf problem it should go to `jobs.on('error')` however if you are not already getting it there, tell me how can I reproduce this without having redis-sential installed

**Comment by gauravnayak210** [comment]
Yes you're right, we are able to catch that redis-sentinel error in
`jobs.on('error')`
when 
`kue.createQueue(function() {})`
 is done. (in CreateQueue.js)

But the issue is, at the time when attempting to create a job, we are not getting any log in callback of  `jobs.create().save()` . ( in worker.js).

**Comment by behrad** [comment]
I don't consider this an issue. please re-open at restate your issue if still a problem
