### ISSUE TITLE
Move website into own repo

### ISSUE THREAD

**Issue by Incognito** [Automattic/kue#626]
In the interest of making Kue smaller, can we move the admin page into a second repo that connects to kue proper?

**Comment by behrad** [comment]
this has been discussed in other issues also, please search it and drop your comments, however I'm interested to see what would you get from this?

**Comment by Incognito** [comment]
So I've just read over #339 and #153, and I don't see the core reason why we can't have a second repo. The present state of things feels like shipping MySql with PHPMyAdmin, where a great many people really don't want PHPMyAdmin installed even though some people find it useful (so they go install it).

This is also helpful for scaling up microservices that just do one thing rather than running many services with a walled off feature. For instance, this could even be taken to a place where the worker and promoters are their own packages (ie, kue-promoter, kue-worker, kue-web-gui) which can be composed into "kue" if need be to run all of these in the same node script execution.

After reading the tickets I'm not sure I can sway you on this. Until you can be brought around I'll try to keep a fork of the project.

**Comment by behrad** [comment]
simplicity is my high priority.

I won't resist separating the JSON API/Web console into another project, however then for small, simple installations user should be aware of installing two projects, with two configuration points...
