### ISSUE TITLE
Is it still necessary to call promote()

### ISSUE THREAD

**Issue by tianp** [Automattic/kue#638]
Hi,

Kue at early days suggest to call promote() in the docs, and few weeks back I upgraded Kue into version 0.8.12 and still calling promote() at my code. But in the newer version the suggestion or explanation about promote() is no longer in the docs but still existed in code example https://github.com/Automattic/kue/blob/master/examples/delayed.js

So I just wondering is it still necessary to call promote() using this newer version?

**Comment by behrad** [comment]
I've forgotten to update examples directory @tianp My Bad!
from Kue 0.9 on you don't need `promote` however if you are on 0.8 branch you still need to stick to it. You can read the 0.8.x docs https://github.com/Automattic/kue/tree/0.8

**Comment by behrad** [comment]
https://github.com/Automattic/kue/issues/640
