### ISSUE TITLE
Delayed Job triggered immediately

### ISSUE THREAD

**Issue by tianp** [Automattic/kue#639]
Hi,

I create a job with delay options, but instead of wait for the amount of delay, it triggered immediately just like ignoring the delay options. The strange is, this only happens in our production server. In the dev server, the delay works just fine. 

We share same source code and Kue version between production and dev. 

```
jobs.create( 'task1', {test:'123'} )
  .delay( 300000 )
  .save(function( error ) {
    console.log('saved')
})
```

```
jobs.process( 'task1', function( job, done ) {
  console.log('processed')
  done()
})
```

Is anyone ever have this issue?

**Comment by TimofeyBiryukov** [comment]
I am having the same issue. Thing is, its not consistent. Some times delay would work, and some times for the first job (after server lifted) it getting processed immediately.

**Comment by behrad** [comment]
tianp's problem was a coding issue which resolved in another topic, it may be a race in your app, please debug and provide more info first

**Comment by TimofeyBiryukov** [comment]
Apparently jobs witch were getting processed on the start are earlier job
delayed earlier. Witch came obvious after debugging.

ср, 17 июня 2015 г. в 20:36, Behrad <notifications@github.com>:

**Comment by behrad** [comment]
so can we close this now?

**Comment by TimofeyBiryukov** [comment]
Yes.

чт, 18 июня 2015 г. в 19:22, Behrad <notifications@github.com>:
