### ISSUE TITLE
TTL exceeded when task re-activated

### ISSUE THREAD

**Issue by mikob** [Automattic/kue#641]
I have a task that fails, it's queued like this:

```js
var jobId = queue.create('test-job', {
            title: "test-job",
            arg:  20
        }).delay(35000).attempts(5).ttl(3000).backoff({ delay: 5000, type:'fixed' }).priority('high').save();
```

When I change the state to 'active' in the kue-dashboard, the task immediately fails with `TTL exceeded` without attempting to execute the job.

**Comment by behrad** [comment]
changing the state to `active` in the kue-dashboard is not a standard way to make jobs active!
inactive jobs should be grabbed by workers.

**Comment by mikob** [comment]
it wasn't an inactive job, it was a failed job. What's the standard way of restarting failed jobs?

**Comment by behrad** [comment]
if you want to go for the sixth attempt, change job state to `inactive` from failed.
