### ISSUE TITLE
Add support for Redis Cluster

### ISSUE THREAD

**Issue by dg3feiko** [Automattic/kue#642]
Redis cluster is a much better solution for HA then sentinel, I tried to pass a cluster enabled redis client to kue.js but it didnt work. I used ioredis as the redis client, its interfaces are very similar to node-redis but with some subtle difference, e.g. message subscription and lua script loading and invocation.

Glad to see redis cluster support in kue.js.
Thanks

**Comment by behrad** [comment]
Glad too see a PR supporting ioredis according to https://github.com/luin/ioredis/wiki/Migrating-from-node_redis

**Comment by tianp** [comment]
+1

**Comment by behrad** [comment]
We should also add support for ioredis. I should check @az7arul's PR.

**Comment by VijayKumarMidde** [comment]
+1

**Comment by verxx** [comment]
+1

**Comment by chaudhryjunaid** [comment]
+1

**Comment by chaudhryjunaid** [comment]
Although node_redis and ioredis will merge, there seems to be no set timeline regarding this!

**Comment by behrad** [comment]
Done through #652
