### ISSUE TITLE
error callback getting hit twice?

### ISSUE THREAD

**Issue by kevinburkeshyp** [Automattic/kue#644]
hey, we're running kue 0.8.x. imagine redis is *not* running, so any connection attempts generate an ECONNREFUSED - dumb case, but the easiest to reproduce the issue:

we have code that looks like this:

```javascript
var queue = kue.createQueue(redis: config.redis)
queue.create('notification-service', jobData).save(function(err) {
  if (err) {
    return cb(err, false);
  }
  return cb(null, true);
});
```

I observe that this callback is getting hit with an error. I also observe the event emitter is getting hit with an error, if I add it:

```javascript
queue.on('error', function(err) {
  console.trace();
  return console.log("caught emitted error: ", err);
});
```

The error looks like:

```
[Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED]
```

I am a little confused. I expect this situation to have an error - I would just expect either the callback to save() to contain a non-null error, or the eventemitter to contain an error, but not both.

**Comment by behrad** [comment]
I can't see what the problem is with this?
your `save` is unsuccessful so clbk(err) should be called, and all redis error events are also emitted to kue as `error`.

**Comment by kevinburkeshyp** [comment]
I guess the problem is that any error handling operations (logging, cleanup) may be being run twice.

**Comment by behrad** [comment]
`save` and `createQueue` are two different operation requests of your app to kue, so you should expect two answers :) 
In node's event driven world, you may receive `on('anything`...)` whenever in middle of your operations.

**Comment by kevinburkeshyp** [comment]
ahhh... I didn't realize that the eventemitter events were coming from the `createQueue` operation and not the `save` operation. Ok. Thanks!
