### ISSUE TITLE
Multiple instances of the same app

### ISSUE THREAD

**Issue by jamc** [Automattic/kue#645]
How does Kue handle the following scenario:

I have 2 instances of the same app queueing jobs with Kue to the same Redis server with the same prefix.

I also have 2 instances of other app processing the jobs from the same queue, each app has 3 workers with concurrence 5.

Will this cause conflict? Does Kue manage locks or something?

Thanks in advance.

**Comment by behrad** [comment]
Kue is designed for this. by the help of `Redis` as a shared storage.

**Comment by jamc** [comment]
Thanks for the response.

We faced a problem where it seems that some data on redis or something got corrupted. We decided to have different prefix per app stacks and everything seems to work fine now.

We will be investigating this issue, it may or may not be a Kue issue.

Thanks for the support!

**Comment by behrad** [comment]
happy kueing @jamc
