### ISSUE TITLE
Delay can't work in production

### ISSUE THREAD

**Issue by tianp** [Automattic/kue#647]
Hi,

Still having an issue in my production server where the delay is not working even though the delay option is filled properly (around 5 mins), see screenshot. It stated ```delayed``` at first, but then after a few seconds it immediately fired.

I'm using Ubuntu 12.04.4 and Kue 0.8.12, with Redis and app in one server.

Any advice?

![screen shot 2015-06-17 at 5 56 10 pm](https://cloud.githubusercontent.com/assets/313285/8205406/981e9eee-151a-11e5-956b-16932a99857f.png)

**Comment by behrad** [comment]
Kue 0.8.x is almost stably tested to be working by many users, however this could be a potential bug if you are doing something wrong in your code or promote call.
I can't say more with this info, why aren't you upgrading to `0.9` ?

**Comment by tianp** [comment]
Hi @behrad, thanks for your quick response.

I just upgrade Kue to ```0.9``` in my local dev and follows upgrading instructions. After upgrading, the JSON API is not working properly and return ```204``` HTTP response with empty content when creating new jobs. Note that I'm using ```kue-ui```, before this upgrade the JSON API works just fine. 

Any idea why is this happening?

**Comment by tianp** [comment]
I'm sorry, turns out I'm sending invalid JSON that makes ```204``` HTTP response. 

So I just upgrade Kue into 0.9.3 both in my local dev and production environment. But the issue still persists, it still exactly as I said "It stated delayed at first, but then after a few seconds it immediately fired." but in my local dev it's delayed just fine.

Please see screenshot for the job info, and take a look at the intervals between ```created_at``` and ```promote_at``` is exactly ```50,000ms``` equal with the delay option. But still can't figured why the job is fired after few seconds.

![screen shot 2015-06-17 at 7 11 18 pm](https://cloud.githubusercontent.com/assets/313285/8206644/b2c58414-1525-11e5-9723-f9d4df9bee5f.png)

**Comment by behrad** [comment]
all timestamps look ok, `started_at` shows when job has been started

**Comment by tianp** [comment]
I'm really sorry, this is completely my bad. In my codes create the delay seconds, and I always assumed it was milliseconds, silly me. So the delay is working good now in my production environment. 

Thanks @behrad to spared your time to response my issue.
