### ISSUE TITLE
Can't set TTL in JSON

### ISSUE THREAD

**Issue by oleghind** [Automattic/kue#650]
Can't find anywhere in docs how to set TTL when creating new Job through API:

probably in source code such a line is missing in `exports.createJob` function:

```javascript
if( options.ttl ) job.ttl(options.ttl);
```

**Comment by behrad** [comment]
I don't remember adding `ttl` through JSON api, you can create a PR if you don't mind :)

**Comment by oleghind** [comment]
sure https://github.com/Automattic/kue/pull/651
