### ISSUE TITLE
Delete active/delayed jobs based on data

### ISSUE THREAD

**Issue by tianp** [Automattic/kue#653]
Hi,

It would be nice if I could remove one or several jobs based on its data. Example job data:

```
{
  "id": 123,
  "data": {
    "userId": "001",
    "email": "mail@example.com"
  }
}
```

I can delete the job (active/delayed) using:

```$ curl -X DELETE http://local:3000/job/userId/001``` 

or

```$ curl -X DELETE http://local:3000/job/email/mail@example.com``` 

or any other similar approach.

**Comment by behrad** [comment]
If you are turning indexes on, you can search on your data by Kue, find job Ids and simply remove them
If you are not using search indexes, store jobIds with your meaningful logic data in your app (r.g. on redis) then lookup job ids in your cache and remove them :)

**Comment by tianp** [comment]
Thanks a lot! @behrad
