### ISSUE TITLE
How to delete a specific job id using Job object?

### ISSUE THREAD

**Issue by tianp** [Automattic/kue#654]
Hi,

In the docs, I can't found a way to delete a specific job id using Job object. I need something similar like ```kue.Job.delete( jobId )``` or  ```job.remove( jobId )```

I need this to cancel a delayed job without using JSON API.

**Comment by behrad** [comment]
using jobId
`kue.Job.remove( jobId )`

using job object
`job.remove()`

**Comment by tianp** [comment]
I think the ```kue.Job.remove( jobId )``` needs to be putted in the docs.

Thanks anyway :)

**Comment by dmastylo** [comment]
Yeah, this should be added to the documentation. Why isn't there a return value when you call remove?

**Comment by behrad** [comment]
> Why isn't there a return value when you call remove?

what return value?

**Comment by dmastylo** [comment]
To verify job was removed? Or is there no worry about that?

**Comment by behrad** [comment]
you should provide a callback for this:
```js
 kue.Job.remove( jobId, function(err){})
```

**Comment by dmastylo** [comment]
Thanks!
