### ISSUE TITLE
Merging and superceeding jobs

### ISSUE THREAD

**Issue by nyurik** [Automattic/kue#658]
Hi, I am considering to use Kue for map tile regeneration, which means the jobs are ranges of tiles to be re-generated - a set of (startIndex,count) tuples. Frequently, new ranges will be added, and they may overlap with the pending ones.  What is the best way to manage such ranges, merge them, or possibly invalidate parts of them (e.g. part of the range is no longer needed - should the job be cancelled, and the range broken up into two and resubmitted?) Thanks!

**Comment by behrad** [comment]
I'm not sure I'm getting your point of question right!

**Comment by nyurik** [comment]
@behrad, my point is this:  I need to generate data blobs, each of which is indexed with an integer. For example, my system may decide it needs 60 data blobs starting at 2440, or it needs just one data blob at 2480. Sometimes the number of items would be on the order of 10s of millions, so it might not make sense to enque them all individually.  Frequently the ranges may overlap (like in this example), so the system needs to prevent double-processing as much as possible. The generation will happen on multiple servers, but I could in theory make enqueuing all happen on one server.  So the question is - what's the best way to adapt Kue to serve this need, and also, how should I handle de-duplication.  Thanks!

**Comment by behrad** [comment]
As I got you need to relate overlapping job ids to current job id and cancel them... if true

1) Kue does not know any de-duplication or even worker business logic, it is your apps duty on top to relate job ids using any shared data structures (one of best is the redis itself).

2) If you are gonna cancel some jobs, always there is a race between cancel command and the queued jobs being started (activated). take this in mind.

All this is when taking that you don't know about overlapping jobs when creating them! So you blindly create some jobs... after which you expect to cancel some preventing them to process, if the above doesn't hurt your logic.
However if you already can relate jobs, you can do better, for example playing with job priorities to give some jobs lower possibility to start!

said all these knowing abit of your problem, and I think there should be more details decisive

**Comment by nyurik** [comment]
@behrad, #2 is fine - i can do the same work twice - its not optimal, but it won't hurt.  My question is really how to do #1. I will be adding many ranges, some with lower priority than others. As they are processed, there will be new ranges added or removed, and I would like to somehow optimize duplicates - so that if possible, it wouldn't do it more than once.  I guess the de-duplication logic should happen when new range is added to the queue - should it simply iterate through all the pending items and update?  E.g. If there is a pending range that partially overlaps with the new one, expand existing one. If by expanding it, it overlaps other ranges, combine them all into one. If nothing overlapping is found, add a new one.  Or should I somehow manage it on the side? In which case, what do i store in Kue?

**Comment by behrad** [comment]
Seems you should update some jobs on any new job. You can bind to queue events and update jobs easily, however there should an external structure to make your path through the job ids.
I've not any coding experience on tiles and maps, but you may need an interval tree implementation or R-tree implementation to store jobs ids in tile intervals, and retrieve overlapping jobs ids with any tile interval.

**Comment by knutole** [comment]
I'm using Kue for tile creation also, and in general I can say it works great! Running into a simliar problem as @nyurik here, and I need to cancel jobs in groups. Is there any way I can assign a custom `id` (non-unique) to Kue jobs when creating them, and then cancel said jobs in groups (hence non-unique id)?

**Comment by behrad** [comment]
No, I always store a (somethingId, job.id) pair somewhere and when something needs to be canceled, I lookup `somethingId` to find `job.id` and then cancel (remove/...) that job :)

**Comment by knutole** [comment]
That's what I figured. Thanks.

**Comment by behrad** [comment]
I'm closing this for now guys, don't mind to open it later

**Comment by knutole** [comment]
Why is `job.id` undefined right after having created the job?

```javascript
var job = jobs.create('render_raster_tile', {
	params : params,
	storedLayer : storedLayer
}).priority('high').ttl(2000).removeOnComplete(true).attempts(5).save();

console.log(job.id); // undefined 
```

**Comment by behrad** [comment]
> Because job.id is only set when job is active. Thanks. ;)

No, because you should try to learn more about asynchronous programming in node.js
The correct is:
```js
var job = jobs.create('render_raster_tile', {
    params : params,
    storedLayer : storedLayer
}).priority('high').ttl(2000).removeOnComplete(true).attempts(5).save( function(err){
  console.log(job.id); 
});
```

**Comment by knutole** [comment]
Yes, I was a bit quick to judge there. Thank you.

**Comment by behrad** [comment]
;)
