### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jesusbotella** [Automattic/kue#662]
Hi,

I'm trying to use Kue for my project and I'm struggling with it to make it work.

I set up two queue processes in Kue. One process is done first, and then, I create a new one from other type with the data I obtained from the first one.

When the second one is running, and it is almost finished, it throws me this error:

    Unhandled rejection RangeError: Maximum call stack size exceeded

The first process finished correctly with no error, and done function was called.

I attach the code from the second process I'm running

    var price = function (job, done) {
        var variant_id = job.data.variant_id,
        price = job.data.price;

	DB.subscriptorsToNotifyPrice(variant_id, price)
	.then(function (result) {
		return new Promise (function (resolve, reject) {
			var request_data = {
				variant: result[0].variant_id,
				subscriptors: _.map(_.map(result, 'subscriptor'), 'email')
			};

			request.post({
					url: 'http://localhost:5000/notify/price',
					form: request_data
				},
				function (err, response, body) {
					if (err) return reject(err);
					if (response.statusCode !== 200) return reject(body);
					return resolve(body);
				}
			);

		});
	})
	.then(function() {
	    done(null, "Acabado");
	})
	.catch(function(err) {
                done(err);
		console.log(err);
		throw err;
	});
    };

When I remove the request function in the code, the error disappears but I don't think that there are any errors in the module.

Do you have any clue about it?

Best regards,
Jesús.

**Comment by behrad** [comment]
the error message sounds like it is related to your promise rejection. May it be concerned to `reject(body)`?

This is not related to Kue however :)
