### ISSUE TITLE
Job processing priority threshold

### ISSUE THREAD

**Issue by lebek** [Automattic/kue#663]
Is there any existing mechanism to process jobs with priority above a threshold (e.g. medium)?

**Comment by behrad** [comment]
I'm not sure if I understand your question.

You can queue jobs with four levels of priorities https://github.com/Automattic/kue#job-priority
Kue is a priority queue, meaning that higher priority jobs are higher to get processed first always.

**Comment by lebek** [comment]
I want to have a job processor that *only* accepts high priority jobs. Relying on the priority system alone can cause problems when a low priority job is running, and then a high priority job comes along and has to wait for the low priority job to complete. My plan was to have a few workers just accepting high priority jobs. A workaround is to create a separate queue for the high priority jobs.

**Comment by behrad** [comment]
seems you jobs are pretty long running, otherwise the priority queue would work as expected.
as you mentioned if you need full control on your urgent jobs, then simply use a different job type instead of priority.
