### ISSUE TITLE
next() route is not invoked

### ISSUE THREAD

**Issue by gauravnayak210** [Automattic/kue#667]
I have created custom middleware for handling gzip compressed data coming in request body.

In below code block, "gunzipTest" function to decompress data is working correctly (it gives me correct json data), But the issue is my next() route is not being invoked, 
even I don't get any error in the code block.

Please suggest.

```
app.use(function (req, res, next) {
        var dataStr = '';
        req.on("data", function (chunk) {
            dataStr = dataStr + chunk;
            if (dataStr.length == req.headers['content-length']) {
                gunzipTest(dataStr, function (err, result) {
                    if (err) {
                        console.log('err: ', err);
                        next(err);
                    } else {
                        req.body= result.toString();
                        console.log('result : ', req.body);
                        next();
                    }
                });
            }
        });
    });

    function gunzipTest(dataStr, cb) {
        var buffer = new Buffer(dataStr, 'base64');
        nodeZlib.unzip(buffer, function (err, res) {
            if (err) {
                cb(err, null);
            }
            else {
                cb(null, res);
            }
        });
    }

```
Thanks in advance.

**Comment by blikenoother** [comment]
@gauravnayak210 can you paste the complete code. Just need to check you have placed `app.use` at right place

**Comment by hemangmehta** [comment]
@gauravnayak210 : you just need to add below code block and it will work fine-

 req.on('end', function() {
              next();
 });

**Comment by gauravnayak210** [comment]
Thnx guys for your kind reply, Yes Hemang its working now.
