### ISSUE TITLE
To set concurrency as 1?

### ISSUE THREAD

**Issue by Hiteshm01** [Automattic/kue#668]
I want to run a job with one instance running at a time. Its inputs are already being fed via kue. Does concurrency count start with 0?
Below code allowed two instances as far as I can see from the logs
```javascript
jobs.process(process_name, 1, function (job, done) {
			debug("going to process job # " + job.id);
			var options = job.data;
			// do something here
		});
```
and it dint pick the job when I replaced concurrency with 0.

Any help? :|

**Comment by behrad** [comment]
`jobs.process(process_name, 1, function (job, done) {})`
and 
`jobs.process(process_name, function (job, done) {})`

are the same and they should both work :)

You may have been mistaken your logs when playing with Kue.

**Comment by Hiteshm01** [comment]
I will be careful this time. Thanks anyway for the help!
