### ISSUE TITLE
Job that doesn't call done() retries twice, but attempts is set to 4 (ttl = 2000)

### ISSUE THREAD

**Issue by magtutu** [Automattic/kue#669]
I would expect the following job to be attempted 4 times. In 0.9.3 it is only run twice. In 0.9.1 the job is tried four times. TTL is a super important feature.

```javascript
var kue = require('kue');
var queue = kue.createQueue();

queue.process('testjob', function(job, done){
  console.log('running testjob');
});

queue.create('testjob', {})
  .attempts(4)
  .ttl(2000)
  .save();
```

**Comment by magtutu** [comment]
Redis 2.8.17 (00000000/0) 64 bit

**Comment by behrad** [comment]
this is a serious bug, will provide a patch soon. thank you @magtutu

**Comment by magtutu** [comment]
ttl seems to work as expected in 0.9.4. Gracias!

**Comment by behrad** [comment]
:+1:
