### ISSUE TITLE
Watching for inactive jobs

### ISSUE THREAD

**Issue by oleghind** [Automattic/kue#670]
I would like to setup an alert when number of inactive jobs becomes more than N.

This looks like it:
```javascript
queue.inactiveCount( function( err, total ) { // others are activeCount, completeCount, failedCount, delayedCount
  if( total > 100000 ) {
    console.log( 'We need some back pressure here' );
  }
});
```
But seems it triggers only once instead of watching for the number of inactive jobs change, so what would be the best  event to watch for inactive jobs number growth?

**Comment by behrad** [comment]
currently there's no global stats in kue, so your app can either
1) call `.inactiveCount` periodically 
or
2) use `.enqueue` and `start` events to count queued jobs.

also even better would be a PR adding stat events to kue :)

**Comment by behrad** [comment]
This can be implemented in an extra module, like `kue-stats`
