### ISSUE TITLE
Signaling jobs of a shutdown.

### ISSUE THREAD

**Issue by alexcarruthers** [Automattic/kue#672]
I want to make long-running jobs pausable and resumable across shutdowns and there are certain parts of my jobs where i can safely pause. However there's a couple things I'm not sure about.
1. How do I signal the currently running jobs that a shutdown has been initiated so that when I get to the "safe" point, I can pause.
2. How do I put the job "back" so that on restart it will run the job again (the job itself will be responsible for getting back to where it was based on database state external to kue). 

The only thing I can think of for #2 is incrementing the max number of attempts, but I'm not sure if that would even work.

**Comment by behrad** [comment]
remember @alexcarruthers that Kue will shutdown when workers inside the process mark jobs as done or your `timeout` will mark running jobs as failed. But if you are talking about a global inter-process shutdown notification: Kue is not currently emit `shutdown` to other kue instances. This can be realized with a simple PR.

I don't know how you need this and in what way you want to mix these in, I think you don't even need pause, just shut all nodes down, and on restart your jobs will be re-attempted if they have enough attempts left (you can use a MAX_INT attempts for them).

there are so many other possibilities if you don't like this method.

**Comment by alexcarruthers** [comment]
From within a running job, can I increase the number of attempts?

**Comment by behrad** [comment]
you can update job total attempts this way:
`job.attempts( n ).update()`

**Comment by behrad** [comment]
closing this for now if you don't mind...
Can be opened any time if needed.
