### ISSUE TITLE
[question] Node crashes when redis connection dies - best practice for handling?

### ISSUE THREAD

**Issue by bradvogel** [Automattic/kue#673]
Currently if the Redis connection is lost, Node crashes. Could Kue handle this more gracefully, such as using the pattern in https://gist.github.com/FGRibreau/1761963? Or could we do this using the API?

More of a question of best practice versus a feature request. Thanks!

**Comment by behrad** [comment]
have you checked https://github.com/Automattic/kue#error-handling ?

**Comment by bradvogel** [comment]
Yes, I saw that and we're handling the 'error' event, but we're getting "Redis connection gone from end event". I believe this can be handled by listening for the 'end' event and restarting the redis connection.

Has this come up before?

**Comment by behrad** [comment]
we have a simiular issue on redis `connection gone`, can you create a PR and test this since you are seeing this error. I'll support this.

**Comment by bradvogel** [comment]
Ok, so just to clarify, we should be handling the 'end' event and then trying to reestablish the connection?

**Comment by behrad** [comment]
I think that sounds ok, please give it a shot :+1:

**Comment by behrad** [comment]
https://github.com/Automattic/kue/issues/660

**Comment by bradvogel** [comment]
Great, we'll try a few things on our (very flaky) Redis connection and let you know what we find.

**Comment by behrad** [comment]
you can really help improving this @bradvogel since I've no unstable redis connection to create this ;)

**Comment by behrad** [comment]
Upgrading to node_redis 2.3 should've improved this in 0.10

**Comment by deepakmani** [comment]
Recently, I found jobs going to inactive state on heroku-redis and found that it wasn't a code bug. After restarting the worker, it started processing the jobs using the queue.watchStuckJobs() command. It wasn't able to fix the inactive jobs automatically so I'm guessing it is because of redis connection problem,

I'm testing out node redis' retry strategy in worker.js. Is this something you have tried @bradvogel?

````
var client = redis.createClient({
    retry_strategy: function (options) {
        if (options.error.code === 'ECONNREFUSED') {
            // End reconnecting on a specific error and flush all commands with a individual error
            return new Error('The server refused the connection');
        }
        if (options.total_retry_time > 1000 * 60 * 60) {
            // End reconnecting after a specific timeout and flush all commands with a individual error
            return new Error('Retry time exhausted');
        }
        if (options.times_connected > 10) {
            // End reconnecting with built in error
            return undefined;
        }
        // reconnect after
        return Math.max(options.attempt * 100, 3000);
    }
});
````

I've also added an end event listener in the worker to check.

````

kue_obj.client.on('end', function() {

	// create reusable transporter object using the default SMTP transport
	var nodemailerMailgun = nodemailer.createTransport(mg(auth));

	nodemailerMailgun.sendMail({
	  //
	}, function (err, info) {
	  if (err) {
	    console.log('Error: ' + err);
	  }
	  else {
	    console.log('Testing Retry strategy' );
	  }
	});


});
````

**Comment by bradvogel** [comment]
@deepakmani Can't say - we moved to Bull (and not looking back!)

**Comment by deepakmani** [comment]
Got it. Thanks.

**Comment by deepakmani** [comment]
@bradvogel,
Can you recommend a stable redis provider. We are using Heroku Redis and when it goes down and comes back Kue's node-redis is unable to reconnect. We need to restart the app and worker. 
So far tried and had issues with Heroku Redis, RedisLabs, RedisTogo and Compose.io(hearsay) :)
