### ISSUE TITLE
[feature request] [discussion] add gitter chat

### ISSUE THREAD

**Issue by hellboy81** [Automattic/kue#676]
Please add gitter chat to enable live support

**Comment by behrad** [comment]
had requested this months ago from Automattic org. owner, will follow up for the gitter permission

**Comment by behrad** [comment]
have sent another email, still waiting ...

**Comment by kulbirsaini** [comment]
Can we have an IRC channel or any other alternate mode of communication?

**Comment by hellboy81** [comment]
Yes

**Comment by behrad** [comment]
Done! https://github.com/Automattic/kue/pull/702
