### ISSUE TITLE
Limit to N Jobs in X Hours 

### ISSUE THREAD

**Issue by meteorjs3000** [Automattic/kue#677]
How can the number of jobs be limited to N jobs every X hours? 

For example, if there are 10 jobs queued up, I want the worker to do only 5 jobs (1 job every minute) starting at say 12pm. Then do the remaining 5 jobs (polling at the same 1 job/min) but at 6pm. So its like limiting to 5 jobs every 6 hours.

**Comment by behrad** [comment]
Kue doesn't understand about worker's rate of processing, the only control it has its concurrency control.
You should use a rate limiter module to control producing jobs.

**Comment by meteorjs3000** [comment]
@behrad Thanks for your reply! Do you have any rate limiter module to recommend?

**Comment by behrad** [comment]
there exists plenty of them... I've tested https://github.com/AfterShip/rate-limiter since this was working in a clustered environment.

The easy way is producer side, but more realistic/meaningful would be a consumer side implementation.

**Comment by behrad** [comment]
closing this for now... if you don't mind

**Comment by tomblanchard** [comment]
@behrad @meteorjs3000 Could anyone please help me out with this? I've got 15k jobs runnng with `removeOnComplete(true)` and it maxes out my redis client 50MB memory limit half way through.

I'm thinking of implementing a rate limiter which would limit 100 jobs per hour or something of that nature, I've looked through a bunch of different Node rate limiter modules, but can't quite figure out how to use one in conjunction with Kue.

Any help would be appreciated.
