### ISSUE TITLE
TTL take into account updates

### ISSUE THREAD

**Issue by btmdave** [Automattic/kue#679]
When setting TTL, will this take into account updates being made within the job? 

For example, if the TTL is set to 10 seconds, will it automatically fail it or if data is being written, will it reset the clock?

Also, would there be a way to set a TTL on completed jobs? So jobs that are completed after period of time can be cleaned out.

**Comment by behrad** [comment]
TTL start ticking when your job gets into `active` queue (=starts being processed by your worker code) and nothing resets it. I think this is the correct semantics for `staying in active` ttl.
What you propose means `(last) access in active` ttl and is something different.


> Also, would there be a way to set a TTL on completed jobs? So jobs that are completed after period of time can be cleaned out

TTL doesn't clean jobs, it simply fails them. You can either set `.removeOnComplete` to clean them immediately or use a watchdog process to clean them, you can find a sample code in issues. it is less than 10 lines code.

**Comment by btmdave** [comment]
Got it, thanks for the explanation.
