### ISSUE TITLE
After max concurrency is reached, jobs stop being processed

### ISSUE THREAD

**Issue by btmdave** [Automattic/kue#680]
Any ideas why after the max concurrency setting for a specific job is reached, it seems to no longer accept new jobs, even after it's gone down.  For example, if set to 20, it'll process 20, then start to complete some, inactive jobs stay inactive and don't automatically start processing.

**Comment by behrad** [comment]
if your claim was true, then all Kue users would stop using it since this would be critical bug :)
Please post a sample code that can regenerate the problem of your case.

**Comment by btmdave** [comment]
Yeah..... I can't seem to reproduce it, I'm thinking maybe it could have been related to high CPU load.  If it occurs again, I'll dig around a little more to see if I can find more info.  I'll close this issue out, thank you.
