### ISSUE TITLE
Kue incorrectly grabs both username and password in Redis URL

### ISSUE THREAD

**Issue by openjck** [Automattic/kue#681]
The documentation [indicates](https://www.npmjs.com/package/kue#redis-connection-settings) that a connection can be created with a Redis URL, like this:

```js
var q = kue.createQueue({
  redis: 'redis://example.com:1234?redis_option=value&redis_option=value'
});
```

A URL formatted like that would work, but the `REDIS_URL` provided by the [Heroku Redis](https://elements.heroku.com/addons/heroku-redis) add-on includes a username, like this:

```
redis://h:examplepass@sub.example.com:111
```

The password is `examplepass`, but Kue incorrectly determines that the password is `h:examplepass`. This is because Kue [grabs the entire auth property of the URL](https://github.com/Automattic/kue/blob/master/lib/redis.js#L35), which includes both username and password. When a username is provided, Kue should only grab the password.

**Comment by behrad** [comment]
thank you @openjck
