### ISSUE TITLE
WARNING: Upgrading from 0.8 to 0.9 causes all delayed jobs to fire

### ISSUE THREAD

**Issue by evanhuang8** [Automattic/kue#687]
When I upgrade the kue from 0.8 to 0.9, all the existing jobs in the queue that has an ETA is processed immediately - is this the expected behavior due to job incompatibility? If so, there should be a warning in the upgrade guide

**Comment by behrad** [comment]
I don't remember If I tested this... but you can check if jobs are incompatible... (don't think so) however think a similar issue was reported then...
Can you resolve this @evanhuang8 ?

**Comment by evanhuang8** [comment]
I looked at the code and yeah it seems that the job structure is incompatible, since the in 0.9 jobs use "promote_at" to deal with delays, which the old jobs don't have, therefore the worker will think that the job is essentially supposed to be execute immediately.

This should be marked explicitly in the upgrade guide.

**Comment by behrad** [comment]
We are on 0.10 now.
