### ISSUE TITLE
Wipe out queue?

### ISSUE THREAD

**Issue by olalonde** [Automattic/kue#689]
Is there a method to completely wipe out the queue data from Redis? That would be helpful for testing. I suppose I could do it with redis directly but I'm not too familiar with the commands. (I know there's a test mode but this would be for integration testing).

**Comment by btmdave** [comment]
It's pretty simple with `redis-cli`, you can delete all data in redis by using `redis-cli flushall` or assuming you're using the default prefix of `q`, you could do

 `redis-cli KEYS "q:*" | xargs redis-cli DEL`  to delete only data specific to kue.

**Comment by olalonde** [comment]
Ok thanks. Going to close this as I gave up on kue after realising it wasn't a FIFO queue :/
