### ISSUE TITLE
Redis connection gone from end event. node_reis 0.12.1

### ISSUE THREAD

**Issue by liujb** [Automattic/kue#692]
When I connect to the My localhost is ok ,
But not for the production dev. how to resolve this problem.

**Comment by behrad** [comment]
Are you deploying using a container? Some reported issues docker related... (you can search issues)
If not, that can be caused by a poor connection, or something that's making redis connection forced to close...

**Comment by blacksonic** [comment]
It happens also on cloud infrastructures...it is common that a connection is closed after a day.

**Comment by behrad** [comment]
We should first decide if this is a redis driver module task or the higher level library one?
Should be reported to `node_redis` or `ioredis` so that they improve? Or should we handle this?

I'm not facing this problem so can't write and test an improvement code, would welcome if you provide a tested PR in your environment

**Comment by blacksonic** [comment]
redis maybe passed in as a constructor argument to kue and redis handling moved outside the library

**Comment by behrad** [comment]
currently kue supports a connectionFactoryMethod in the constructor, thats because Kue needs to create connections on demand... So you can't provide an already stablished connection for it (if you meant that)

**Comment by blacksonic** [comment]
why is it necessary to have multiple connections?

**Comment by behrad** [comment]
one is the global internal events subscriber connection, 
second is the BLPOP connection per worker for job picking...

**Comment by behrad** [comment]
You can test with Kue 0.10, which upgraded to node_redis 2.3
