### ISSUE TITLE
Awful sorting.

### ISSUE THREAD

**Issue by alexcarruthers** [Automattic/kue#693]
Sorting the jobs doesn't work well. looking at my list of completed jobs sorted by id, the order is 1, 10, 100, 1000, 10000, 10001, 10002, 10003, etc... Looking into it seems to be because of redis interpreting the scores of the sorted sets (ie the id) as strings not integers. It makes, for example, https://github.com/Automattic/kue#job-cleanup have undefined behaviour as it's not truly in order.

**Comment by misterjt** [comment]
I have the same problem. Makes it hard to do progress.

Progress goes  10 %. Index  1  of  10 .
Progress goes  60 %. Index  6  of  10 .
Progress goes  70 %. Index  7  of  10 .
Progress goes  80 %. Index  8  of  10 .
Progress goes  90 %. Index  9  of  10 .
Progress goes  100 %. Index  10  of  10 .
Progress goes  20 %. Index  2  of  10 .
Progress goes  30 %. Index  3  of  10 .
Progress goes  40 %. Index  4  of  10 .
Progress goes  50 %. Index  5  of  10 .

Indexes was added sequentially.

**Comment by behrad** [comment]
Closing this in fever of duplication. please follow up in old issues for the topic.
