### ISSUE TITLE
TTL on update (progress) vs complete

### ISSUE THREAD

**Issue by nyurik** [Automattic/kue#694]
It seems setting TTL on a long running job that constantly updates its progress TTL-expire fails before the job completes, even though the progress update has happened much more recently than TTL.  Does TTL only look at the job completion? I think progress update should be a good-enough for TTL monitoring.

**Comment by behrad** [comment]
TTL currently looks at job start time @nyurik 
I should check the code if update time can improve the semantics of this, nice point :)
