### ISSUE TITLE
TTL failure does not trigger .on("failed",...) event

### ISSUE THREAD

**Issue by yan7109** [Automattic/kue#695]
I have a fairly simple excerpt below (using 0.9.4):

```
var job = queue.create('test_job', {title: 'test_job1'}).ttl(5000).save().removeOnComplete(true).on("complete", function(){
console.log("success");
}).on("failed", function(){
console.log("failed");
});
```

For some reason, after 5 seconds, even though express shows the job as TTL failed, the console never prints "failed". It would always proceed until completion. Any ideas why? 

Thanks!

**Comment by behrad** [comment]
in above code you are not using a `queue.process`, so queued job never gets in active.
TTL feature is activated on active jobs
