### ISSUE TITLE
Redis connection gone from end event. (error)

### ISSUE THREAD

**Issue by markthethomas** [Automattic/kue#696]
I think this may have come up before, but I've been experiencing the below error using latest stable kue with redis 2.8.1. I seem to get the error every 10 minutes or so when we're running our node app in a staging docker container (debian:jessie is base image). Not sure what to make of the timing of it. 

I can post more code if/when helpful, but it's a pretty straightforward use of kue and the error comes up even when the staging container is idle and not getting hit w/ any requests that would make use of kue. 

I've (re)opened a similar issue on node-redis [#676](https://github.com/NodeRedis/node_redis/issues/676#issuecomment-132732252), since that's where the problem seems like it might be coming from.

Thanks!

````
Error: Redis connection gone from end event.
    at RedisClient.flush_and_error (/var/www/app/current/node_modules/redis/index.js:149:13)
    at RedisClient.connection_gone (/var/www/app/current/node_modules/redis/index.js:486:10)
    at Socket.<anonymous> (/var/www/app/current/node_modules/redis/index.js:114:14)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback [as _tickCallback] (node.js:381:11)
````

**Comment by maxfrigge** [comment]
I am getting the exact same error with redis 2.8.21 hosted on compose.io and kue 0.9.3.

For what it matters.. the application is running inside a docker container too.

**Comment by markthethomas** [comment]
Yeah, that's exactly my setup. Do you get it every 10 minutes or so?

Mark

@markthethomas everywhere

**Comment by maxfrigge** [comment]
I spin up the container .. it works for s while and then stops working forever until I restart the container/kue. Not sure about the 10 minutes, but it doesn't work for long.

I have found a [related issue on stackoverflow](http://stackoverflow.com/questions/11429020/redis-connection-gone-from-close-event)

Apparently there is an option `socket_keepalive` in `node-redis >= 0.11.0`. 
Kue however uses `node-redis-warlock` which doesn't seem to have this option.

An alternative would be to add a timer that pings the server to keep the connection going :-/

Is there a way to access the redis client kue uses?

**Comment by maxfrigge** [comment]
Sorry.. I have to correct myself. 

Kue does use node-redis 0.12.0 so you should be able to pass `socket_keepalive=true` along with your redis options.

I am testing it right now and will report back if it fails again.

**Comment by markthethomas** [comment]
Doesn't this default to true? https://github.com/NodeRedis/node_redis#overloading

**Comment by maxfrigge** [comment]
.. you are absolutely right. Didn't check the default setting. 

Guess it's about time to ditch kue.

**Comment by markthethomas** [comment]
I haven't seen this in a while on my end since enabling the `no_ready_check` flag -- has anyone else?

**Comment by behrad** [comment]
You can check 0.10 based on latest node_redis with improved connection handling.
