### ISSUE TITLE
Job is invalid

### ISSUE THREAD

**Issue by btmdave** [Automattic/kue#700]
Any idea what causes a job to be considered invalid?  We have quite a few failed jobs, with this type of trace.

Error: job \"180149\" is invalid\n    at /var/www/app/server/node_modules/kue/lib/queue/job.js:173:17\n    at bound (domain.js:254:14)\n    at runBound (domain.js:267:12)\n    at try_callback (/var/www/app/server/node_modules/redis/index.js:592:9)\n    at RedisClient.return_reply (/var/www/app/server/node_modules/redis/index.js:685:13)\n    at HiredisReplyParser.<anonymous> (/var/www/app/server/node_modules/redis/index.js:321:14)\n    at HiredisReplyParser.emit (events.js:107:17)\n    at HiredisReplyParser.execute (/var/www/app/server/node_modules/redis/lib/parser/hiredis.js:43:18)\n    at RedisClient.on_data (/var/www/app/server/node_modules/redis/index.js:547:27)\n    at Socket.<anonymous> (/var/www/app/server/node_modules/redis/index.js:102:14)\n    at Socket.emit (events.js:107:17)\n    at readableAddChunk (_stream_readable.js:163:16)\n    at Readable.push (_stream_readable.js:126:10)\n    at TCP.onread (net.js:538:20)

**Comment by btmdave** [comment]
Seems to be if hash.type is undefined, so I guess what would cause this?  It's being processed by the correct job type but then immediately failing, the data is showing empty and the type is undefined.

**Comment by btmdave** [comment]
After further investigation, it looks like a job is trying to call done on a different job.

For Job ID `225473` the error is `Error: job \"223688\" is invalid`

**Comment by behrad** [comment]
these ids remaining in state ZSETs should be all due to non-transactional job state changes in current Kue versions.
starting 1.0.0 I will fix these kind of issues.

**Comment by behrad** [comment]
This should have been fixed by a workaround patch in 0.10

**Comment by expresstechsoftwares** [comment]
@behrad I'm using KUE 0.11.6 but still facing this issue.
