### ISSUE TITLE
Does kue fail after a few million tasks ?

### ISSUE THREAD

**Issue by AaronO** [Automattic/kue#716]
Every time we reach about ~10,000,000 tasks, `kue` / `redis` seems to get stuck. It can add new tasks to `redis` but `kue` stops consuming tasks so they just pile up ...

I was wondering if anyone else has experienced this issue with `kue` in production and has an idea why `kue` would fail ?

**Comment by behrad** [comment]
I've a system processing around `500M < X < 1Billion`  jobs now, processing 2M jobs/day.
If you search issues you find issues with current version on different environments => you should properly gaurd your worker's process method so that node.js process crashes, uncaught exceptions don't  take up job concurrency over time (ttl can be used for this also)

Please let me know details if the above didn't help you and you have an specific problem using Kue.

**Comment by AaronO** [comment]
We process between 100-500k jobs/day.

Each task is isolated in it's own `node.js` `domain` so uncaught exceptions are handled and they are wrapped correctly in promises. We also call `kue.shutdown` on `SIGTERM`/`SIGINT` and `on('uncaughtException'`. I'm not sure what we could do better to cleanup, any ideas ?

Right now for example we have 0 tasks in active and ~25k in pending ... And kue isn't moving any tasks from `pending` to `active` even though there are 10 healthy `worker` processes running.

I would love to get your input, since you use `kue` at a larger scale than most that I've seen, but to date we've had a lot of issues with `kue` and it's rather frustrating

**Comment by behrad** [comment]
> Right now for example we have 0 tasks in active and ~25k in pending ... And kue isn't moving any tasks from pending to active

So this shouldn't be a leaked worker issue, Are you calling `watchStuckJobs()`? What version of Redis are you on? Is that hosted? or local network?



> there are 10 healthy worker processes running

If healthy, node process restarts should not help starting active jobs in your case.

**Comment by AaronO** [comment]
We don't call `watchStuckJobs()`. We are running `redis`@`2.8.12` on another remote server.

**Comment by AaronO** [comment]
Actually we do call `watchStuckJobs`. (But not in each `worker` but in a single `clock` process that connects to the same `redis` DB).

**Comment by behrad** [comment]
> there are 10 healthy worker processes running
> If healthy, node process restarts should not help starting active jobs in your case.

Does restarting workers solve this?

> We are running redis@2.8.12 on another remote server.

Are you experiencing poor connection/redis hiccups?

**Comment by AaronO** [comment]
Restarting workers does not solve it. They execute some tasks but then stop. Besides that `redis` works perfectly fine (adding new tasks work).

I've been debugging and the issue seems to be with `Worker.getJob()`. My logs seem to indicate that the call to `blpop` never resolves. (Which obviously blocks everything). (By never resolves I mean that the callback doesn't get called).

**Comment by behrad** [comment]
please verify that the list being BLPOPed contains items.. ( for each job on your inactive, you should have a single item (=1) in it's corresponding list. Actually what watchStuckJob does is always checking if that list is sync with inactive ZSET (containing enough items to be BLPOPed)
if your issue is the helper list being emptied while you have jobs in inactive ZSET, I wonder why watchStuckJobs isn't working!!!

**Comment by AaronO** [comment]
That's just of our task types. But as you can see it is not empty:

```
LLEN q:build:jobs
(integer) 12614
```

**Comment by behrad** [comment]
then shouldn't be BLPOP stuck there...!

**Comment by AaronO** [comment]
@behrad That's what I don't understand, the redis docs say `BLPOP` only blocks if the list is empty. But I can assure you it blocks.

I added some logs to `kue`: https://github.com/GitbookIO/kue/blob/master/lib/queue/worker.js#L293-L323

And here's what we see in our logs:

```
Sep 24 22:22:57 gitbook-com app/worker.7:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:22:58 gitbook-com app/worker.2:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:22:58 gitbook-com app/worker.2:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:22:58 gitbook-com app/worker.9:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:22:58 gitbook-com app/worker.9:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:02 gitbook-com app/worker.9:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:02 gitbook-com app/worker.9:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:02 gitbook-com app/worker.8:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:02 gitbook-com app/worker.8:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:02 gitbook-com app/worker.9:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:02 gitbook-com app/worker.9:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:05 gitbook-com app/worker.9:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:05 gitbook-com app/worker.9:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:05 gitbook-com app/worker.4:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:05 gitbook-com app/worker.4:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:09 gitbook-com app/worker.9:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:09 gitbook-com app/worker.9:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:10 gitbook-com app/worker.2:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:10 gitbook-com app/worker.2:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:10 gitbook-com app/worker.9:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:10 gitbook-com app/worker.9:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:10 gitbook-com app/worker.9:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:10 gitbook-com app/worker.9:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:17 gitbook-com app/worker.4:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:17 gitbook-com app/worker.4:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:19 gitbook-com app/worker.5:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:19 gitbook-com app/worker.5:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:21 gitbook-com app/worker.10:  !! Kue Worker: getJob: Calling blpop 
Sep 24 22:23:21 gitbook-com app/worker.10:  !! Kue Worker: getJob: blpop key is: q:build:jobs 
Sep 24 22:23:22 gitbook-com app/worker.6:  !! Kue Worker: getJob: Calling blpop 
```

If calling `blpop` worked, we should see `calling zpop` or `blpop error` logged.

And if I check in `redis`, I see that the list isn't empty:

```
LLEN q:build:jobs
(integer) 13111
```

**Comment by behrad** [comment]
Can you confirm the response from executing the BLPOP command from redis-cli ?

as a side note: Are you also using TTL ?

**Comment by AaronO** [comment]
Yep, I just tried running `BLPOP` from `redis-cli` and it works:

```
BLPOP q:build:jobs 0
1) "q:build:jobs"
2) "1"
```

There must be some error with the `redis` client (our redis client is `0.12.1`)

We don't use `TTL`.

**Comment by AaronO** [comment]
What's even stranger ... Is that calling `blpop` from the `redis` client (locally) using the same version and host works.

Here's the test code:

```js
var redis = require('redis');
var log = console.log.bind(console);

var opts = {
    'port': 17327,
    'host': '{HOST}',
    'auth': '{PASS}',
    'options': {
        'no_ready_check': true
    }
};

var client = redis.createClient(opts.port, opts.host, opts.options);

client.auth(opts.auth, function(err) {
    log('Auth err:', err);

    client.blpop('q:build:jobs', 0, log);
});
```

It outputs:

```
❯ node ./t.js
Auth err: null
null [ 'q:build:jobs', '1' ]
```

**Comment by behrad** [comment]
Did you searched `node_redis` issues to check for any problems on your specific redis version already reported !?
Your problem is strange! But you can try upgrading to `node_redis` 1 and test with the latest version. I haven't checked yet if you'll need an API refactor/change to upgrade node_redis.

**Comment by behrad** [comment]
> What's even stranger ... Is that calling blpop from the redis client (locally) using the same version and host works

then it can be a connection problem... (keepalive issue?) You can read this https://github.com/Automattic/kue/issues/696

I would test with latest node_redis if I were you...

**Comment by AaronO** [comment]
It really is strange ... I'm going to try updating `node_redis`.

We already used the `no_ready_check` option as recommended in: https://github.com/Automattic/kue/issues/696#issuecomment-142992317

I'll try updating the client and let you know if that works. But this is definitely a strange issue, any ideas if `kue` could possibly be corrupting the client or doing something that would block `blpop` from going through ?

**Comment by AaronO** [comment]
I updated `node_redis` to `2.0.1` (their latest), and the bug is still there ...

**Comment by behrad** [comment]
> any ideas if kue could possibly be corrupting the client or doing something that would block blpop from going through ?

No! thats a simple `client.blpop` call...

Can you provide me a simple code which re-produces this case?

**Comment by AaronO** [comment]
It seems like that if I change the `blpop` timeout from `0` to `1` it works. Let me rollback and ensure that it blocks.

**Comment by AaronO** [comment]
@behrad Actually that's just stupid, sorry ...

**Comment by behrad** [comment]
!????

**Comment by AaronO** [comment]
@behrad Sorry, I've been banging my head on this for a few hours, I guess I'm tired.

Changing the timeout from `0` to `1` is nonsensical.

The `blpop` calls would go through, but then it would fail on `zpop`.

**Comment by behrad** [comment]
setting a sample timeout may help you diagnose the issue better. If it fails on zpop, then there actually is no job on that jobs ZSET !!!

The data you providing here are in contradiction !

**Comment by AaronO** [comment]
@behrad But at least that proves that the command is going through, and the connection/transport isn't the problem ... Which makes this more confusing

**Comment by AaronO** [comment]
@behrad I've found the issue: https://github.com/Automattic/kue/blame/master/lib/queue/worker.js#L267

The `blpop` client is created using `redis.createClient()`, which breaks `kue` users with custom redis clients ...

This is why we're getting conflicting data, I inserted a `llen` call that uses `self.client` before `blpop` that returns the correct result, so I'm pretty sure this is the issue.

**Comment by behrad** [comment]
`redis.createClient()` is actually using the same provided options when you called `createQueue`

I'm not sure I got you point!

**Comment by AaronO** [comment]
We're passing a pre connected `redis` connection rather than a string.

So it can use that client, but it can't create new ones if you pass an existing connection.

I started looking into using a `string` to pass our connection info, but `createClientFactory` appears to have an auth related race condition: https://github.com/Automattic/kue/blob/master/lib/redis.js#L86

**Comment by behrad** [comment]
You'd better telling me about the specific redis connection method you are using... Sure this should be re-createable for Kue.



> I started looking into using a string to pass our connection info, but createClientFactory appears to have an auth related race condition: https://github.com/Automattic/kue/blob/master/lib/redis.js#L86

That is how node_redis docs says to initialize a connection.

**Comment by behrad** [comment]
closing this @AaronO

**Comment by AaronO** [comment]
@behrad I'm giving up on this too. I know it sounds totally crazy, and the data seems contradictory but it's exactly what we're seeing in production ...

The `blpop` blocks for sure, why I still have no real idea, it must be some kind of client setup error or a race condition.

It worked in production up until earlier today (and started failing for no apparent reason).

I'm going to sleep on this, one of my colleagues wrote an a drop-in replacement that uses `mongo` instead of `kue` so we're going to use that in the meantime.

Anyway sorry for taking up your time and the confusion, I understand that this sounds strange to you, it does to us...
