### ISSUE TITLE
release notes for 0.9.4, 0.9.5

### ISSUE THREAD

**Issue by davisford** [Automattic/kue#721]
Hi, npmjs lists the latest release as `0.9.5`, but the [releases page](https://github.com/Automattic/kue/releases) has only `0.9.3`.  I see the url changed from LearnBoost to Automattic somewhere down the line -- could that be the issue?

How can I find out what changed in the last two releases?

**Comment by behrad** [comment]
https://github.com/Automattic/kue/blob/master/History.md

haven't tagged them yet

**Comment by davisford** [comment]
ah, thanks @behrad
