### ISSUE TITLE
Unable to queue jobs, unstable redis connection

### ISSUE THREAD

**Issue by tsturzl** [Automattic/kue#723]
Previously I had seen stuck jobs, due to an unstable redis  connection. Though I find it odd that my redis connections I use for cache don't share this issue. So I'm not completely certain if that is the issue. However, I'm running into an issue where my API is unable to create jobs. Basically what I do is I create a document in mongodb, then create multiple jobs passing that ID to other instances to replicate that document with changes based on a zip code and a given radius.

I had added a global error handler to just restart the process in the event that redis or kue throw an error via the event emitter `queue.on('error', function(err){...})`. So hopefully this will give me some more insight as to what's going on.

Why would this happen however? Shouldn't there be an exception thrown when I try to create a job and there is no connection to create this job on redis? Or is this emitting the error through the queue object? This seems like strange error handling.

**Comment by behrad** [comment]
I'm not sure, if I'm understanding you quite right,
You can check for `.save` errors in it's callback function.

**Comment by behrad** [comment]
please update and check Kue 0.10 for improvements on node_redis 2.3
