### ISSUE TITLE
Process jobs in specific interval time indefinitely

### ISSUE THREAD

**Issue by kororo** [Automattic/kue#730]
Hi Guys,

I looked around the features in Kue, it seems missing a feature that I need. I may be wrong but if you have a way I look after please do let me know.

What I would like to do is have a schedule task to run in specific interval (lets say 10 seconds) indefinitely. I added 3 jobs to run specific task "do-something".

-- queue "do-something" --
[HEAD]     -->     [job:name:1]     -->     [job:name:2]     -->     [job:name:3]     -->     [TAIL]

-- queue "do-something" after 1st process --
[HEAD]     -->     [job:name:2]     -->     [job:name:3]     -->     [job:name:1]     -->     [TAIL]

-- queue "do-something" after 2nd process --
[HEAD]     -->     [job:name:3]     -->     [job:name:1]     -->     [job:name:2]     -->     [TAIL]

and so on...

What I tried to do is to process job, and mark it as delayed 1 second and put back into queue to the end list. It is not working, it gives me the only first job. From my observation, this is because the queue.process will get all job based on the "ready to be executed" state in "id" ASC.

```
var queue = kue.createQueue();
queue.create("do-something", {"name": 1}).delay(1000).save();
queue.create("do-something", {"name": 2}).delay(1000).save();
queue.create("do-something", {"name": 3}).delay(1000).save();

// set the KUE job
queue.process('do-something', 1, function (job, context, done)
{
  console.log(job.data.name);
  job.delay(1000).delayed().save();

  // dont call done
  // done();
});
```

-- queue "do-something" --
[HEAD]     -->     [job:name:1]     -->     [job:name:2]     -->     [job:name:3]     -->     [TAIL]

-- queue "do-something" after 1st process --
[HEAD]     -->     [job:name:1]     -->     [job:name:2]     -->     [job:name:3]     -->     [TAIL]

-- queue "do-something" after 2nd process --
[HEAD]     -->     [job:name:1]     -->     [job:name:2]     -->     [job:name:3]     -->     [TAIL]

So another approach is to mark the job as done and re-create them.

```
var queue = kue.createQueue();
queue.create("do-something", {"name": 1}).delay(1000).save();
queue.create("do-something", {"name": 2}).delay(1000).save();
queue.create("do-something", {"name": 3}).delay(1000).save();

// set the KUE job
queue.process('do-something', 1, function (job, context, done)
{
  console.log(job.data.name);
  queue.create(job.type, job.data).delay(job.delay()).save();
  done();
});
```

It works but it would be great if there is no necessary to always recreate the job. So I still can have the events, logs, progress data. Any inputs will be appreciated.

Thanks

**Comment by behrad** [comment]
There's been multiple requests for a job re-scheduling, or recurring feature. We can discuss about letting Kue to expose/implement a way of simply repeating a job (not with retries, they are something else) if that is not adding conflicts to the core library.
However I think best approach would be another npm module implementing this over kue with creating new jobs for each iteration of the task.

**Comment by kororo** [comment]
Hi behrad,

It is true, I dont want to get the kue become tools that is derail from the initial goals.
But is it reasonable to rework the "get jobs" logic to get first job based on the "date processed ASC" rather than "job ID ASC"? (Note: Sorry I forgot the exact code that I remembered last time, I can have a look if necessary for the discussion)

By the way, what was the suggestion on the approach you mentioned?

Thanks

**Comment by behrad** [comment]
> But is it reasonable to rework the "get jobs" logic to get first job based on the "date processed ASC" rather than "job ID ASC"?

this has been filed as a bug in issues and will be fixed for sure @kororo

**Comment by kororo** [comment]
Hi behrad,

Thanks for the clarification. Good stuffs
