### ISSUE TITLE
Question: What does queue.processing actually does?

### ISSUE THREAD

**Issue by IvanMMM** [Automattic/kue#735]
It's a newbie questions, but I can't find direct answers anywhere.
How queue.process actually works? 

Should I call it one time for specific job type or should I call it each time for each job in list?
What will happen after job list is empty?
Should I call new queue.process after new job was added to empty list with working queue.process?
Will "Processing Concurrency" start working without waiting for 20 mails to be in job list or it will be waiting for emails?
Thank you.

**Comment by behrad** [comment]
Sorry for late response.

> How queue.process actually works?

Uses BLPOP to wait for new items and then a ZPOP to pop the item.

> Should I call it one time for specific job type or should I call it each time for each job in list?

Once

> What will happen after job list is empty?

That method will be blocked until new items arrive

> Should I call new queue.process after new job was added to empty list with working queue.process?

After or Before makes to difference. Jobs are persisted and waiting inactive worker processes them.

> Will "Processing Concurrency" start working without waiting for 20 mails to be in job list or it will be waiting for emails?

Concurrency makes active jobs in hand. i.e. when 20 jobs are being processed, no more job gets inside process until one gets done.
