### ISSUE TITLE
Is there an official way to secure the REST API

### ISSUE THREAD

**Issue by godfroidt** [Automattic/kue#738]
Hi,

is there an official way to secure the REST API before I start on something on my own?
I am looking at something like API token or bearer authentication with IP whitelisting.
Any pointers, ideas?

Thanks
Thierry

**Comment by behrad** [comment]
REST api is currently a very basic express app, you can inject your own security into it.
I prefer a reusable plug-in like npm module which can be added on top of Kue :)

**Comment by godfroidt** [comment]
Ok, thanks,
I will look on how to do that.
