### ISSUE TITLE
How to handle workers vs web containers

### ISSUE THREAD

**Issue by KeKs0r** [Automattic/kue#744]
Hi,

I have a single app that I deploy in 2 ways, once as normal web container that handles user requests and the other one (more memory) as workers.

In the old version of Kue I would just not call promote on the web containers and then only call that on the worker. (not even sure if that worked)

Since I need kue on both, the web containers  (for creating jobs) and on the workers, but I don't know how to prevent my web containers than from doing the actual work.

Any ideas? 
(They have identical codebase, just different configuration)

**Comment by behrad** [comment]
If you are on recent versions of Kue, `.promote()` is deprecated and you don't need to call that any more

**Comment by KeKs0r** [comment]
I know, but I want on some processes where kue is also started, that those
processes DONT execute jobs.

**Comment by behrad** [comment]
just put `queue.process` in processes where you want to execute jobs.
