### ISSUE TITLE
Access Job parameter on failed event

### ISSUE THREAD

**Issue by KeKs0r** [Automattic/kue#746]
Hi,

I am setting some values before I start a job and change them when the job is done in order to make sure not running a job on the same data multiple times.

Problem is that I am not 100% sure how to reset those values on job failure. I wanted to add an `failed` event, but realized that the failed event does not have access to the jobs parameter, or does it?

My next approach was defining the handler on the instance in my process methods, which just looks wrong to me:

```javascript
        queue.process('matchdayBest', function (job, done) {
            var matchday = job.data.matchday;
            var key = 'matchday:status:' + matchday;
            job.on('failed', function(){
                redis.HSET(key, 'best', 1);
            });
            matchdayBest.process(matchday, done);
        });
```

Any ideas on how to solve this?

**Comment by behrad** [comment]
```js
queue.on( 'job failed', function( jobId, errorMsg ){
   // key = jobId + 2;
} );
```

**Comment by behrad** [comment]
You can also use, `Job.get` static method to fetch job.data in your failed listener
