### ISSUE TITLE
Multiple producers: how to gracefully shutdown producer without asking workers to stop

### ISSUE THREAD

**Issue by gebrits** [Automattic/kue#757]
Given a topology with multiple publishers, how can I safely shutdown a publisher? 

Following the [Graceful Shutdown](https://github.com/Automattic/kue#graceful-shutdown) documentation, will ask all workers to stop which is not what I want. I just want to stop the publisher. 

Is process.exit() enough, or will I have to gracefully close the underlying node connection?

**Comment by gebrits** [comment]
I believed that Graceful shutdown was inter-process. After reading https://github.com/Automattic/kue/issues/672, this doesn't seem to be the case. 

For me this works out as I want, I can just do Graceful Shutdown on a producer after it's done seeding, since a performer and workers do not occur in the same process in my setup. 

Am I understanding this correctly?

**Comment by behrad** [comment]
Graceful Shutdown is designed for workers. for job producers there's no meaning of graceful shutdown, since there's no active state between producers and redis. 
You can easily exit when all jobs are saved or your expected events fired.
