### ISSUE TITLE
flushall_q_keys option

### ISSUE THREAD

**Issue by clounie** [Automattic/kue#759]
Re: https://github.com/Automattic/kue/issues/94#issuecomment-71253108

 We could make it happen only once upon queue creation (i.e. it only gets passed to the first redis client,) or make every redis client `flushall` on init. Thoughts?

**Comment by behrad** [comment]
flushing deletes all kue keys, many can't do it in a real, production system.

**Comment by clounie** [comment]
Worth as a test option or nah?

**Comment by behrad** [comment]
I think this is very feasible and easy to run `redis-cli` and run a FLUSHDB on selected DB.
However if you want only delete Kue prefixed keys, then you should write a scalable script using may be SCAN :)

**Comment by clounie** [comment]
Gotcha, thanks!
