### ISSUE TITLE
throttle/debounce jobs?

### ISSUE THREAD

**Issue by idris** [Automattic/kue#760]
Is there a way to have a job act similarly to [`_.debounce`](https://lodash.com/docs#debounce) or [`_.throttle`](https://lodash.com/docs#throttle) such that if something tries to create the same job within, say, 5 minutes, it will not add another job?

**Comment by behrad** [comment]
No built-in function is available for this I'm afraid @idris 
You can implement one, by using lodash or async base functions on top of Kue as an external module
