### ISSUE TITLE
Clarify the attempts documentation

### ISSUE THREAD

**Issue by mansona** [Automattic/kue#767]
Hey All, 

I just want to clarify something that I can't find info in the documentation. I am trying to use the `attempts()` functionality but it doesn't seem to be working. 

here is my job: 
```queue.create("jobName", {
   section: 'profiles',
   iniciatedBy: 'cron'
}).attempts(5).save();```

I implemented a promise based timeout function before I found the `ttl()` functionality and essentially the `done()` function in the job is called with an error once the timeout is hit. When this happens the job stops instantly and doesn't re-attempt. 

Does the attempts logic only work with `ttl()` or should it be working in the scenario I describe above?

**Comment by behrad** [comment]
would you please show us your `.process` and how are you failing the job (hence expecting `attempts` to reattempt it) ?

**Comment by mansona** [comment]
thanks @behrad , as soon as I was putting together a simplified version of the process function I noticed what I was doing wrong. I have a system of jobs where some jobs create other jobs etc. and I was adding the `attempts(5)` in the wrong level of the hierarchy

**Comment by behrad** [comment]
good for you @mansona
