### ISSUE TITLE
concurrency issue

### ISSUE THREAD

**Issue by pepoviola** [Automattic/kue#772]
Hi, I'm experiencing a problem when I set up two or more workers ( processors ), only process the first job and never again take a job from the queue, leaving all others jobs in inactive queue.
If I set a single worker, working properly and all the jobs are processed.
I try to check if an error is generated, but no error is emitted, apparently this callback is never called
`client.blpop(client.getKey(self.type + ':jobs'), 0, function( err ) {` 
Also i made a network capturing and only see this between server and redis server

```
*3 
$7 
evalsha 
$40 
54b5f3c93bc373eb500cdb6e80ccca0220b89330 
$1 
0 
:0 
*3 
$7 
evalsha 
$40 
54b5f3c93bc373eb500cdb6e80ccca0220b89330
$1 
0 
:0 
*3 
$7 
evalsha 
$40 
54b5f3c93bc373eb500cdb6e80ccca0220b89330
$1 
0 
:0 
```

Any idea what could be happening?
Thx!

---

kue version: 0.10.4
redis_version: 2.8.12

**Comment by behrad** [comment]
please send me the code, so I can run it locally to debug whats happening

**Comment by pepoviola** [comment]
Hi thanks for the answer. I'm creating the queue in this way:
```
var queue = kue.createQueue( {
	redis : {
		host : host,
		port : port,
		auth : auth
	}
} );
```

Add jobs:
```
var job = queue.create( "populate", {
	jid : jid
} ).priority( "high" ).save();

job.on( "complete", function() {
	callback();
} ).on( "failed", function() {
	callback( new Error( "Failed" ) );
} );
```

And the code that run is something like this. But I'm sure that the `done` callback is called because i see the `complete` event is fired.
```
	queue.process( "populate", 2, function( job, done ) {
		var jid = job.data.jid;

		myLib.populate( jid, function( err ) {
			if( err ) console.log( err );
			done( err );
		} );
	} );
```

Thx!

**Comment by pepoviola** [comment]
Hi @behrad could you reproduce this issue? Let me know if you need more info.
Thx!

**Comment by behrad** [comment]
Sorry I hadn't time to test your code, will do this tomorrow and let you know... 

Note: this is a very basic Kue functionality to dispatch jobs to concurrent workers and this is already working. There should be problem in your own code. You can however drop `myLib.populate` and test Kue separately on that.

**Comment by peterporfy-planorama** [comment]
@pepoviola did you find something? We have a similar issue here: https://github.com/Automattic/kue/issues/815
