### ISSUE TITLE
Graceful shutdown doesn't shutdown at all

### ISSUE THREAD

**Issue by windrago** [Automattic/kue#775]
Hello,

I have followed the documentation but I don't see to be able to exit the process with a graceful shutdown.
The code in the shutdown block never gets executed. Last line does but the process does not exit.

// if both buttons are pressed, disconnect:
			if (left && right) {
				process.once('SIGTERM', function(sig) {
					kue.shutdown(5000, function(err) {
						console.log('Kue shutdown: ', err || '');
						process.exit(0);
					});
				});
				tag.disconnect();
			}

Any help is wildely appreciated.
thx

**Comment by behrad** [comment]
Is your shutdown callback getting called? (do you see 'Kue Shutdown' at console?)

**Comment by windrago** [comment]
The entire code in the process.once block doesn't get called (sorry I implicitly implied that some gets called in my previous statement) - it doesn't shuts down at all.

**Comment by behrad** [comment]
‍‍‍`process.once('SIGTERM', function(sig)` will be called when you send a SIGTERM signal to your node.js process which can be done by pressing `CTRL+C ` in the terminal which you process is running.
This is nothing to do with Kue.

**Comment by windrago** [comment]
Thank you for the explanation, now I understand how it is suppoesed to be used.
What would be the recommened way to shutdown at will (exist the process naturally and not by sig.)?

**Comment by behrad** [comment]
```js
kue.shutdown(2000, function(err) {
  console.log('Kue shutdown: ', err || '');
  //process.exit(0); you should not need this line
});
```
