### ISSUE TITLE
Enabling concurrency will make job.update() or job.save() triggers job processing twice

### ISSUE THREAD

**Issue by eugeneyu-savvi** [Automattic/kue#777]
I have the following code

```
var queue = kue.createQueue();

queue.process('myjob', 4, processMyJob);

function processMyJob(job, done) {
    console.log('processMyJob');
    // do some process
    done();
}

function testJobs() {
    var job = queue.create('myjob', { name: 'test' });
    // job.update does the same
    job.save(function jobSaved(err) {
        // do something
        job.data.jobid = job.id;
        job.save();
    });
}
testJobs()
```
This will execute `processMyJob` twice even though it only creates one job.

I need to either save / update my job id into its data field to be used later.
It works fine if no concurrency option is on.

it looks like `redis` sends the job to `getJob` twice

**Comment by eugeneyu-savvi** [comment]
well I just realised this is not in the scope of the 'update job' feature as the job did not enter process worker yet.

**Comment by behrad** [comment]
1) you can call update instead of save when updating a job
2) I can't see why you are putting job.id inside data! When you have job.data should should also have job.id
3) Is your problem cleared now? Or yet it exists?

**Comment by eugeneyu-savvi** [comment]
1) Yes you are right. but update still triggers the same
2) Well, that was one of the legacy code I had which I just need to process job.id in worker.
3) It is cleared with workaround but I think the point of the issues was `update job object before processing`

**Comment by eugeneyu-savvi** [comment]
That does not sound like a real use case. will close it
