### ISSUE TITLE
Limit number of Kue calls per second

### ISSUE THREAD

**Issue by LizzieCohaesus** [Automattic/kue#781]
I am using Kue to process a number of api calls to google analytics, I need to ensure that it is making no more than 10 calls per second or the api will refuse the calls.

Is there a way to limit the number processed per second as I could not see anything in the options for this. Otherwise is there a way for me to add failed tasks to the queue again so I ensure they are run.

**Comment by behrad** [comment]
> I need to ensure that it is making no more than 10 calls per second or the api will refuse the calls

This is what you can handle by available rate limiting or token bucket implementations in npm



> Otherwise is there a way for me to add failed tasks to the queue again so I ensure they are run

You can either use a high retry limit, or write a script to check failed queue and requeue them. If you search issues you can find sample codes.
