### ISSUE TITLE
`job dequeue` event

### ISSUE THREAD

**Issue by Trindaz** [Automattic/kue#782]
I am logging job processing times. The `job enqueue` event is pretty handy but there doesn't seem to be a corresponding `job dequeue` event. It would have been useful in my case.

Is there any place for this in kue? Or should I be able to achieve this already? I was able to return various job properties as the result of a successful job, but this didn't handle the case of failed jobs. And anyway, I wanted to log the time it took between enqueueing and dequeueing without including job processing time.

**Comment by behrad** [comment]
Checking code you can add `deqeue` event when job get's `active` in `worker.js`. Can you provide a PR?

**Comment by behrad** [comment]
Kue already has `job start` event which means job is dequeued :)
