### ISSUE TITLE
Longer Delays

### ISSUE THREAD

**Issue by j** [Automattic/kue#785]
So the documentation about delays say to pass in milliseconds and it creates times and processes up to 1000, etc, etc. Which doesn't sound too hot for a lot of delays scheduled further in the future.

Basically, can I create longer delays?

Here's my (example) use-case:

For every user that signs up, I'll create a delayed job to be processed in 30 minutes, I want to process certain things (i.e. pull updated info from 3rd party API), then re-schedule the same job for another 30 minutes later.  I'll do 30 minute intervals for the first 7 days, then I'll change the delay to, lets say, 1 full day after that.

An alternative to this type of use-case would be for every user sign up, create all the events to be processed in the future. 30 minutes from now, 1 hr, 1:30, 2:00, 2:30... (for a whole week), then switch to one a day after that for a whole week. (essentially creating around 343 scheduled future jobs for every user sign up right off the bat).

Can Kue handle a large amount of delayed queues like this?

**Comment by behrad** [comment]
No difference, you can simply do `.delay( 24 * 60 * 60 * 1000 )` for a 24h delay :)
You can also update job delay as wanted: `job.delay(...).update()`

**Comment by j** [comment]
I guess my main concern is that the delay isn't just a javascript timer and an actual persisted delay that can live through crashes, etc.

**Comment by behrad** [comment]
delay is implemented by a Redis ZSET and a promotion script which is run when a kue process is run, So there's no Javascript timer and delays will survive process restarts :)
