### ISSUE TITLE
Can't Connec to Redis after Failover

### ISSUE THREAD

**Issue by livingeek** [Automattic/kue#786]
We are using Redis Sentinel to allow Redis to fail over gracefully.  We have had it in production for a while running behind an HAProxy VIP, but we continue to have issues whenever redis sentinel failovers over to the other side.  We get the error "Caught exception: Error: Redis connection gone from end event."

Looking through the docs again I see that we can setup redis-sentinel to handle the failover of the master rather than attempting to route this through HAProxy as that appears to have some issues with the failover.  Setup a dev environment with Redis failing over without issue.  Things are fine when you start the app, but once you fail redis over we get an error that ECONNREFUSED.  

Received +switch-master message from Redis Sentinel.  Reconnecting clients.
Caught exception: Error: Redis connection to undefined failed - connect ECONNREFUSED

This is our code for the connection bits.  

var endpoints = [
  {host: '10.22.191.117', port: 26379},
  {host: '10.22.254.229', port: 26379}
];
var opts = {};
var masterName = 'mymaster';
var sentinel = Sentinel.Sentinel(endpoints);
var queue = kue.createQueue({
  redis: {
    createClientFactory: function(){
      return sentinel.createClient(masterName, opts);
    }
  }
});

This is on kue 0.10.4.  Not sure why it doesn't handle the failing over through a VIP properly, and why we get an undefined for the failover.  Verified access, and regardless of which side starts as the master same issue either way.  So it appears to be getting the master, but not getting the new master after the fact.  

Also looks like the creator of node-redis-sentinel recommends using ioredis, but only see information on using that for cluster, not for sentinel.  Is this something that is being worked in, or already available and not documented?

**Comment by livingeek** [comment]
Some additional details of our architecture that I was testing to verify.  

We are using cluster where the web UI and ingest points for creation will run on the master.  So master is generating a monitoring job for us every minute so we can verify that processing is continuing to go through.  When I do the restart I get a connection back fine from the master, but all jobs are stuck in an inactive state.  It appears that the workers that have been spun up in additional clusters are having the issue reconnecting.  

Web UI for Kue and the creation of the monitoring job are working fine.

**Comment by behrad** [comment]
Can you setup a test case @livingeek ?
