### ISSUE TITLE
When creating jobs from a stream, the last job is not created

### ISSUE THREAD

**Issue by jkrenge** [Automattic/kue#789]
I am using [fast-csv](https://github.com/C2FO/fast-csv) to iterate over a CSV file using a `stream`. For each row of the CSV file, I want to create a job in redis, for which I use [kue](https://github.com/Automattic/kue). Parsing a row is synchronous function. The whole thing looks like this:

 ```javascript
var csvStream = fastCsv(_config.csvOptions)
  .on('data', function(data) {
    var stream = this;
    stream.pause();

    var payload = parseRow(data, _config);
    console.log(payload); // the payload is always printed to the console

    var job = kue.create('csv-row', {
        payload: payload
      })
      .save(function(err) {
        if (!err) console.log('Enqueued at ' + job.id);
        else console.log('Redis error ' + JSON.stringify(err));

        stream.resume();
      });
  })
  .on('end', function() {
    callback(); // this ends my parsing
  });
```

The simple `console.log(payload);` shows for every row of my CSV file, however the job is not created. I.e., none of the outputs in the callback of `save` are being printed, and the job is not in my redis.

I assume, because it's the last row of the CSV file, the stream already emits `end` and so the last `kue.create()` cannot be executed before the process terminates?

Is there a way to halt the stream's `end` until kue is done?

*Full disclaimer:* I raised this with [fast-csv](https://github.com/C2FO/fast-csv/issues/124) and more generally on [SO](http://stackoverflow.com/questions/34464354/wait-for-callback-of-async-function-in-last-stream-ondata-event) as well.

**Comment by behrad** [comment]
I'm not sure if I got your issue right, Are you sure that `.create` is called but you won't be inside `.save` callback?

**Comment by jkrenge** [comment]
Well, to be perfectly honest, I am not sure. But the line before `.create()` with the simple console output `console.log(payload);` is always called. So basically I do see this output, but no enqueueing result for that `payload`.

**Comment by behrad** [comment]
Can you tell if you are catching an error here:

```js
kue.on( 'error', ... )
```

**Comment by jkrenge** [comment]
I have following code in the top of my app:

```javascript
var redis = require('kue');
var kue = redis.createQueue(settings.redis.connection);

kue.on('error', function(err) {
  console.log('kue error: ' + err);
});
```

But no error is shown.

**Comment by jkrenge** [comment]
Adding an additional layer of in-memory persistence by using an `async.queue()` mitigates the problem as described [here](http://stackoverflow.com/questions/34464354/wait-for-callback-of-async-function-in-last-stream-ondata-event).
