### ISSUE TITLE
Attempts surpassing max attempts on delay jobs upon failure, resulting in infinite retries. 

### ISSUE THREAD

**Issue by JperF** [Automattic/kue#797]
Issue 1:
----
I am using Kue as a scheduling mechanism and we have a large number of delayed processes that rely on kue. Recently, within the last 2 weeks, we have experiences some unusually behavior from kue. 

The jobs that were scheduled about 7-24 weeks ago to be fired off now are entering a sort of infinite loop on failure. The jobs have a maximum attempt value of 1 but the job keeps retrying infinitely. This issue appears to only be happening with delayed jobs that failed. I originally thought that we were passing a incorrect error to the job process callback similar to issue #392 but I wasn't able to manually create the issue in testing. (We were either passing back a `string` or `Error` object anyways.)

Issue 2:
----
`Note: This may or may not be related to the initial problem.`
Currently in our production environment we are having single jobs run multiple times when there are no failures. This again happens only with jobs that are initially delayed. According to our logs, which may or may not be accurate, the first job instance starts running then the second one starts before the first is marked as complete. In our system we have console output when a job is `promoted`, `enqueued`, `completed`, `failed`, and had a `failed attempt`. I thought this issue may of been related to #375 because in our production environment we have multiple node instance for load balancing reasons, but we took one of the instances away and we were still experiencing the same problem. However, these jobs were created when there were multiple node instances. An example output from our logs looks a follows:

````javascript
2016-01-03T18:37:46.986Z - [scheduler] [Kue Event - promotion] JobId: 23010...
2016-01-03T18:37:46.988Z - [scheduler] [Kue Event - enqueue] JobId: 23010...
2016-01-03T18:37:47.952Z - [scheduler] [Kue Event - promotion] JobId: 23010...
2016-01-03T18:37:47.953Z - [scheduler] [Kue Event - enqueue] JobId: 23010...
2016-01-03T18:37:48.020Z - [scheduler] Ran job: 23010...
2016-01-03T18:37:48.038Z - [scheduler] [Kue Event - complete] JobId: 23010...
2016-01-03T18:37:48.448Z - [scheduler] Ran job: 23010...
2016-01-03T18:37:48.456Z - [scheduler] [Kue Event - complete] JobId 23010...
````

The `Ran Job` console log is printed out during the `process` function. 
All these messages come from the same host program as well. 

Unfortunately I don't have the redis data on this job because we remove jobs upon completion. 

Stats
----
Currently we have roughly 4.3k delayed jobs in our system. 

Running Redis: `2.8.4`
Running Kue Version: `0.10.4`

Here are some example jobs from redis output directly:
`Note: I have taken out the data portion of this job since it contains some sensitive information. `

`Attempts = 134358`
`Max Attempts = 1`

````javascript
127.0.0.1:6381> hgetall q:job:3042
 1) "started_at"
 2) "1451924030129"
 3) "max_attempts"
 4) "1"
 5) "error"
 6) "undefined"
 7) "attempts"
 8) "134358"
 9) "workerId"
10) "kue:0f110a54eb9d:70:modelFunction:1"
11) "data"
12) "dataStuff"
13) "failed_at"
14) "1451924030144"
15) "delay"
16) "10540800000"
17) "type"
18) "modelFunction"
19) "state"
20) "failed"
21) "priority"
22) "0"
23) "created_at"
24) "1441236423363"
25) "promote_at"
26) "1451777223363"
27) "updated_at"
28) "1451924030144"
````

**Comment by behrad** [comment]
I've seen the first issue and this should be a race when updating `attempts`. Strange for me! Will investigate more into it. Please let me know if you could dig in more details on it.

Second issue I'd never heard of, can be a race in job promotion script, I believe a single job is promoted twice, otherwise there's no way a single queued job gets twice in workers! I should recheck this...

**Comment by JperF** [comment]
@behrad Thanks for the quick response. 

What causes the job promotion? Calling `.process` on a given job type?

**Comment by behrad** [comment]
Job promotion is silently run by Kue at intervals: https://github.com/Automattic/kue/blob/master/lib/kue.js#L167-L203

**Comment by JperF** [comment]
@behrad 
After further investigation we deemed the second issue was caused by updating to `^0.10.4` Kue. We have since reverted back to `^0.9.3`. I think this was a reflection of upgrading to 10.0 according to this https://github.com/Automattic/kue/wiki/Upgrading-to-0.10.x. Where `MAY` meant every delayed job... do you currently have a suggestion/solution on how to properly update the delayed jobs without having to get a new redis instance, wiping out all delayed jobs, or creating and running a script to recreate each delayed job?

**Comment by behrad** [comment]
You can use these two functions to map between old plain ids and new order preserving ids:

https://github.com/Automattic/kue/blob/master/lib/redis.js#L80-L97

to compose a simple migration script.

**Comment by pcothenet** [comment]
I'm experiencing the same issue, but I did wipe the queue clean after upgrading to 0.10.x

**Comment by behrad** [comment]
you are not using TTL, right?

**Comment by behrad** [comment]
@JperF , @pcothenet  Can you please confirm this?

**Comment by JperF** [comment]
@behrad I was using the built in TTL in my application.

**Comment by behrad** [comment]
I suspect TTL, Can you test the latest?

**Comment by JperF** [comment]
@behrad 
This may take some time since I wasn't able to create it consistently locally.  @pcothenet were you able to create an adequate test for this? My only testing environment is our live application that I don't want to use as a testing environment.

**Comment by pcothenet** [comment]
@behrad I am using TTL
@JperF haven't been able to isolate, it's only happened in my prod environment so far

**Comment by JperF** [comment]
@behrad 
Your latest fix was only for the infinite retries on job failures correct?

**Comment by behrad** [comment]
> Your latest fix was only for the infinite retries on job failures correct?

yes
