### ISSUE TITLE
removeOnComplete "enough" time?

### ISSUE THREAD

**Issue by ryan-kimber** [Automattic/kue#798]
The documentation indicates that we should 'provide enough time for .remove calls on each job object to complete before your process exits, or job indexes will leak'.

Unfortunately, this doesn't give any indication of how much time enough time might be, or how the cleanup process runs. 

Is there a 'rule of thumb' we can follow for how long we should wait? 

I'm currently adding some tests on our producer/consumers and sleeping for 5 seconds after my tests have completed.

**Comment by behrad** [comment]
you can use _.after to ensure all callbacks are called before you exit @ryan-kimber
