### ISSUE TITLE
Oops jobQueue has some problem  { [Error: ERR value is not a valid float] command: 'ZADD', code: 'ERR' }

### ISSUE THREAD

**Issue by rajegit** [Automattic/kue#800]
I am getting the following error in my kue deployment 
//Error
Oops jobQueue has some problem  { [Error: ERR value is not a valid float] command: 'ZADD', code: 'ERR' }

//Caller that calls producer
..
var callProducer = require('producer.js);
..
callProducer (data, function(jobReturn){
console.log(jobReturn); // <-- this is where the error is 
});

//Producer with Callback (producer.js)
var jobCreator = function (data, callback){
..
job = jobQueue.create(...);
..
job
 .on('complete', function(result){
        callback(result); // pass the result back to callback
    })
...
}
export.modules = jobCreator;

//Worker
..
jobQueue.process('job_name', function (job, done){
..
done(null,'true'); // return value
}

**Comment by behrad** [comment]
Can you confirm `done(null,{res: 'true'}); ` resolves the issue?

**Comment by rajegit** [comment]
no behrad the error persist . I looked it more closely the error pattern is similar to error from “Function Declarations vs. Function Expressions” . I am making a wild guess .

**Comment by behrad** [comment]
I can't tell whats going wrong looking at 
```
callProducer (data, function(jobReturn){
consolelog(jobReturn); // <-- this is where the error is 
});
```
check callProducers code to see what can cause this

**Comment by rajegit** [comment]
Got it ! . The callback was getting assigned to a variable. Really appreciate your support and work :) 

Please close this issue .

**Comment by behrad** [comment]
:+1:
