### ISSUE TITLE
Jobs stuck in Delayed state - Infinite retry

### ISSUE THREAD

**Issue by pcothenet** [Automattic/kue#802]
![banners_and_alerts_and_kue](https://cloud.githubusercontent.com/assets/1460006/12302498/4f1f8a5e-b9da-11e5-9388-3928c2711f51.png)

Over the past few weeks, I've had multiple instances of jobs seemingly stuck in *Delayed* state, retrying every second, way past the max number of attempts (set to 2 here). Any idea what could be causing this and how to prevent it?

**Comment by behrad** [comment]
related to #797

**Comment by pcothenet** [comment]
Seems to be exactly the same thing. Closing this one.
