### ISSUE TITLE
Deleting an active job from the dashboard does not stop the job

### ISSUE THREAD

**Issue by alelavoie** [Automattic/kue#804]
If I delete an active job from the dashboard (with the [x] button), it seems to remove all references to the job from redis but won't stop the job process.

It might not be a "bug" but I think it is counterintuitive and can lead to problems and/or confusion. 

For example, let's says I have very long jobs and I process them 1 at a time. If I delete an active job from the dashboard, it says "0 active" while all the new jobs are put in the queue. 

![image](https://cloud.githubusercontent.com/assets/10867504/12311442/07a3307c-ba25-11e5-8011-38a838085b09.png)

All goes back to normal when the "deleted" job finishes in the background but it took me some time to understand what was happening. 

If you are not planning on adding the possibility to kill a job from the dashboard, maybe a warning saying that the job is still running would avoid the confusion ?

Thanks for your nice work btw !

**Comment by alelavoie** [comment]
The problem is not with kue. Sorry for that.

**Comment by jdrydn** [comment]
@alelavoie What was the problem?
