### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by Grandiz** [Automattic/kue#807]
Sometime i'm getting this error
Redis connection to ****.garantiadata.com:15012 failed - read ECONNRESET.
Create queue like this
```javascript
var q = kue.createQueue({
    prefix: 'q',
    redis: {
        port: process.env.KUEREDISPORT,
        host: process.env.KUEREDISHOST,
        auth: process.env.KUEREDISPWD
    }
});
```
And have about 13 workers. Could it be the problem? And is there some workaround
```javascript
q.create(name, {

}).delay(delay).removeOnComplete( true ).save(next);
```

**Comment by behrad** [comment]
I can't remember if we are handling reconnects... However latest node_redis version should empty it's command queue after reconnect automatically, and you may benefit from this if you are on latest kue version.
You can test and let us know :)
