### ISSUE TITLE
.idea in your npm published package

### ISSUE THREAD

**Issue by rom1504** [Automattic/kue#808]
I've recently noticed that git globally ignored filed are included in a npm package when publishing it and as a result some files are published by accident. See https://github.com/npm/npm/issues/5673 (and I'm working on https://github.com/rom1504/npm-safeguard)

The last version published of this package contain files in a .idea/. It doesn't seem like they contain actually private information in this case, but publishing these files by accident can lead to publishing passwords or any other private information (that would be put in webstorm run configurations for example)

**Comment by behrad** [comment]
I'll check and absolutely will fix that if so, thank you @rom1504

**Comment by kerimdzhanov** [comment]
There is also unnecessary `projectFilesBackup` and some `links.txt` file, here how it looks:
<img width="691" alt="screenshot at jan 25 06-45-53" src="https://cloud.githubusercontent.com/assets/1128317/12540219/827a0cd6-c32f-11e5-8e47-4f83ea04a6e8.png">

**Comment by behrad** [comment]
I'll remove them guys... thank you
