### ISSUE TITLE
Same completed job handled by multiple servers

### ISSUE THREAD

**Issue by pfzero** [Automattic/kue#809]
Hi,

I have an issue getting back the response from workers. I have N servers (which create jobs) and M workers per each job type. Each job is handled by a single worker, but when the worker puts the response after the processing was done, the job gets handled back by all (N) servers.

I am using the queue level events because of the drawbacks of the job events level (i.e. jobs are stored in memory until the job is completed - in this case this can take a long time, and if the node process is restarted, the reference to the job will be lost).

Is there a way to process the job response on a single server (just like the workers process the job) rather than doing it on all servers?

**Comment by behrad** [comment]
Queue events are based on redis pub/sub and so all instances will receive the same event. Local job events may suite your case better @pfzero 
Or you can implement a distributed barrier on top of redis so only one (first event) get through :)
