### ISSUE TITLE
Controlling failure attempts "on the fly"

### ISSUE THREAD

**Issue by kerimdzhanov** [Automattic/kue#810]
Hi there,

As I understand, failure attempts can be controlled only using the `Job#attempts` method, and any failed job retries _x_ times.

How about controlling that retries from a `queue.process` function? There are many error cases in processing jobs that shouldn't be retried. e.g. validation errors.

I would like to fail a job without retrying if one of the required job parameters is missing or invalid.
Or, if it's a kind of network error or database connection failure I would like to be able to retry current job.

Is there more elegant way to control the failure attempts than like this:

``` js
queue.process('email', function (job, done) {
  if (!isValidEmail(job.data.email)) {
    return done(null, { error: new Error('invalid email address') });
  }

  sendEmail(job.data, function (err) {
    if (err) { // e.g. temporary network error
      return done(err);
    }

    done();
  });
});
```

Instead, I would like to have something like:

``` js
queue.process('email', function (job, done) {
  if (!isValidEmail(job.data.email)) {
    job.finalize(); // that fails the job immediately without retrying
    return done(new Error('invalid email address'));
  }

  sendEmail(job.data, function (err) {
    if (err) { // e.g. temporary network error
      return done(err);  // without finalization, will be retried
    }

    done();
  });
});
```

Thanks in advance!

**Comment by behrad** [comment]
> There are many error cases in processing jobs that shouldn't be retried. e.g. validation errors.

I also believe adding an `abort` functionality would help and this means failing job forcefully without running normal retry logic.

How about a `job.abort` method? can you create a PR?

**Comment by kerimdzhanov** [comment]
Hi,

I'm not so good in kue's interior kitchen, but I want to help, and I'll try.

**Comment by kerimdzhanov** [comment]
`job.abort` is a good name for this purpose :+1:.

Is calling back is required after the `job.abort()` or we can simply pass an `err` to the `job.abort` without calling `done`?

Which of the following is better:

```js
  if (!isValidEmail(job.data.email)) {
    job.abort(); // fail the job immediately without retrying
    return done(new Error('invalid email address'));
  }
```

Or

```js
  if (!isValidEmail(job.data.email)) {
    return job.abort(new Error('invalid email address')); // fails the job immediately without retrying
  }
```

Or maybe both variants should work?

**Comment by behrad** [comment]
Thinking again on this, `job.abort` won't help standalone.
`done` is actually detaching job from worker... So we should solve this by calling `done(err)` not a job method, however we can mark that job to be aborted by `done(err)`:

```js
job.setAbort( true ); // Can you propose a better name for such a method?
done(new Error('critical error'));
```

**Comment by kerimdzhanov** [comment]
How about:

```js
worker.process('some-job', function (job, done) {
  // ...
  job.attempts(0); // and seems we need to `.save()` here
  done(new Error('critical error'));
});
```

Or maybe without calling any job methods, we can call `done()` giving a specific error, like:

```js
function CriticalError(message) {
  Error.captureStackTrace(this, this.constructor);
  this.name = this.constructor.name;
  this.message = message;
  this.critical = true; // this flag will indicate that the job shouldn't be retried
}

require('util').inherits(CriticalError, Error);
```

Having above, we can simply call:
```js
done(new CriticalError('missing required params'));
```

Or even easier (but lacking best practices):
```js
var err = new Error('Uhh, ohh!');
err.critical = true;
done(err);
```

**Comment by behrad** [comment]
attempts is not intended for aborting jobs and will complicate debugging aborted jobs at first glance and even not readable, however it could be the internal implementation of `.abort`:
```js
Job.prototype.abort = () => {
   return this.attempts(0).save();
}
```
Writing above code, I remembered we already have a `Job.noMoreAttempts` method, Can you check if that works?

the second approach setup is not easy and simple, requires one to create special errors... Not interested.

**Comment by kerimdzhanov** [comment]
Sorry, I can't find such method.

How about naming it `Job#suppressAttempts();`?

**Comment by behrad** [comment]
> Sorry, I can't find such method.

Oh, pordon me, it was a PR actually #666 


> How about naming it Job#suppressAttempts();?

Why not :+1:

**Comment by behrad** [comment]
And please add a test case inside your PR @kerimdzhanov

**Comment by kerimdzhanov** [comment]
Yes, sure.

Would be nice to have a _CONTRIBUTING_ section in this repo :+1:

**Comment by behrad** [comment]
> Would be nice to have a CONTRIBUTING section in this repo

I'd be great if you can inject one for a starter :heart_eyes:
