### ISSUE TITLE
Question: Can I pause a job while it's running in a try/catch

### ISSUE THREAD

**Issue by bartonhammond** [Automattic/kue#819]
My job is accessing a rate limited service.  When the limit is exceeded the code throws an exception which can be caught in the worker.  The error contains the time when the rate limit will reset - I want to restart the job at that time.

Is this the correct way to handle this:

```
 _queue.process('cachejob', 1, function(job, ctx, done) {
    let buildCache = new BuildCache();
    
    buildCache.processJob(job)
      .then(() => {
        done();
      }).catch((err) => {
        debugger;
        if (err
            && err.status
            && err.status === 403) {
          ctx.pause(err.ratelimitReset * 1000, (err)=> {
            if (!err) {
              ctx.resume();
            } else {
              done(err);
            }
          });
        } else {
          done(err);
        }
      });
  });
```

**Comment by behrad** [comment]
pause's first input is the timeout of the process of trying to pause the worker, not the interval that worker will be paused. After the pause callback is called. you can delay until rateLimitReset and then resume.
You are currently resuming right after pause callback is called.

**Comment by bartonhammond** [comment]
So I changed to this but the jobs just keep running and I never see the 'resuming'.

```
          console.log('*********         pausing', pause);  ///  prints 8000
          ctx.pause(100, (err)=> {
            if (!err) {
              setTimeout( () => {
                console.log('*********    resuming');     //never see this                      
                ctx.resume();
              }, pause );
            } else {
              done(err);
            }
```

**Comment by bartonhammond** [comment]
My bad - the job queue does stop processing.
