### ISSUE TITLE
Pause processing of all jobs

### ISSUE THREAD

**Issue by gblock0** [Automattic/kue#830]
If I am not using the test queue, is there a way to pause processing of all jobs? I was thinking something like: 
```
queue.process('*', function(job, ctx, done){
  ctx.pause( 5000, function(err){
    console.log("Worker is paused... ");
    setTimeout( function(){ ctx.resume(); }, 10000 );
  });
});
```

**Comment by behrad** [comment]
There's no meaning for a wildcard worker in Kue @gblock0 You should call `ctx.pause` in all your worker functions when you want to :)

**Comment by behrad** [comment]
There's no meaning for a wildcard worker in Kue @gblock0 You should call `ctx.pause` in all your worker functions when you want to :)

**Comment by gblock0** [comment]
what if i have hundreds of worker functions that are dynamically created?

**Comment by behrad** [comment]
This won't be that easy, but you can somehow arrange to write also a dynamic system-wide pause, but how about using `queue.shutdown` ? you can use shutdown and let Kue do that for you.., however you should re-create (initialize) your queue using `createQueue` again :)

**Comment by gblock0** [comment]
Would I have to register all the processes again?

**Comment by behrad** [comment]
I believe so :)

**Comment by gblock0** [comment]
ok thanks
