### ISSUE TITLE
kue-dashboard: Cannot find module 'yargs'

### ISSUE THREAD

**Issue by mateeyow** [Automattic/kue#838]
This is the same with Issue #762. Somehow every time I install kue, `package.json` does not yargs on dependencies. Kue version: `0.10.5`

**Comment by behrad** [comment]
we should add yargs to `devDependecies`

**Comment by elyas-bhy** [comment]
This issue should be closed, following #796.

**Comment by juanmaia** [comment]
I have kue installed with version `^0.10.5` on my package.json, but I'm getting the same error.
Looks like yargs is on package.json on master, but not on `0.10.5`.
Are u guys planning to release a new version any time soon?
For now I manually added it on package.json.

**Comment by behrad** [comment]
fixed in 0.11.0
