### ISSUE TITLE
Cant bind events on job which was created via API

### ISSUE THREAD

**Issue by nanowang** [Automattic/kue#843]
Hi.

What I'm trying to do is:
- create a job via API
- register events on it

like this:
```
queue.on('job enqueue', function(id, type) {
  console.log("Job " + id + " got queued of type " + type + ", registering events...");
  return kue.Job.get(id, function(err, job) {
    return job.on('complete', function(result) {
      return console.log("Job completed with data: " + result);
    });
  });
});
```

I can check and confirm in the inspector that the function is already in `job._events.complete`, but the event wont be triggered.

**Comment by behrad** [comment]
I'm afraid job object events are only emitted in the producer process side, you can bind to queue `job complete` event.
