### ISSUE TITLE
Job id's being converted to Strings

### ISSUE THREAD

**Issue by hockeytim11** [Automattic/kue#845]
The stripFIFO function returns the string representation of the jobID (my fault, I missed that when writing it). I only noticed it now while doing strict comparison of cached jobID's in our unit tests.

I would suggest doing a type conversion before removing the jobID. Notice the added plus sign on the return.

```
 client.stripFIFO = function( zid ) {
      if ( typeof zid === 'string' ) {
        return +zid.substr(zid.indexOf('|')+1);
      } else {
        // Sometimes this gets called with an undefined
        // it seems to be OK to have that not resolve to an id
        return zid;
      }
    };
```

Thank you, this has been a very nice package to work with.

**Comment by behrad** [comment]
Why aren't you creating a PR @hockeytim11

**Comment by hockeytim11** [comment]
Sorry, I was able to move my project back to the main branch so I kinda stopped using my fork. I will revive it and create a PR though.
