### ISSUE TITLE
Delayed Jobs stuck in inactive state

### ISSUE THREAD

**Issue by ragavanthiru** [Automattic/kue#847]
When the node process of kue restarts or crashes and restarts, the delayed jobs getting stuck in the inactive state. But newly created delayed jobs are working. But when the server stops, I am gracefully shutting down the kue.

Added watchdog settings as well but it doesn't seem to be helpful.  How can I handle this?

**Comment by behrad** [comment]
Can you post a script which is reproducing the same issue?

**Comment by behrad** [comment]
> Attaching producer and consumer below

Your code is not minimal and contains many dependencies, I can't run it as-is, Can you break it down to a smaller code only using Kue?

**Comment by kirps** [comment]
I've moved on from the above approach due a discovered issue in that logic. 

My underlying problem is that I have a difficult time detecting specific job state. I've moved my current questions to #856.

Thanks for taking a look
