### ISSUE TITLE
How can I re execute the failed jobs?

### ISSUE THREAD

**Issue by goddyZhao** [Automattic/kue#851]
For example, I have some jobs, and they are failed after being retried for several times. But I want to schedule a timer (another bg process) to collect all the failed jobs (eg: once per hour) and re-execute them. Is it possible?

**Comment by behrad** [comment]
As README.md says you can do
```js
kue.Job.rangeByState( 'failed', 0, n, 'asc', function( err, jobs ) {
  // you have an array of maximum n Job objects here
  jobs.map(function(job){ job.inactive() });
});
```
