### ISSUE TITLE
How can I check the state of the queue to determine if a specific job exists

### ISSUE THREAD

**Issue by kirps** [Automattic/kue#856]
I need to create a job if and only if it does not exist in one of the states besides failed. The best I've come up with is below, but it loses access to queue events for some reason. Would LOVE some help/guidance.

```js
var createJob = function(job_data) {
	queue.create('event-test2',{title: 'Event Test2'}).save(); //this job triggers the handler
	//job type callback hell -- could be promisified or something?
	kue.Job.rangeByType(job_data.type, 'active', 0, 10000, 'asc', function(err, jobs) {
		if(err){
			console.log('error checking active jobs.');
			return;
		} else if (jobs.length === 0) {
			kue.Job.rangeByType(job_data.type, 'inactive', 0, 10000, 'asc', function(err, jobs) {
				if(err){
					console.log('error checking inactive jobs.');
					return;
				} else if (jobs.length === 0) {
					kue.Job.rangeByType(job_data.type, 'complete', 0, 10000, 'asc', function(err, jobs) {
						if(err){
							console.log('error checking complete jobs.');
							return;
						} else if (jobs.length === 0) {
							kue.Job.rangeByType(job_data.type, 'delayed', 0, 10000, 'asc', function(err, jobs) {
								if(err){
									console.log('error checking delayed jobs.');
									return;
								} else if (jobs.length === 0) {
									//now we know that the job of this type does not exist
									//save this on to the queue
									console.log('calling enqueue job'); //this is written to the console
									var job = queue.create(job_data.type, job_data.options)
										.delay(job_data.day_of_week.toDate())		
											.save(); //this job is placed on the queue, but does NOT trigger the event handler
								}
							});
						}
					});
				}
			});
		}		
	});
};
```

**Comment by behrad** [comment]
Your code doesn't seem meaningful to me, Use unique ids in your application.
You can store saved job.ids in your app, and check that id's state before re-creation of any job.

**Comment by kirps** [comment]
Are you saying to store the created id's in a separate data store and then query by id upon starting the job producing process?

**Comment by behrad** [comment]
> I guess it seems odd to me that I can't rely on the queue to tell me it's own state

you can query job state by Id, or query jobs by state... I can't see what you can't rely on?

**Comment by kirps** [comment]
The issue is unique jobs, thus some uuid is necessary, mind is calculated. Job.id does not seem to be overridable, thus I can't use that uuid in Job.get. 

Thus I must query the list of all job.ids for each state, iterate over them, get all the job objects by id, and check for a uuid property in their data. This quickly turns into an async mess.

Alternatively I can store a map of uuid: job.id in some other data store and check for each job.id. 

That requires either implementing another data store or at least additional raw redis data, which means sharing the redis client.

It feels like this should be trivial, so I feel like I'm missing something.

**Comment by behrad** [comment]
> Alternatively I can store a map of uuid: job.id in some other data store and check for each job.id

this is the way to go, as I mentioned before.

We can also add overridable job later in Kue, but job uniquness is something the application should take care of, not the job queue.

**Comment by kirps** [comment]
I'm in the process of implementing the map. My biggest issue is that it's a duplication of data that all necessarily exists on the queue. 

The ability to override the job.id might be a nice feature as you mentioned, thanks for the thoughts.
