### ISSUE TITLE
Kue broken with redis update

### ISSUE THREAD

**Issue by aldgagnon** [Automattic/kue#857]
Kue is throwing the following error when attempting to save jobs.

`Error: ERR wrong number of arguments for 'hset' command
    at JavascriptReplyParser.parseResult (/home/nodeuser/node_modules/redis/node_modules/redis-parser/lib/javascript.js:90:16)
 `

Appears there were some deprecations in node-redis starting in version 2.5.0. You can view the [changelog](https://github.com/NodeRedis/node_redis/blob/master/changelog.md). Is it possible to change Kue to use v2.4.2 until the issue is resolved?

As a work around, I have been explicitly setting redis in my package.json to v2.4.2.

**Comment by behrad** [comment]
Kue is currently using 2.4.x version of node_redis!

**Comment by aldgagnon** [comment]
From the package.json, it appears Kue is using

`"redis": "^2.4.2"`

If I'm not mistaken, the caret will allow the newer minor or patch level versions, which leads to the issue I'm having.
