### ISSUE TITLE
Where are the tasks running?

### ISSUE THREAD

**Issue by Brakkar** [Automattic/kue#862]
Hi
In the context of kue used as node background queue, what is responsible dor running the bg tasks?
Are they run from nodejs main thread or somerthing else? Also how is concurrency achieved, as on the email example in the docs? Threads?

**Comment by behrad** [comment]
Node.js has a single thread running an event loop. 
Kue is using node_redis's BLPOP implementation on top of that, to listen for new work. You can see https://github.com/Automattic/kue/blob/master/lib/kue.js#L326-L347 for the concurrency internals.
