### ISSUE TITLE
[Question] Subscribing to Job

### ISSUE THREAD

**Issue by tht13** [Automattic/kue#863]
My impression from the API is that Job#subscribe should invoke the callback whenever an event for that job is fired. I would then assume the event type to be the first argument (or second using the Error first convention) However I seem to just be getting the callback invoked immediately with no args passed. It is being called from [here](https://github.com/Automattic/kue/blob/master/lib/queue/job.js#L877). 
Is this supposed to be happening or am I doing this wrong?
Thanks

**Comment by behrad** [comment]
Job.subscribe is an internal method, You are not supposed to call it. Please refer to README for properly listening on job events.

**Comment by tht13** [comment]
You may want to remove the `@api public` tag from the jsdoc describing the method, or change it to private then.
It would be helpful then in the README to have a proper listing of extenal api methods. The README is great for learning the system with detailed examples, but a goo descriptive documentation (Based off of your JSDoc comments) would be a welcome addition :smile:

**Comment by behrad** [comment]
> You may want to remove the @api public tag from the jsdoc describing the method, or change it to private then

:+1:
