### ISSUE TITLE
Kue as message queueing implementation

### ISSUE THREAD

**Issue by markotom** [Automattic/kue#864]
I want to use Kue as Pub/Sub message queueing implementation, with different queues depending on a prefix (v.gr. component name). I've created a wrapper with a `push` method to add a message into a queue, but I could not accomplish that I wanted.

`publisher.js`

```js
const assert = require('assert')
const Kue = require('kue')
const faker = require('faker')

class Queue {
  constructor (options) {
    options = options || {}
    options.prefix = options.prefix || 'store'
    options.redis = options.redis || {}

    this.kue = new Kue({
      prefix: options.prefix,
      redis: options.redis
    })
  }

  push (queue, message) {
    assert.equal(typeof queue, 'string', 'should be specified a queue name')
    assert(message, 'should be specified a queue message')

    this.kue.create(queue, message).save()
    return this
  }
}

let queue1 = new Queue({ prefix: 'store1' })
let queue2 = new Queue({ prefix: 'store2' })

setInterval(function () {
  let model = {
    firstname: faker.name.firstName(),
    lastname: faker.name.lastName()
  }

  queue1.push('user.create', model)
  queue2.push('user.create', model)
}, 500)
```

`subscriber.js`

```js
const Kue = require('kue')
const queue1 = new Kue({  prefix: 'store1' })
const queue2 = new Kue({  prefix: 'store2' })

queue1.process('user.create', function (queue, next) {
  console.log('Store 1', 'Creating a new user...')
  console.log(queue.data)
  next()
})

queue2.process('user.create', function (queue, next) {
  console.log('Store 2', 'Creating a new user...')
  console.log(queue.data)
  next()
}))
```

But, my example just save one queue message into Redis  with `store2` prefix to be received by the `queue2.process`. I don't know if I did something wrong or is an issue about of unsupported multiple instances from `Kue()`. Do you know how I can work it?

**Comment by behrad** [comment]
You can't `const queue1 = new Kue({  prefix: 'store1' })`.
You should use `.createQueue` which currently returns a singleton. 
Also I don't see a fit for two `.process` calls with the same job name in a single node.js process. Either do them in multiple node.js processes or call it this way:

`queue.process('user.create', 2, function(...`
