### ISSUE TITLE
Kue job processing not working

### ISSUE THREAD

**Issue by jatinseth2007** [Automattic/kue#865]
Hi,

I have a system where I need to create lot of jobs around 35000-40000, I am testing this system by creating jobs at one end and processing it on other end. I am able to create jobs (I have verified it by  seeing Redis) but I am not able to process it. At the time of processing, It never comes inside process function, 1 always prints but 2 never

console.log('1');
jobs.process ("tagSocialposts", 1, function(job, done){
console.log('2');
});

 I tried to debug it by printing console.log(jobs) it is showing following output, I am not able to see jobs type "tagSocialposts" but able to see in redis. Secondly,  connected: false is showing false.

{ client: 
   { stream: 
      { _connecting: true,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        onend: null,
        destroyed: false,
        bytesRead: 0,
        _bytesDispatched: 0,
        _pendingData: null,
        _pendingEncoding: '',
        pipe: [Function],
        addListener: [Function: addListener],
        on: [Function: addListener],
        pause: [Function],
        resume: [Function] },
     options: { socket_nodelay: true, socket_keepalive: true },
     connection_id: 1,
     connected: false,
     ready: false,
     connections: 0,
     should_buffer: true,
     command_queue_high_water: 1000,
     command_queue_low_water: 0,
     max_attempts: null,
     command_queue: { tail: [], head: [], offset: 0 },
     offline_queue: { tail: [Object], head: [], offset: 0 },
     commands_sent: 0,
     connect_timeout: false,
     enable_offline_queue: true,
     retry_max_delay: null,
     retry_timer: null,
     retry_totaltime: 0,
     retry_delay: 150,
     retry_backoff: 1.7,
     attempts: 1,
     pub_sub_mode: false,
     subscription_set: {},
     monitoring: false,
     closing: false,
     server_info: {},
     auth_pass: null,
     parser_module: null,
     selected_db: null,
     old_state: null,
     domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     connectionOption: { port: 6379, host: '127.0.0.1', family: 4 },
     address: '127.0.0.1:6379',
     prefix: 'q',
     getKey: [Function] },
  promoter: null,
  workers: 
   [ { queue: [Circular],
       type: 'blogFacebook',
       client: [Object],
       running: true,
       job: null,
       id: '13085-blogFacebook-1',
       _events: [Object] },
     { queue: [Circular],
       type: 'blogInstagram',
       client: [Object],
       running: true,
       job: null,
       id: '13085-blogInstagram-2',
       _events: [Object] },
     { queue: [Circular],
       type: 'blogPinterest',
       client: [Object],
       running: true,
       job: null,
       id: '13085-blogPinterest-3',
       _events: [Object] },
     { queue: [Circular],
       type: 'blogRss',
       client: [Object],
       running: true,
       job: null,
       id: '13085-blogRss-4',
       _events: [Object] },
     { queue: [Circular],
       type: 'blogTumblr',
       client: [Object],
       running: true,
       job: null,
       id: '13085-blogTumblr-5',
       _events: [Object] },
     { queue: [Circular],
       type: 'blogTwitter',
       client: [Object],
       running: true,
       job: null,
       id: '13085-blogTwitter-6',
       _events: [Object] },
     { queue: [Circular],
       type: 'blogYoutube',
       client: [Object],
       running: true,
       job: null,
       id: '13085-blogYoutube-7',
       _events: [Object] },
     { queue: [Circular],
       type: 'mailers.users.expired',
       client: [Object],
       running: true,
       job: null,
       id: '13085-mailers.users.expired-8',
       _events: [Object] },
     { queue: [Circular],
       type: 'monitorSocialposts',
       client: [Object],
       running: true,
       job: null,
       id: '13085-monitorSocialposts-9',
       _events: [Object] },
     { queue: [Circular],
       type: 'monitorSocialpostsMetrics',
       client: [Object],
       running: true,
       job: null,
       id: '13085-monitorSocialpostsMetrics-10',
       _events: [Object] },
     { queue: [Circular],
       type: 'tagAssignBlogs',
       client: [Object],
       running: true,
       job: null,
       id: '13085-tagAssignBlogs-11',
       _events: [Object] } ],
  shuttingDown: false }

**Comment by jatinseth2007** [comment]
Have a look at my KUE-UI http://demos.preprod.ykone.com/kue/jobs/ 

It's showing the jobs.

**Comment by behrad** [comment]
> console.log('1');
> jobs.process ("tagSocialposts", 1, function(job, done){
> console.log('2');
> });

you should call done after `console.log` so that your worker keeps on the next job
