### ISSUE TITLE
Search API is not working

### ISSUE THREAD

**Issue by gabrielcsapo** [Automattic/kue#866]
```
var job = jobs.create('install', { project: project, title: project.name })
        .priority(extra.priority)
        .searchKeys(['title'])
        .save();
```

if `project.name` is `testing1`

`curl -v http://localhost:8872/granaries/job/search?q=testing`
`[]`

Will look at the tests and see if I can pinpoint the issue.

**Comment by Dev-Dipesh** [comment]
Have you found a solution for it?
I'm running into the same issue, even though I have defined indexes and also tried with *reds*, I still can't search it. All other JSON APIs are working but `search?q=` isn't.
