### ISSUE TITLE
Forcing single active job at once

### ISSUE THREAD

**Issue by whitepaperclip** [Automattic/kue#887]
Is this possible? Say I have 10,000 records in a database and I want to store a result for each one of them, from some third-party API. If I add each object to the queue, I don't want to flood the API with 10,000 requests. How do I force each job to wait for completion?

`queue.process("api", 1, function (job, done) {`

The above hasn't worked. It's still putting 350+ records in an active state.

**Comment by behrad** [comment]
That should work if you call your store method inside process and call done when store is finished.

**Comment by whitepaperclip** [comment]
I was calling `done()` prematurely.
