### ISSUE TITLE
Question: How expensive is inactiveCount() call / job split & rebalancing

### ISSUE THREAD

**Issue by nyurik** [Automattic/kue#893]
I have very long-running jobs, and the service runs ~100 job processors. Once in a while, each process should check how many jobs are in the inactive queue, and if the queue is running low (under 10), split current job into two.  I do not want to overwhelm Redis server when it has many jobs (thousands), so the question is - how often should each of the 100 job processors check the size of the inactive queue on a good fast server.  Does it perform any kind of counting, or is that a single value somewhere? 

P.S. Is there a reason why job.progress() does not have a completion callback?

**Comment by behrad** [comment]
> Does it perform any kind of counting, or is that a single value somewhere?

inactiveCount uses Redis' ZCARD operation and that's cheap. You are OK to run that even per second :)



> P.S. Is there a reason why job.progress() does not have a completion callback?

No. You can add one!

**Comment by nyurik** [comment]
Thx!
