### ISSUE TITLE
Security: Update stylus to 0.54.5, fixes minimatch 0.3.0 RegExp DoS issue

### ISSUE THREAD

**Issue by FdezRomero** [Automattic/kue#911]
Hi there,

Kue currently uses `stylus@0.52.x`, with the following dependency tree:

```
+ stylus@0.52.4
  + glob@3.2.11
    + minimatch@0.3.0
```

On install, NPM warns "minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue".

Simply updating the `package.json` to `stylus@0.54.5` would update `glob` to 7.0.x and `minimatch` to 3.0.2, fixing the RegExp DoS issue.

Thank you!

P.S. Very funny that this security alert is issue #911 🚨

**Comment by kievechua** [comment]
Come across this issue via synk.io
More details can be seen here
https://snyk.io/test/npm/kue/0.11.1

**Comment by behrad** [comment]
this should be fixed now
