### ISSUE TITLE
How do I done() another job (by job id?)?

### ISSUE THREAD

**Issue by mautematico** [Automattic/kue#913]
How do I done()

**Comment by behrad** [comment]
I don't see why you need this?

**Comment by frode** [comment]
If you have a async function performing server-side stuff that will run another function on the feedback, you want to pass the job.id and perform a done on the job once server is done? I need this. I've seen this been asked before, without any answers..

**Comment by behrad** [comment]
simply also pass the `done` callback where it needs to go.
