### ISSUE TITLE
slack integration

### ISSUE THREAD

**Issue by victusfate** [Automattic/kue#917]
Has anyone worked on any slack integrations?
Curious one of my coworkers wanted to get some feedback on jobs that were initiated by slack, I figured a general integration connected to a specific channel would be good.

**Comment by nallown** [comment]
Just use the [slack-node-sdk](https://github.com/clonn/slack-node-sdk) module to trigger the Slack webhook on event fires. Should be pretty straight forward to do.

**Comment by victusfate** [comment]
thanks
