### ISSUE TITLE
Job being processed with older queue version

### ISSUE THREAD

**Issue by ilroux** [Automattic/kue#928]
Hello folks:

I'm running into an issue where a sometimes a job is getting executed by an old version of the queue process block, when this happens is apparently random. I've read #391 and #403 the process block error handler for both versions looks like this:

 ```js
queue.process('job', function (job, done) {
  var domain = require('domain').create();
  domain.on('error', function (err) {
    var err = `Unexpected error: ${err}`;
    log.error(err);
    done(err);
  });

  domain.run(function () {
    //Do some work
    done();
  });
});
```

To fixed i've tried the following:
1. **flushdb redis**: No luck
2. **Check for other instances of the app**: I've stopped the app and queue a couple of jobs so see if maybe another process was pinned and continue to execute the jobs, but was not the case, the queue remained the same until the app was turned on again.

I'm pretty lost at this point and I was hoping if you can point me in the right direction to understand what could be wrong?

Thank you for your time,
Juan

**Comment by ilroux** [comment]
Fixed by changing the job name, closing the issue.

**Comment by ryanvanderpol** [comment]
I'm experiencing the exact same thing and believe this should be reopened. I found this older issue (#494) where a few others seemed to have the same problem.  

As stated here by @juankaram, changing the name of the job resolves the issue, but that is not a viable solution for me.

**Comment by ryanvanderpol** [comment]
To make things even more confusing, I actually REMOVED the job altogether.  I completely deleted the job code from the app.  But when I add a job to the queue with the same name as the old job it still executes the old job code.

**Comment by ryanvanderpol** [comment]
Bump.  This is still a problem for me and I think this issue should be reopened.
