### ISSUE TITLE
How to prevent adding the same job

### ISSUE THREAD

**Issue by carstensaltus** [Automattic/kue#934]
I want to be able to create/save a job with a unique value that is indexed, once i attempt to add this  same job again, it shouldn't save/create this job if it already exists in the queue.

I'm thinking of extending the save function to do this check for me, but not to sure how to approach this.
kue.Job.prototype.save = function(fn) {}

**Comment by victusfate** [comment]
I'd handle it with something up front, like a hash of inputs (you mention an id) and then store this id in a key / value database (like redis or memcache).

if (id or hash of inputs is not in table) then fire the job

**Comment by peterporfy** [comment]
You need a distributed lock like in this PR: https://github.com/Automattic/kue/pull/832/files
We use a similar approach (but with redlock) and works well.
