### ISSUE TITLE
Has Support Stopped for Kue?

### ISSUE THREAD

**Issue by JperF** [Automattic/kue#935]
Has support for kue stopped? I made an issue (#918) over a month ago and no progress report nor status updates on it. 

@behrad Originally commented on it but gave no real reasoning for the issue. Last time I posted an issue it was resolved relatively quickly.

**Comment by behrad** [comment]
I've been so busy @JperF , excuse me for the delay, However I'd expect Kue users to debug issues and create PRs, I'd love to see more contributions :) I've not enough time to test and debug all issues myself :(

**Comment by victusfate** [comment]
I have just enough time to read through some issues and suggest answers ;)

**Comment by jdesboeufs** [comment]
@behrad Why not promote some additional maintainers?
I've pending PR ;)

**Comment by behrad** [comment]
@jdesboeufs I'm open to this

**Comment by jdesboeufs** [comment]
Cool!
What about v1 status? Nearly released or features to cherry-pick?

**Comment by jdesboeufs** [comment]
But OK to join the maintainer team ;)

**Comment by nrempel** [comment]
Any update on this?

**Comment by behrad** [comment]
I'll try to review and merge pending PR's, I'll let in those with active effective PRs.

**Comment by nrempel** [comment]
Thanks for the update @behrad! I completely understand the lack of bandwidth to support an open source project in your spare time. I'm glad people are stepping up to help maintain.

**Comment by behrad** [comment]
0.11.2 is published, I'm getting ready to switch master to v1... any guys how want to review
