### ISSUE TITLE
Working on one job at a time / jobs blocking each other

### ISSUE THREAD

**Issue by queicherius** [Automattic/kue#937]
Let's say I have a job, which blocks the CPU for a while. If this job is triggered while a bunch of other jobs are already running, it completely blocks the execution of them as well, since it hogs the CPU so much.

- Can you limit the CPU of each job, so all of them are guaranteed at least an equal amount of CPU?
- Can you make the worker process only run a single job at a time (as opposed to a single job **per type**, which it is doing right now), while still using the priorities set to determine which job to choose? This way I could spawn mutltiple processes and limit their CPU at the OS level.

Or am I doing something completely wrong in the first place? Anything helps. Thanks! 😃

**Comment by victusfate** [comment]
I think you want to start running different types of jobs dedicated to their own workers.

What I'm planning to do is have 1 server's workers handle Job types A,B,C another servers workers handle Job types D, another server's workers handle Job type E,F etc. All of them connect to the same redis instance/kue through a lite wrapper I coded up (has Job and Worker classes)

**Comment by queicherius** [comment]
I was thinking about doing it via the method you wrote (process A only takes job A, process B takes B, C and D etc). However in my case the CPU intensive task only runs a few times a day, so I'd effectively waste potential of the worker (since I would CPU lock them all at e.g. 1/4 of the CPU), wouldn't I?

**Comment by victusfate** [comment]
With a differentiated setup yeah you wouldn't access type A's resources with other job types.
If A only runs once a day or so, you can always bundle it with your other light resource jobs.

**Comment by queicherius** [comment]
> If A only runs once a day or so, you can always bundle it with your other light resource jobs.

But that poses exactly the problem I described - then A takes away (in my case completely blocks for an unacceptable amount of time) the resources of B, C and D. 😞

**Comment by queicherius** [comment]
Alright, so I found a way to do this which is kind of hacky, but still acceptable in my case. I just use the same "type" for all workers (so everything is in the same queue and gets worked off sequentially), and define the actual worker type in the `data` object. Then I can cluster it (one process / core) so the resources for each worker are independent. In my tests this works pretty well, but I am still curious if there is a better way.

```js
const kue = require('kue')
const cluster = require('cluster')
const os = require('os')
const queue = kue.createQueue()
const clusterWorkerSize = os.cpus().length

if (cluster.isMaster) {
  setupMaster()
} else {
  setupWorker()
}

// Setup the master, which forks the workers
function setupMaster () {
  // Fork the cluster
  for (var i = 0; i < clusterWorkerSize; i++) {
    console.log(`Forking cluster #${i}!`)
    cluster.fork()
  }

  // Queue some demo jobs
  setTimeout(() => {
    for (var j = 0; j < 10; j++) {
      queue
        .create('worker', {handler: 'high-priority', title: 'High priority job'})
        .priority('high')
        .save()

      queue
        .create('worker', {handler: 'low-priority', title: 'Low priority job'})
        .priority('low')
        .save()
    }
  }, 3000)
}

// Setup the workers, which process jobs
function setupWorker () {
  queue.process('worker', (job, done) => {
    log('Popping job: ' + job.data.handler)

    // Get the callback using the handler ID
    const callback = jobs[job.data.handler]
    callback(job, done)
  })
}

// List of all jobs with their processing callbacks
const jobs = {
  'high-priority': (job, done) => {
    log('Doing high priority work')
    blockCpuFor(10)
    log('Done with high priority work')
    done()
  },
  'low-priority': (job, done) => {
    log('Doing low priority work')
    setTimeout(() => {
      log('Done with low priority work')
      done()
    }, 500)
  }
}

// Logging with timestamp
function log (s) {
  var now = new Date().toString()
  console.log('[' + now + '] ' + s)
}

// Block the CPU / event queue doing meaningless work
function blockCpuFor (s) {
  var ms = s * 1000
  var now = new Date().getTime()
  var result = 0
  while (true) {
    result += Math.random() * Math.random() * Math.random() * Math.random()
    if (new Date().getTime() > now + ms) {
      return
    }
  }
}
```

**Comment by victusfate** [comment]
The Jobs all have different types so don't block each other. But you can register different jobs together in the same worker.

**Comment by queicherius** [comment]
Even if they have different types, they have the potential to block each other. That was my initially described (and tested) problem. I solved my use-case with a [wrapper around kue](https://github.com/queicherius/simple-worker) in the end.
