### ISSUE TITLE
Hosting on Elastic Beanstalk?

### ISSUE THREAD

**Issue by seanlindo** [Automattic/kue#939]
Has anyone successfully deployed a worker instance to ELB? I don't want to go through setting up and managing an EC2 instance if I don't have to

**Comment by peterporfy** [comment]
Yes, what is your question?

**Comment by seanlindo** [comment]
Sorry! What steps did you take @peterporfy?

**Comment by peterporfy** [comment]
Nothing special. We are using workers along with express. We have both single instance and load balanced auto scale instances as well. Simple Amazon Linux with nodejs. You should set up the recommended graceful shutdown for Kue especially when using autoscale. We are probably going to create a supervisor instance for watchstuckedjobs and timeout management. Currently watchstuckedjobs runs in each instance which is unnecessary and it is not straightforward to declare a master instance in EB.
