### ISSUE TITLE
search keys not being removed

### ISSUE THREAD

**Issue by bbn** [Automattic/kue#94]
When a job is complete I remove it from the queue (see code below). After running about 70,000 jobs overnight the redis memory usage is at approx 30MB. There were 18 failed jobs still in the database, and the queue length is currently zero - jobs are processed more quickly than they are queuing. Redis is not being used in any other way.

Any ideas why the redis memory usage keeps increasing even though I'm deleting the completed jobs? Coffeescript code:

```
gaemodel.update = (params) ->
  job = jobs.create "gaemodel-update", params 
  job.attempts 2
  job.save()
  job.on "complete", ->
    job.remove (err) ->
      throw err if err
      console.log 'completed job #%d', job.id
```

**Comment by knutole** [comment]
I think there should be a `flushall` option when initing `Kue` so that the job queue will be clean each time it's run. Very useful when scripting, debugging, testing. Now I have to manually `flushall` on unclean exits.

**Comment by behrad** [comment]
a `flushall_q_keys` would be more appropriate option :)

**Comment by knutole** [comment]
Yes, and much appreciated!

**Comment by behrad** [comment]
then you can create a new issue for that @knutole
