### ISSUE TITLE
node_redis: Deprecated: The HSET command contains a "undefined" argument.

### ISSUE THREAD

**Issue by Dids** [Automattic/kue#943]
I'm assuming this is caused by kue, but not 100% sure.

**Comment by davelandry** [comment]
Also getting this message, here's the full warning:

```
node_redis: Deprecated: The HSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
```

**Comment by AliUz** [comment]
same

**Comment by aldgagnon** [comment]
Has anyone made any progress this morning? Just ran into this issue this morning and started poking around which lead me here.

**Comment by AliUz** [comment]
Any updates on this? It's causing my jobs to fail ...

**Comment by nmalzieu** [comment]
Any news on this ? I'm getting the same error. My task is executed but this error makes kue retry so it's actually executed a few times.
Thanks !

**Comment by AliUz** [comment]
I found the reason for my failure, I was using promises with kue, and I was calling the done callback like this : `.then(done)`. But the callback structure is `done()` for success or `done(err)` for error. So if `done` is called with any parameter, it fails. 

I corrected it like so:

```
.then(() => done())
.catch(done)
```

**Comment by nmalzieu** [comment]
that was it ! thanks so much @AliUz 👍

**Comment by AliUz** [comment]
@nmalzieu no problem mate! :)

**Comment by Dids** [comment]
Just to chime in, I'm not using `.then` promises, so that doesn't apply in my case.

**Comment by ChrisAlvares** [comment]
I am also getting this without using the `.then` promise.

**Comment by behrad** [comment]
that may be related to a callback not being passed somewhere...

**Comment by daohoangson** [comment]
I have encountered this issue and it looks like it happened when the error for done() is not a string or Error().

**Comment by angelmadames** [comment]
@AliUz Man, you rock! Thanks for your input, helped us solve some issues :)

**Comment by fedecaccia** [comment]
Thanks for the answer it helped to me! So, how can we return the result from the worker?
