### ISSUE TITLE
Endless 'TTL exceeded' error log

### ISSUE THREAD

**Issue by xavierchow** [Automattic/kue#944]
I have some jobs in `failed` state due to ttl exceeded, but their `zid`s are still in the `jobs:active` sorted set, which leads to writing the error log again and again and finally exhausts all redis memory.

* There's `checkActiveJobTtl` which use setInterval to check the active job ttl, see [here](https://github.com/Automattic/kue/blob/master/lib/kue.js#L224-L244)
* The failed job's zid is still in the zset and it's timeouted already
* Then `job.failedAttempt` will be called and it writes a log to `{q}:job:id:log`
* Cause the old state and new state are both `failed` the `zid` wouldn't be removed [here](https://github.com/Automattic/kue/blob/master/lib/queue/job.js#L676)

My question is how could this inconsistency happen? and any suggestion to remedy it?

**Comment by behrad** [comment]
There may be a race in job ttl handling, 
TTL is dropped in Kue v1 in favor of automatic stalled job handling by Kue.
