### ISSUE TITLE
Desc sorting in UI seems weird

### ISSUE THREAD

**Issue by Ir00man** [Automattic/kue#945]
When selecting **desc** sort in UI one can see that jobs sorting well from big to little job_id, but why first (biggest) number is far from real biggest number? It's 142 or me, but I have 23593 jobs in total.

![screenshot from 2016-09-12 19-59-18](https://cloud.githubusercontent.com/assets/3997133/18444975/751eb66e-792c-11e6-91c8-816f192e8533.png)

And then, after scrolling to the bottom of the list, we get next part of jobs loaded and showed and they also sorted from big to little but within their range (for me 152 - 143)

![screenshot from 2016-09-12 19-59-48](https://cloud.githubusercontent.com/assets/3997133/18445043/c93e68de-792c-11e6-9405-525b656ed2d7.png)

Why it's so by design and how can I get real desc sorting to view last jobs listed on top?

Thx.

**Comment by behrad** [comment]
It will be changed to recently completed in later versions

**Comment by vjustov** [comment]
Any updates on this?
