### ISSUE TITLE
How to keep all the jobs I have created even after a stop and run of the code.

### ISSUE THREAD

**Issue by antoniodimariano** [Automattic/kue#946]
Hi to all, 

let me consider this example https://github.com/Automattic/kue/blob/master/examples/stale.js
 just to go forward to my issue:

Every time I restart the code, I lose all the jobs I have started.
I was wondering if there is a way to keep the jobs list I have created even after a stop and run of the code. 
It could be nice if all the jobs would restart as soon as the code starts.
 
Thank you in advance.

**Comment by antoniodimariano** [comment]
Actually what I really need is a way to load an already existing Queue on Redis.
Is it possible?

**Comment by peterporfy** [comment]
It is not completely clear what do you mean. Can you please elaborate a bit more? What do you mean by `Every time I restart the code, I loose all the jobs I have started.`?

**Comment by antoniodimariano** [comment]
Well, I mean each time I  stop and re-run my code I lose the jobs. 
There is a way to reconnect, 

> var jobs = kue.createQueue()

using to an already created Queue on Redis  and rerun the existing jobs?
Hope I make myself clear.

**Comment by antoniodimariano** [comment]
@peterporfy What I am looking for is a way to resume jobs after a restart of the node.js application.

**Comment by peterporfy** [comment]
It is still not completely clear. You don't have the jobs after a node restart? Are they in redis?

We are stopping and starting this kind of applications several times a day (aws autoscaling + deployments) without problem. Job processing does not stop.

We use https://github.com/Automattic/kue#graceful-shutdown also to drain the actual server.
