### ISSUE TITLE
createQueue does not respect redis connection settings?

### ISSUE THREAD

**Issue by nicholasserra** [Automattic/kue#947]
Hello. Trying to start with the most basic trial of kue. Trying to connect to local redis via

```
var kue = require('kue');
var q = kue.createQueue({
  prefix: 'q',
  redis: {
    port: 1234,
    host: '127.0.0.1',
  }
});
```

As described in the redis connection settings docs: https://github.com/Automattic/kue#redis-connection-settings

But always getting the error `Redis connection to 127.0.0.1:6379 failed`. It seems createQueue is not respecting anything I pass into it as options. Wondering if the docs are out of date?

Thanks!

**Comment by nicholasserra** [comment]
Disregard, had a weird local dependency issue that was doubling up instances.

**Comment by FdezRomero** [comment]
Hi @nicholasserra, I'm having the same issue. How did you solve this?

**Comment by nicholasserra** [comment]
I realized I was initializing two instances of kue. The docs ended up being correct on how to specify a custom redis connection.

**Comment by FdezRomero** [comment]
So it must be something else in my case... Thanks!

**Comment by lifeisfoo** [comment]
I'm facing the same issue on node 6.3.0 and kue  0.11.5, any advice?

The `createQueue` function is executed automatically when the kue module is required, so the singleton is populated and the next explicit call `kue.createQueue(opts)` doesn't recreate the connection (because is a singleton).

```
var kue = require('kue');
var queue = kue.createQueue(opts);
```
