### ISSUE TITLE
Error: Redis connection to 127.0.0.1:6379 failed - connect EMFILE 12

### ISSUE THREAD

**Issue by devarajc** [Automattic/kue#949]
Im new to the kue api.  When I try to create more than 1000 queues using loop,  node js throwing  an **Error: Redis connection to 127.0.0.1:6379 failed - connect EMFILE 12**

My question is 
1. basically  doing anything wrong?
2. need to close the queue some where?

var kue = require('kue');
const queue = kue.createQueue();
var counter = 0;

function createJob(i) {

    var job = queue.create('email' + i, {
        title: 'welcome email for tj',
        to: 'tj@learnboost.com',
        template: 'welcome-email'
    }).attempts(5).save(function(err) {
        //if (!err) //console.log(job.id);
    });

    queue.process('email' + i, function(job, done) {
        email(job.data, done);
    });

    function email(address, done) {
        console.log("hey............", address);
        ++counter;
        done()
    }
}

queue.on('job enqueue', function(id, type) {
    //console.log( 'Job %s got queued of type %s', id, type );

}).on('job complete', function(id, result) {

    console.log("done......", id, result);
    kue.Job.get(id, function(err, job) {
        if (err) return;
        job.remove(function(err) {
            if (err) throw err;
            console.log('removed completed job #%d', job.id);
            console.log(new Date());
            console.log("counter", counter);
        });

    });
});

for (var i = 0; i < 1000; i++) {
    createJob(i);
}

**Console Error** 
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect EMFILE 127.0.0.1:6379 - Local (undefined:undefined)
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at connect (net.js:863:16)
    at net.js:951:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
    at node.js:405:3

**Comment by peterporfy** [comment]
Kue will create a redis connection for each job type (for separate BLPOP). You basically create 1000 job types by your `'email' + i` pattern. You should not do that.

Define a single job type which is `email` in your example.

So creating a job:

```
function createJob(i) {

var job = queue.create('email', {
    title: 'welcome email for tj',
    to: 'tj@learnboost.com',
    template: 'welcome-email'
}).attempts(5).save(function(err) {
    //if (!err) //console.log(job.id);
});
}
```

And process them in a single handler:
```
queue.process('email', function(job, done) {
    email(job.data, done);
});


function email(address, done) {
    console.log("hey............", address);
    ++counter;
    done()
}
```

If you want to process more jobs concurrently then see the documentation: https://github.com/Automattic/kue#processing-concurrency

**Comment by devarajc** [comment]
got it..Thanks.
If I have 4 cores system, processing-concurrency functionality will use the 4 cores efficiently?

**Comment by peterporfy** [comment]
It depends on what you. Nodejs itself is single threaded so keep that in mind.

**Comment by devarajc** [comment]
Okay..thanks:)
