### ISSUE TITLE
Why did you implement Kue?

### ISSUE THREAD

**Issue by adriano-di-giovanni** [Automattic/kue#950]
I know it's an odd question to ask but why did you implement Kue instead of using one of the established MQ servers?

Thanks

**Comment by behrad** [comment]
Kue is a task/job opinioned queue, not a generic message queue.
Distribution of workers, Job retries, scheduled jobs and simplicity was main purpose of kue when I joined this project.
Can you elaborate on some MQ names that can be simply replaced by Kue?

**Comment by adriano-di-giovanni** [comment]
I'm new to MQs so, I can't elaborate any name at the moment.
Can you answer your own question, please?

**Comment by aysark** [comment]
Interested in this question too.

Also compare and contrast agenda vs kue (other than the obvious) would be appreciated.

**Comment by behrad** [comment]
http://queues.io also may help guys

**Comment by behrad** [comment]
And as @antirez [says](http://antirez.com/news/88) implementing a job queue on top of redis is almost deprecated, and [Disque](https://github.com/antirez/disque) is born for such cases.
I'm thinking to re-write the next Node.js job queue on top of Disque...

**Comment by mitchellporter** [comment]
>Distribution of workers, Job retries, scheduled jobs and simplicity was main purpose of kue when I joined this project.

@behrad  Thanks for the info. This simple explanation did a lot for me, makes sense now why so many libs have been abstracting away certain queue complexities. Also thanks for sharing http://queues.io I hadn't seen this before.

**Comment by rturk** [comment]
We use kue for all our backend processing, including payments and credit card processing. Previously we've used celery. Main reasons are:

- It just works. 
- It's based nodejs so I can keep my code clean, re-use code, re-use unit tests
- Backed by redis, proven fault proof insanely fast server
- AWS friendly (via redis server)
- It's easy to run Multiple workers in parallel using PM2
- All the messaging is JSON based, after I'll my jobs are done I dump them to MongoDB 
- Survived last blackfriday

**Comment by mitchellporter** [comment]
> All the messaging is JSON based, after jobs are done I dump them to MongoDB

@rturk Would you mind elaborating on this.. what are you dumping into mongo and why?

**Comment by rturk** [comment]
@mitchellporter I dump old jobs to MongoDB in order to keep redisDB storage footprint small.
