### ISSUE TITLE
Process does not exit

### ISSUE THREAD

**Issue by AliUz** [Automattic/kue#951]
I have a cronjob that runs periodcally, and I implemented a job queue using Kue. At the end of the job, I close my connection to the database. Before it used to work, but ever since implementing Kue, the process does not exit. I am assuming this is because the Redis connection stays open.

Any way to tell the job to exit once it has completed the jobs in the queue? Or a way to close redis connection?

**Comment by behrad** [comment]
Have you tried `.shutdown`?

**Comment by AliUz** [comment]
@behrad works :-) thanks!
