### ISSUE TITLE
Kue failing upon job creation

### ISSUE THREAD

**Issue by aldgagnon** [Automattic/kue#953]
Installed software:

> Debian 8.1
> Strongloop v6.0.2
> NodeJS v4.2.4
> Kue 0.11.1

I am experience an issue creating a simple Kue job. I'm attempting to create a job using the sample code provided in the documentation, however the applicationerrors out immediately. The error appears to be triggered when calling the save() function. I've further tested this sample code with various redis server versions, with both local and remote installations but with no luck. Has anyone else experienced this issue or anything similar? What strikes me as odd is that the application crashes when attempting to run it using Strongloop (**slc run**) however works fine when simply running it with Node (**node .**). The error is provided below.

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> ReplyError: ERR wrong number of arguments for 'hset' command
>     at parseError (/home/nodeuser/node_modules/kue/node_modules/redis/node_modules/redis-parser/lib/parser.js:163:12)
>     at parseType (/home/nodeuser/node_modules/kue/node_modules/redis/node_modules/redis-parser/lib/parser.js:224:14)

**Comment by rtodea** [comment]
My stack trace for the same issue:

**Comment by rtodea** [comment]
After some debugging I have found the problem to be [`strong-agent`](https://github.com/strongloop/strong-agent).

The app is started with [tracing](https://docs.strongloop.com/display/SLC/Tracing) enabled by default.

To have the tracing functionality, `strong-agent` wraps the Node packages (i.e. the ones in [`/lib/probes`](https://github.com/strongloop/strong-agent/tree/master/lib/probes)) to provide a profiling API.

One of these packages is the [`redis`](https://github.com/strongloop/strong-agent/blob/master/lib/probes/redis.js) Node client, but as mentioned in the Strongloop tracing [docs](https://docs.strongloop.com/display/SLC/Tracing):

> The following table lists the backends for which tracing has been tested. It may work with other versions of the stated Node drivers, but has not been tested with them.
> ...
> Redis	redis 0.21.1
> 

The `redis` Node package used by `kue` is **2.6.0**, but the slc knows how to wrap **0.12.1** (0.21.1 does not exist, and might be a typo in the docs).

A solution is to start the app without tracing/profiling.

This is available via `--no-profile` option:
```
slc run --no-profile
```

When in production one would use `slc start` which does not have `--no-profile`.

The docs also mention `slc ctl tracing-stop <SERVICE-ID>`.

But, unfortunately, something like:
```
slc start
slc ctl tracing-stop <SERVICE_ID>
```
does not work.

**Comment by aldgagnon** [comment]
Well done rtodea! Good job on the debugging. Glad to see you created a ticket was created with strongloop. Let's hope they pick it up and fix it!

**Comment by sam-github** [comment]
We are trying to address this in https://github.com/strongloop/strong-agent/issues/10, but I don't know how to reproduce. Can someone post an example script using kue or redis that fails?
