### ISSUE TITLE
How Do You Debug Stuck Jobs ?

### ISSUE THREAD

**Issue by adalyz** [Automattic/kue#957]
Hi Guys,

We are processing close to over 2 Million jobs daily with kue, but unfortunately we have to restart kue every 2 days because there are jobs which are stuck in Active state for more than 6 hours. 

I understand that its something to do related with some promise not being fulfilled or redis connection mismatch or something. 

Unfortunately using domains, logs, try catch and others is not helping us narrow down on the issue.  

I just want to know how do you guys debug such cases ?  Any suggestion is most welcome. 

Thanks

**Comment by behrad** [comment]
You may use different timeouts within your suspected callbacks which may are not being called.
You can use Kue's ttl feature (has some issues in 0.11)
I'm finalizing v1 branch of kue which should solve issues mentioned above.

**Comment by adalyz** [comment]
Thanks behrad, can you please explain what do you mean by 

> You may use different timeouts within your suspected callbacks which may are not being called.

**Comment by xfg** [comment]
@behrad when are us wait v1 ?

**Comment by behrad** [comment]
In a week or 2!
