### ISSUE TITLE
Failing a job

### ISSUE THREAD

**Issue by edward-blanco** [Automattic/kue#958]
Why if the http.statusCode !== 200 the jod is completed and not failed?

testing ".save(function (err)" for example the err is null but I need to catch the error when http.statusCode is not 200. How can I get a failed job if http.statusCode = 500?

**Comment by Deadly0** [comment]
In this case i just re-enqueue the job like this:
```
if (http.statusCode === 500) {
    job.state('inactive').save();
    done();
}
```

Maybe it will be helpful.
