### ISSUE TITLE
High Severity Security Vulnerability with one of your Dependancies

### ISSUE THREAD

**Issue by dustmoo** [Automattic/kue#961]
High severity vuln found in minimatch@0.3.0, introduced via kue@0.11.1
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:minimatch:20160620
- from: kue@0.11.1 > stylus@0.52.4 > glob@3.2.11 > minimatch@0.3.0

**Comment by behrad** [comment]
this should be fixed in 0.11.2 by upgrading to stylus 0.54.x
