### ISSUE TITLE
Error: job "425596" doesnt exist

### ISSUE THREAD

**Issue by Deadly0** [Automattic/kue#971]
Is someone know why this issue my appears and how to catch it? I do not remove any jobs manually, use only `.removeOnComplete(true)`

```
Error: job "425596" doesnt exist
     at Command.callback (/home/carmod/www/avitoparser/bundle/programs/server/npm/node_modules/kue/lib/queue/job.js:178:17)
     at normal_reply (/home/carmod/www/avitoparser/bundle/programs/server/npm/node_modules/redis/index.js:714:21)
     at RedisClient.return_reply (/home/carmod/www/avitoparser/bundle/programs/server/npm/node_modules/redis/index.js:816:9)
     at JavascriptRedisParser.Parser.returnReply (/home/carmod/www/avitoparser/bundle/programs/server/npm/node_modules/redis/index.js:188:18)
     at JavascriptRedisParser.execute (/home/carmod/www/avitoparser/bundle/programs/server/npm/node_modules/redis-parser/lib/parser.js:415:12)
     at Socket.<anonymous> (/home/carmod/www/avitoparser/bundle/programs/server/npm/node_modules/redis/index.js:267:27)
     at emitOne (events.js:77:13)
     at Socket.emit (events.js:169:7)
     at readableAddChunk (_stream_readable.js:153:18)
     at Socket.Readable.push (_stream_readable.js:111:10)
```

**Comment by behrad** [comment]
Are you sure there's no race happening between job complete/removal and your code handling that job?

**Comment by behrad** [comment]
the above code doesn't seem to be problematic, can you create a gist that is re-producing the same error, so that I can debug it?

**Comment by dindurthy** [comment]
We've been hitting this too.  It's occasional enough to be likely one or more race conditions.  I see two possible causes assuming you use removeOnComplete:

1) We notice crashes fairly frequently if we use the kue UI to update the state of a failed job to inactive.  I believe the code calls lib/routes/json.js:
```
exports.updateState = function( req, res ) {
  var id    = req.params.id
    , state = req.params.state;

  Job.get(id, function( err, job ) {
    if( err ) return res.json({ error: err.message });
    job.state(state);
    job.save(function( err ) {
      if( err ) return res.json({ error: err.message });
      res.json({ message: 'updated state' });
    });
  });
};
```
Here, we update state and _then_ save the job.  job.state commits an async transaction that will remove the job old state, e.g. q:jobs:type:failed, and another async transaction to create the new state, e.g. q:jobs:type:inactive.  job.save calls job.update --> job.state, which will reset the inactive state.  In between, seems plausible that a worker could grab the job.  If that happens, the worker will process --> complete the job --> error on picking up the next inactive job which has the completed jobs id.

2) Even within job.state, we have two async transactions when changing the state, removing the old state and establishing the new state:
```
if( oldState && oldState != '' && oldState != state ) {
  multi
    .zrem(client.getKey('jobs:' + oldState), this.zid)
    .zrem(client.getKey('jobs:' + this.type + ':' + oldState), this.zid);
}
multi
  .hset(client.getKey('job:' + this.id), 'state', state)
  .zadd(client.getKey('jobs:' + state), this._priority, this.zid)
  .zadd(client.getKey('jobs:' + this.type + ':' + state), this._priority, this.zid);
```
I don't _think_ these are guaranteed to work in order.  More importantly--and correct me if I'm wrong here--I _think_ it is possible that two rounds of delayed job promotion could elapse before the the old state is removed from Redis.  If a worker picks up the job in between, again we will hit the error.

**Comment by tobalsgithub** [comment]
I'm able to reproduce this by artificially making job promotion take longer than 2 seconds. In `checkJobPromotion` I do

```js
setTimeout(function(){
  job.inactive(doUnlock);
}, 3000);
```

Adding multiple jobs to a queue causes a crash pretty quickly, as we ultimately try to promote a job that is already gone.

The only reason I can see the job promotion taking more than 2 seconds in the real world is if the redis transactions are slowed down for some reason. Perhaps the server is under severe load, or maybe the job is really big or something. 

An option to increase the lock timeout might be nice for those of us that are hitting this.

**Comment by tobalsgithub** [comment]
Created https://github.com/Automattic/kue/pull/1018 to help mitigate this
