### ISSUE TITLE
Getting `Error: Shutdown already in progress` after calling `shutdown` on 2 separate queues

### ISSUE THREAD

**Issue by olalonde** [Automattic/kue#973]
I'm getting the following error after rapidly calling `shutdown` on 2 different queue instances:

```
      Error: Shutdown already in progress
          at Queue.shutdown (/app/node_modules/kue/lib/kue.js:379:15)
```

I'm actually waiting for the first queue to be `shutdown` before shutting down the second one.

**Comment by behrad** [comment]
It clearly says you can't subsequent shutdowns....
remember that `createQueue` returns singleton and you only have a single queue instance in each process. You need to call shutdown only once.

**Comment by olalonde** [comment]
Oh, that sucks. Is there any plan to get rid of that singleton architecture in the future?

**Comment by behrad** [comment]
version 1.x will not be a singleton

**Comment by samuelgoldenbaum** [comment]
this is critical and still occurring in v 0.11.6 two years later #1219
