### ISSUE TITLE
How do I cancel a job that's been delayed ? 

### ISSUE THREAD

**Issue by dorongutman** [Automattic/kue#976]
I'm building a mechanism that queues a job with a delay of a given amount of seconds, to allow someone else to abort the job from ever being executed.

How can I cancel the job ?
Do I just fail it with `job.state('failed');` ?

**Comment by behrad** [comment]
Any of these would work:

`Job.remove(jobId)`
`job#remove()`
`job#failed()`

**Comment by dorongutman** [comment]
@behrad will `remove` delete the job completely (with its data) or just mark it as being removed ?

**Comment by behrad** [comment]
it will completely remove the job and its data
