### ISSUE TITLE
How do I keep my connection alive?

### ISSUE THREAD

**Issue by seanlindo** [Automattic/kue#980]
compose.io hardcodes timeouts to 5 minutes, so I need some way of keeping my connection alive. I'm currently passing in ioredis via the `createClientFactory` option, but it's unclear how to access the client Kue is creating so I can re-use the connection and do a `setInterval` or something similar so it's not severed. 

Any ideas?

**Comment by AlexMotz** [comment]
@seanlindo Did you end up figuring out a solution to this problem? I think I am having similar issues once I deploy my job processors to my server they connect to Redis hosted on compose fine but after a few minutes all the docker containers crash.

**Comment by seanlindo** [comment]
@AlexMotz Because we run on AWS, I found it desirable to use SQS and have had great success doing so.

**Comment by AlexMotz** [comment]
@seanlindo Thanks for the info. What do you think of SQS? What kinda response times are you seeing? Do you find it at all limiting using an off the shelf Queue Service?

I was thinking about using RabbitMQ and Celery. From my research looks like the response times look to be a bit quicker.

**Comment by seanlindo** [comment]
@AlexMotz I think that depends on what kind of tolerance you need for your application. For my scale, the messages are worked instantaneously. In addition, the worker is hosted on Elastic Beanstalk. I haven't touched any of the business logic in over 30 days at this point. 

It's been very liberating!

I worked at CareerBuilder many years ago, and we used IronMQ and IronWorker, but over the years their prices have become prohibitive.
