### ISSUE TITLE
unhandled error on shutdown

### ISSUE THREAD

**Issue by hockeytim11** [Automattic/kue#983]
This error is not consistent and might actually be a redis issue. But during testing we try to shutdown our server and restart with a different configuration. Occasionally it will throw this error during shutdown causing a test failure. It seems to be a timing issue where a command is being processed when the shutdown is called and the error event is not being handled.

kue version: 0.11.5
redis version: 2.6.3

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
 AbortError: Stream connection ended and command aborted. It might have been pro
cessed.
    at RedisClient.flush_and_error (C:\Projects\services_engine\trunk\server\nod
e_modules\redis\index.js:351:23)
    at RedisClient.connection_gone (C:\Projects\services_engine\trunk\server\nod
e_modules\redis\index.js:586:14)
    at Socket.<anonymous> (C:\Projects\services_engine\trunk\server\node_modules
\redis\index.js:282:14)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:484:12)
```
To reproduce I was able to get it throw the error with this code. It happens pretty consistently on my machine with 100 iterations, but fewer iterations will make it less likely.
```
var kue = require('kue');

var i = process.argv[2] || 100;

function start() {
  console.log('starting', i);
  var jobQueue = kue.createQueue();
  console.log('started', i);
  jobQueue.client.on('error', function() {
    console.log('err');
  });
  jobQueue.shutdown(function() {
    console.log('kue shutdown', i--);
    if (i > 0) {
      process.nextTick(function() {
        start();
      });
    }
  });
}
start();
```

**Comment by bitliner** [comment]
I experienced the same

**Comment by behrad** [comment]
You should use `jobQueue.on('error'...)`  not `jobQueue.client.on`

**Comment by hockeytim11** [comment]
@behrad Unfortunately, the issue we are talking about isn't caught by that handler. The reason I tried the client one was because the queue level handler doesn't catch it either. Essentially, I would expect this code to work correctly without any error, and it does not on the systems I have tried it on.

```
var kue = require('kue');

var i = process.argv[2] || 100;

function start() {
  var jobQueue = kue.createQueue();
  jobQueue.shutdown(function() {
    if (i > 0) {
      process.nextTick(function() {
        start();
      });
    }
  });
}
start();
```
