### ISSUE TITLE
.delay() order

### ISSUE THREAD

**Issue by sradu** [Automattic/kue#987]
Hi!

We have a queue with million of jobs. Since these jobs affect remote sites we use  delay(random) to run them over longer periods of time.

The problem is when the queue gets backed up. Instead of running the jobs ordered based on delay()'s (which would keep the random order), we're noticing batches of the same site.

Meaning, if the queue is backed up, the order created by delay() is ignored.

Is there any way around this?

**Comment by behrad** [comment]
delayed jobs are promoted to the inactive queue, so if your inactive queue is backed up, they are sorted by priority/lexo from redis point of view.
