### ISSUE TITLE
"job is invalid" crashes

### ISSUE THREAD

**Issue by sradu** [Automattic/kue#992]
We have a pm2 cluster with 4 instances where one instance pushes 200,000 jobs to be processed.

For some reason, maybe a race condition?, we're getting a lot of :

Error node_modules/kue/lib/queue/job.js:179
job "1129073" is invalid

And the process crashes.

On our end, we actually don't care if one or two jobs don't work out. Is there any wait to avoid a crash in this situation?

**Comment by behrad** [comment]
as docs says please use `queue.on('error')`
