### ISSUE TITLE
Multiple kue workers, but target a job for a specific worker.

### ISSUE THREAD

**Issue by matt-barton** [Automattic/kue#995]
I have a system with multiple Kue workers, on separate servers, all consuming the same job queue via Redis.  Is there a way I can enqueue a job to guarantee that it will only be processed by a specific individual worker process?

Can I include a worker id in the job details or something like that?

Or, alternatively, can I enqueue a job which will be executed once by all of the worker processes?

**Comment by FLYBYME** [comment]
Yeah I suggest that you place the hostname in the job name. Kue just does a first come first serve deal with the workers.

**Comment by behrad** [comment]
these are not intended in Kue @matt-barton , so if you need such features you should look for another Queue or may be a Req/Reply middleware.
