### ISSUE TITLE
Arbitrary job name

### ISSUE THREAD

**Issue by hytromo** [Automattic/kue#996]
Suppose that I want to have a different queue per user so as each job to run one-by-one per user (but many parallel overall).

Can I implement this with kue? Something like accepting a regex for the job name or something like `user job *`.

Any idea on how to go with this problem?

Of course one solution would be to create a different job with a different name every time a user registers :100:

**Comment by behrad** [comment]
Kue doesn't support wildcard workers by design @hytromo 
You can go by a worker type per user however if it serves your case.

**Comment by lehainam125** [comment]
Oh how unfortunate,

I would love to have this feature :sob:
