### ISSUE TITLE
Redis connection issue

### ISSUE THREAD

**Issue by Caspain** [Automattic/kue#997]
Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.                0.1:6379

**Comment by Caspain** [comment]
Sorry fixed the problem needed a hosted service.

**Comment by bitliner** [comment]
@Caspain can you explain more about this?

**Comment by Caspain** [comment]
Yes actually, to fully support remote databases , it seems this construct must be conform to.
var queue = kue.createQueue({
	prefix: 'q'
	, redis: {
		port: 13406
		, host: 'redis-13406.c10.us-east-1-3.ec2.cloud.redislabs.com' //example
		, auth: 'password'
		, db: 'some-database', // if provided select a non-default redis db
	}
});

**Comment by Caspain** [comment]
If another approach is  taken, the way the module is programmed the redis will connect locally. yielding that error. This error is persistent even in the latest ^0.11 version

**Comment by Caspain** [comment]
Therefore the createClient method currently connects locally.

**Comment by notflip** [comment]
Is this still the case? In the docs it says that connecting using the url string is okay.
createQueue({redis: 'urlstring');
