### ISSUE TITLE
Updating documentation

### ISSUE THREAD

**Issue by Caspain** [Automattic/kue#998]
I realized the promote logic is updated but no new documentation.
I wish to become a contributor to update these kind of changes. The previous promote method for delayed  jobs was really problematic. Took me a while to sort it out. Wish to ease future readers pain.

**Comment by Caspain** [comment]
I think the delay for jobs needs a bit more content , for one , i did not know that the delay adds the current date + delay time , i thought that it only took one time and made that absolute not relative. As mentioned previously i would like to contribute.

**Comment by behrad** [comment]
the sample usage of delay is telling the truth in docs @Caspain
